import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {writeLifecycleDisposition} from '../inventory/lifecycle-continuation.mjs';
import {retainedPricingSummary} from '../intelligence/recurring-price-eligibility.mjs';
import {currentRetainedPriceReview,targetMarketPriceReview} from './retained-pricing.mjs';
const price=()=>({service:'fixture',market:null,amount:'12',currency:'EUR',confidence:'HIGH',marketApplicability:{status:'UNKNOWN',allowedMarkets:[]},exposure:{marketTargeting:false,requiresQualifiers:true},source:{kind:'ORIGINAL_PROVIDER',hash:'a'.repeat(64),url:'https://provider.example/plans'}});
const target=o=>({id:'fixture-price-FI',service:'fixture',market:'FI',researchObjective:'SERVICE_COVERAGE',verified:[],retainedPriceReview:retainedPricingSummary({service:'fixture',market:'FI',researchObjective:'SERVICE_COVERAGE'},[o],{})});
function final(t,context){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'market-price-projection-'));context.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return writeLifecycleDisposition({directory,handoff:{cohort:{manifest:{serviceIds:['fixture']}},targets:[t]},phases:{pricing:{targets:{[t.id]:t},services:{}}},events:[],bootstrap:[],researchMarkets:{fixture:['FI']},executionComplete:true})[0];}
test('qualified market-unknown evidence survives without establishing target market',t=>{const x=target(price());assert(currentRetainedPriceReview(x));const result=final(x,t);assert.equal(result.pricing[0].status,'UNRESOLVED');assert.equal(result.pricing[0].confidence,null);assert.equal(result.productionEligible,false);});
test('exact retained established market survives serialization and missing rediscovery',t=>{const o=price();o.market='FI';o.marketApplicability={status:'ESTABLISHED',allowedMarkets:['FI']};o.exposure.marketTargeting=true;const x=JSON.parse(JSON.stringify(target(o)));x.reads=[];x.lastAcquisitionFailure='TIMEOUT';assert(targetMarketPriceReview(x));assert.equal(final(x,t).pricing[0].status,'ESTABLISHED');});
for(const mutation of [o=>{o.market='SE';},o=>{o.marketApplicability.status='TARGET_MISMATCH';},o=>{o.exposure.marketTargeting=false;},o=>{o.marketApplicability.allowedMarkets=['SE'];}])test('explicit incompatible retained scope cannot establish target',()=>{const o=price();o.market='FI';o.marketApplicability={status:'ESTABLISHED',allowedMarkets:['FI']};o.exposure.marketTargeting=true;mutation(o);assert.equal(targetMarketPriceReview(target(o)),null);});
test('current exact-price quarantine still defeats market projection',()=>{const o=price();o.market='FI';delete o.marketApplicability;delete o.exposure;const x=target(o);x.quarantinedVerified=[o];assert.equal(targetMarketPriceReview(x),null);});
