import {missingCatalogFields} from '../intelligence/management-targeting.mjs';
import {researchKnowledge} from './research-memory.mjs';
import {chooseInformationAction} from './information-routing.mjs';
// Deterministic planning metadata only. No transport and no evidence grants.
import {normalizeFrontierUrl} from './source-frontier.mjs';
export const marketLanguages={NO:'nb',SE:'sv',DK:'da',DE:'de',AT:'de',FR:'fr',BE:'fr',ES:'es',MX:'es',CL:'es',CO:'es',PT:'pt',BR:'pt',IT:'it',NL:'nl',PL:'pl',CZ:'cs',TR:'tr',TH:'th',KR:'ko',JP:'ja',CN:'zh',TW:'zh',HK:'zh',FI:'fi',RO:'ro'};
export const searchTerms={en:['pricing','subscription','membership','plans'],nb:['priser','abonnement','medlemskap','pakker'],sv:['priser','abonnemang','medlemskap','paket'],da:['priser','abonnement','medlemskab','pakker'],de:['Preise','Abonnement','Mitgliedschaft','Tarife'],fr:['tarifs','abonnement','adhésion','offres'],es:['precios','suscripción','membresía','planes'],pt:['preços','assinatura','adesão','planos'],it:['prezzi','abbonamento','iscrizione','piani'],nl:['prijzen','abonnement','lidmaatschap','pakketten'],pl:['cennik','abonament','członkostwo','pakiety'],cs:['ceník','předplatné','členství','tarify'],tr:['fiyat','abonelik','üyelik','paketler'],th:['ราคา','สมัครสมาชิก','สมาชิก','แพ็กเกจ'],ko:['가격','구독','멤버십','요금제'],ja:['料金','サブスクリプション','会員','プラン'],zh:['价格','订阅','会员','套餐'],fi:['hinnat','tilaus','jäsenyys','paketit'],ro:['prețuri','abonament','membru','pachete']};
export function categoryIntent(target){const c=String(target.category??target.categories?.join(' ')??'').toLowerCase();return /fitness|gym/.test(c)?'MEMBERSHIP':/news|press/.test(c)?'DIGITAL_SUBSCRIPTION':/audio|music|book/.test(c)?'PREMIUM_SUBSCRIPTION':/dating/.test(c)?'PREMIUM_SUBSCRIPTION':/delivery|commerce/.test(c)?'MEMBERSHIP_BENEFITS':/software|vpn|security|cloud|ai/.test(c)?'BILLING_RENEWAL':'SUBSCRIPTION_PLANS';}
export function contextualQuery(t,attempt=0){if(t.researchObjective==='CATALOG_ONLY')return [t.serviceName,t.market,missingCatalogFields(t).join('|')==='WEB_MANAGEMENT'?(attempt?'subscription payment plan change account settings help':'membership billing cancellation online account help'):missingCatalogFields(t).join('|')==='LOGIN'?'official personal account sign in help':attempt?'subscription membership billing account management':'official account login manage subscription',t.authorities?.[0]?.hostname?'site:'+t.authorities[0].hostname:null].filter(Boolean).join(' ');const lang=t.language??marketLanguages[t.market]??'en',terms=searchTerms[lang]??searchTerms.en,intent=categoryIntent(t),host=t.authorities?.[0]?.hostname,term=/MEMBERSHIP/.test(intent)?terms[2]:terms[1];return [t.serviceName??t.service,t.countryName??t.market,attempt===0?terms[0]:terms[3],term,attempt>0&&host?'site:'+host:null].filter(Boolean).join(' ');}
export function diagnoseResearch({authority=false,target=false,priceCount=0,blockers=[],failure=null,configurator=false,rendering=false,discoveryExhausted=false,navigationExhausted=false}={}){
 if(!authority)return 'AUTHORITY_UNRESOLVED';if(!target)return 'NO_PROVIDER_TARGET';
 if(configurator)return 'CONFIGURATOR_REQUIRED';if(rendering)return 'RENDERING_REQUIRED';
 if(/GEO/.test(failure??''))return 'GEO_ACCESS_FAILED';if(/ACCESS|HTTP_403|HTTP_429|TIMEOUT|NETWORK/.test(failure??''))return 'DIRECT_ACCESS_FAILED';
 if(failure)return 'ACQUISITION_FAILED';
 if(priceCount){const text=blockers.join(' ');if(blockers.length&&blockers.every(b=>/TRIAL|PROMO/.test(b)))return 'ONLY_PROMO_OR_TRIAL';if(blockers.length&&blockers.every(b=>/ADDON|SECONDARY|FEE/.test(b)))return 'ONLY_SECONDARY_FEES';for(const [re,reason]of [[/CURRENCY/,'CURRENCY_UNRESOLVED'],[/CADENCE|INTERVAL/,'CADENCE_UNRESOLVED'],[/MARKET/,'MARKET_UNRESOLVED'],[/OWNERSHIP|CONFLICT|STRUCTUR/,'PRICE_FOUND_STRUCTURE_AMBIGUOUS'],[/PLAN|PRODUCT/,'PLAN_UNRESOLVED'],[/ROLE|RECURRING/,'PRICE_ROLE_UNRESOLVED']])if(re.test(text))return reason;return 'NO_SAFE_APP_PRICE';}
 return discoveryExhausted?'DISCOVERY_EXHAUSTED':navigationExhausted?'PROVIDER_NAVIGATION_EXHAUSTED':'NO_PRICE_DETECTED';
}
function planResearchUnrestricted(t,{retained=null,diagnosis=null,history=[],unreadUrls=null,configurationDemonstrated=false,renderingDemonstrated=false,discoveryAllowed=true,executionContext}={}){
 if(t.smartResearch?.version===2){const knowledge=researchKnowledge(t),action=chooseInformationAction(t,{knowledge,executionContext,discoveryAllowed,retained:retained??t.retainedPriceReview,configurationDemonstrated:configurationDemonstrated||t.demonstratedConfigurator===true,renderingDemonstrated:renderingDemonstrated||t.demonstratedRendering===true,urls:unreadUrls??t.urls??[]});return {version:2,...action,knowledge,service:t.service,requestedMarket:t.market,marketApplicabilityEstablished:false,language:t.language??marketLanguages[t.market]??'en',categoryIntent:categoryIntent(t),query:['DISCOVERY','AUTHORITY_DISCOVERY'].includes(action.route)?contextualQuery(t,knowledge.attempts.filter(a=>a.route==='DISCOVERY').length):null,directAppropriate:action.route==='DIRECT',discoveryRequired:['DISCOVERY','AUTHORITY_DISCOVERY'].includes(action.route),decodoConditional:true,configuratorEnabled:false,browserEnabled:false,evidenceStatus:'PLANNING_ONLY',bounds:{reads:4,depth:3,width:2}};}
 const authority=(t.authorities??[]).filter(a=>a.provider===t.serviceName&&a.checkedAt&&['OFFICIAL_PROVIDER','OFFICIAL_SUPPORT'].includes(a.sourceType));
 const urls=(unreadUrls??t.urls??[]).map(u=>normalizeFrontierUrl(u).url).filter(u=>u&&authority.some(a=>a.hostname===new URL(u).hostname));
 const completed=new Set(history.filter(h=>h.completed).map(h=>h.route+'|'+h.url));const fresh=urls.filter(u=>!completed.has('DIRECT|'+u));
 let route,reason;
 if(retained?.sourceBound===true&&['HIGH','MEDIUM'].includes(retained.confidence)&&(retained.market===t.market||retained.objective==='SERVICE_COVERAGE')){route='RETAINED_SUFFICIENT';reason='SOURCE_BOUND_PRICE_ALREADY_AVAILABLE';}
 else if(configurationDemonstrated){route='PARK_CONFIGURATOR';reason='CONFIGURATOR_REQUIRED';}
 else if(renderingDemonstrated){route='PARK_RENDERING';reason='RENDERING_REQUIRED';}
 else if(!authority.length){route='AUTHORITY_DISCOVERY';reason='AUTHORITY_UNRESOLVED';}
 else if(['DIRECT_ACCESS_FAILED','GEO_ACCESS_FAILED'].includes(diagnosis)&&history.some(h=>h.route==='DIRECT'&&h.completed&&h.failure===diagnosis&&h.escalationPermitted===true&&urls.includes(h.url))){route='CONDITIONAL_DECODO';reason=diagnosis;}
 else if(diagnosis==='PRICE_FOUND_STRUCTURE_AMBIGUOUS'&&!fresh.length){route='STRUCTURED_REINTERPRETATION';reason=diagnosis;}
 else if(fresh.length){route='DIRECT';reason=history.length?'ALTERNATE_REVIEWED_PROVIDER_DESTINATION':'REVIEWED_PROVIDER_FIRST';}
 else if(history.filter(h=>h.route==='DISCOVERY'&&h.completed).length>=2){route='STOP';reason='DISCOVERY_EXHAUSTED';}
 else {route='DISCOVERY';reason=urls.length?'PROVIDER_NAVIGATION_EXHAUSTED':'NO_PROVIDER_TARGET';}
 const failedUrl=history.find(h=>h.route==='DIRECT'&&h.completed&&h.failure===diagnosis&&h.escalationPermitted===true&&urls.includes(h.url))?.url;const url=route==='CONDITIONAL_DECODO'?failedUrl??null:fresh[0]??urls[0]??null;if(route==='CONDITIONAL_DECODO'&&completed.has(route+'|'+url)){route='STOP';reason='ACQUISITION_FAILED';}
 return {version:1,service:t.service,requestedMarket:t.market,marketApplicabilityEstablished:false,language:t.language??marketLanguages[t.market]??'en',categoryIntent:categoryIntent(t),route,reason,url,query:['DISCOVERY','AUTHORITY_DISCOVERY'].includes(route)?contextualQuery(t,history.filter(h=>h.route==='DISCOVERY').length):null,expectedPageType:categoryIntent(t),directAppropriate:route==='DIRECT',discoveryRequired:['DISCOVERY','AUTHORITY_DISCOVERY'].includes(route),decodoConditional:true,configuratorEnabled:false,browserEnabled:false,evidenceStatus:'PLANNING_ONLY',bounds:{reads:4,depth:3,width:2},historyKey:JSON.stringify([t.service,t.market,route,url,reason])};
}

export function planResearch(target,options={}){
 const c=target.capabilities;if(!c)return planResearchUnrestricted(target,options);
 const plan=planResearchUnrestricted(target,{...options,discoveryAllowed:c.tavily&&options.discoveryAllowed!==false});
 if(plan.route==='DIRECT'&&!c.direct){if(c.tavily&&options.discoveryAllowed!==false)return {...plan,route:'DISCOVERY',directAppropriate:false,discoveryRequired:true,query:contextualQuery(target,0)};return {...plan,route:'STOP',reason:'CAPABILITY_DISABLED_DIRECT',directAppropriate:false,discoveryRequired:false};}
 if(['DISCOVERY','AUTHORITY_DISCOVERY'].includes(plan.route)&&!c.tavily)return {...plan,route:'STOP',reason:'CAPABILITY_DISABLED_TAVILY',discoveryRequired:false};
 if(plan.route==='CONDITIONAL_DECODO'&&!c.decodo)return {...plan,route:'STOP',reason:'CAPABILITY_DISABLED_DECODO'};
 return plan;
}
