import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {lifecycleSeed} from './lifecycle-continuation.mjs';
import {runAdaptiveCampaign} from './adaptive-campaign.mjs';
import {createResearchMemory,combineResearchMemory} from '../live/research-memory.mjs';
const cwd=process.cwd(),root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'access-compat-')));process.chdir(root);after(()=>{process.chdir(cwd);fs.rmSync(root,{recursive:true,force:true});});
const origin='https://provider.example',account='https://account.provider.example',parent=origin+'/membership',requested=parent+'/one',sibling=origin+'/plans';
const base=()=>({id:'fixture-price-DE',service:'fixture',serviceName:'Fixture',market:'DE',researchObjective:'SERVICE_COVERAGE',smartResearch:{version:2},capabilities:{direct:true,tavily:true,decodo:true,browser:false,groq:false},authorities:[{hostname:'provider.example',provider:'Fixture',sourceType:'OFFICIAL_PROVIDER',checkedAt:'2026-09-25'}],urls:[parent,requested,sibling],leads:[{url:sibling,title:'Membership market terms',rank:0}],gaps:['market'],reads:[],queries:[],decisions:[],blockedOrigins:[],marketProof:{objectives:[{key:'identity',identity:{plan:'Basic'},status:'MARKET_NOT_VERIFIED',missingFact:'MARKET_PROOF'}]}});
const decision=(url,extra={})=>({targetUrl:url,origin:new URL(url).origin,robotsUrl:new URL(url).origin+'/robots.txt',httpStatus:200,decision:'ALLOWED',reason:'NO_APPLICABLE_RESTRICTION',rule:null,boundary:'SAFE_TO_EVALUATE',...extra});
const stopped=()=>({requestedUrl:requested,url:requested,outcome:'ACCESS_CONTROL_STOP',failure:{code:'ROBOTS_ACCESS_STOP'},redirects:[account+'/membership/one'],accessDecisions:[decision(requested),decision(account+'/membership/one',{decision:'ROBOTS_INVALID',reason:'ROBOTS_NOT_TEXT_PLAIN',boundary:undefined,groups:[]})]});
let n=0;function save(t){const file=root+'/state-'+(++n)+'.json';const bytes=JSON.stringify({targets:{[t.id]:t}});fs.writeFileSync(file,bytes);return {target:structuredClone(t),reference:{path:file,hash:createHash('sha256').update(bytes).digest('hex')}};}
function legacy(change=()=>{}){const t=base();t.priorUsage={reads:0,searches:0,reference:save(base()).reference};t.reads=[{requestedUrl:parent,url:parent,outcome:'OK',accessDecisions:[decision(parent)]},stopped()];t.blockedOrigins=[origin];change(t);return save(t);}
// Reproduce the old seeding semantics, including a no-work intermediate lifecycle.
function oldSeed(entry){const t=structuredClone(entry.target);t.researchMemory=combineResearchMemory(t,[t.researchMemory,createResearchMemory(t,entry.reference)].filter(Boolean));t.priorUsage={reads:t.reads.length,searches:0,reference:entry.reference};t.reads=[];t.queries=[];t.decisions=[];return t;}
const seed=entry=>lifecycleSeed(base(),{states:{[entry.target.id]:entry}});
test('legacy redirect block across zero-work parent reaches sibling acquisition and resumes without refilling usage',async()=>{
 const first=legacy(),middle=save(oldSeed(first)),t=seed(middle);const dir=root+'/campaign';let reads=0,searches=0,acquisitions=0;const events=[];
 const options={directory:dir,manifest:{targets:[t],conditionalFollowupTargets:[]},maxActions:1,onTransition:e=>events.push(e),createAdapters:async()=>({read:async({url})=>{assert.equal(url,sibling);reads++;return {url,outcome:'OK'};},search:async()=>{searches++;throw Error('UNEXPECTED_SEARCH');},classify:async()=>({eligible:true}),acquire:async()=>{acquisitions++;throw Error('UNEXPECTED_DECODO');}})};
 const state=await runAdaptiveCampaign(options);assert.equal(reads,1,'stale block must not terminate with zero reads');assert(events.includes('RESERVED'));assert.deepEqual(t.blockedOrigins,[account]);assert.deepEqual(t.researchMemory.blockedOrigins,[account]);assert.equal(searches,0);assert.equal(acquisitions,0);assert.equal(state.services.fixture.used.reads,1);
 const saved=save(t),again=seed(saved);assert.deepEqual(again.blockedOrigins,[account]);assert.deepEqual(again.capabilities,base().capabilities);
 const resumed=await runAdaptiveCampaign({...options,maxActions:1,stopBeforeNetwork:true});assert.equal(resumed.services.fixture.used.reads,1);assert.equal(reads,1);assert.equal(resumed.bounds.reads,state.bounds.reads);
});
test('legacy path denial corrects origin scope but preserves denied request history',()=>{const t=seed(legacy(t=>{t.reads[1].redirects=[];t.reads[1].accessDecisions=[decision(requested,{decision:'DISALLOWED',reason:'MATCHED_RULE',boundary:'APPLICABLE_DISALLOW',rule:{directive:'disallow',path:'/membership/one'}})];}));assert.deepEqual(t.blockedOrigins,[]);assert(t.researchMemory.attempts.some(a=>a.url===requested&&a.failure==='ROBOTS_ACCESS_STOP'));});
for(const kind of ['global','prohibition','missing','independent','tamper','unknown-inherited'])test(kind+' restriction is not cleared',()=>{
 const entry=legacy(t=>{if(kind==='global')t.reads[1].accessDecisions=[decision(requested,{decision:'DISALLOWED',reason:'MATCHED_RULE',boundary:'APPLICABLE_DISALLOW',rule:{directive:'disallow',path:'/'}})];if(kind==='prohibition')t.reads[1].accessDecisions=[decision(requested,{decision:'REVIEW_REQUIRED',reason:'EXPLICIT_PROVIDER_PROHIBITION'})];if(kind==='missing')delete t.reads[1].accessDecisions;if(kind==='independent')t.acquisitionOutcomes=[{url:requested,classification:'PROVIDER_RESTRICTED'}];if(kind==='unknown-inherited')t.researchMemory={blockedOrigins:[origin]};});
 if(kind==='tamper')fs.appendFileSync(entry.reference.path,' ');assert(seed(entry).blockedOrigins.includes(origin));
});
test('genuine restriction in predecessor survives a later redirect denial',()=>{const prior=legacy(t=>{t.reads[1].accessDecisions=[decision(requested,{decision:'REVIEW_REQUIRED',reason:'EXPLICIT_PROVIDER_PROHIBITION'})];});const t=oldSeed(prior);t.reads=[stopped()];const result=seed(save(t));assert(result.blockedOrigins.includes(origin));});
test('missing ancestor stays restricted, without altering retained files',()=>{const first=legacy(),entry=save(oldSeed(first)),bytes=fs.readFileSync(entry.reference.path);fs.unlinkSync(first.reference.path);assert(seed(entry).blockedOrigins.includes(origin));assert.deepEqual(fs.readFileSync(entry.reference.path),bytes);});
test('current redirect-origin restriction and immutable predecessor survive seeding',()=>{const entry=legacy(t=>{t.blockedOrigins=[account];}),bytes=fs.readFileSync(entry.reference.path);assert.deepEqual(seed(entry).blockedOrigins,[account]);assert.deepEqual(fs.readFileSync(entry.reference.path),bytes);});
test('corrected scope never enables an operator-prohibited acquisition',async()=>{const t=seed(legacy());t.capabilities={direct:false,decodo:false,tavily:false,browser:false,groq:false};let calls=0;const s=await runAdaptiveCampaign({directory:root+'/off',manifest:{targets:[t],conditionalFollowupTargets:[]},createAdapters:async()=>{calls++;throw Error('OFF');}});assert.equal(calls,0);assert.equal(s.services.fixture.used.reads,0);assert.deepEqual(s.targets[t.id].capabilities,t.capabilities);});
test('no proven pre-read baseline cannot authorize a legacy correction',()=>{const entry=legacy(t=>{delete t.priorUsage;});assert(seed(entry).blockedOrigins.includes(origin));});
