import '../offline-replay/offline-guard.mjs';
import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {initializeAdaptiveState,assessAdaptiveService,targetExecutionContext} from './adaptive-campaign.mjs';
import {createResearchMemory} from '../live/research-memory.mjs';
import {destinationDiscoveryNeeded} from '../live/open-web-discovery.mjs';
import {executableAction,exhaustedExecutionBudget} from '../live/execution-capabilities.mjs';
import {planResearch} from '../live/research-planner.mjs';
import {lifecycleBudgets} from './lifecycle-continuation.mjs';
const cwd=process.cwd(),root=fs.mkdtempSync(path.join(os.tmpdir(),'v2-actionable-'));process.chdir(root);after(()=>{process.chdir(cwd);fs.rmSync(root,{recursive:true});});
const ref={path:'history.json',hash:createHash('sha256').update('[]').digest('hex')};fs.writeFileSync(ref.path,'[]');
function target({history=false,extra=[],capabilities={},reads=[],queries=[]}={}){const t={id:'fixture-catalog',service:'fixture',serviceName:'Fixture',market:null,researchObjective:'CATALOG_ONLY',smartResearch:{version:2},authorities:[{hostname:'provider.example',provider:'Fixture',checkedAt:'2026-01-01',sourceType:'OFFICIAL_PROVIDER'}],catalogEligibility:{status:'LOGIN_ONLY_ESTABLISHED'},gaps:['WEB_MANAGEMENT'],urls:['https://provider.example/support','https://provider.example/offer'],leads:[{url:'https://provider.example/support',title:'Support',rank:0},{url:'https://provider.example/offer',title:'Fixture',rank:1},...extra.map(url=>({url,title:'Billing management',rank:2}))],reads,queries,decisions:[],blockedOrigins:[],capabilities:{direct:true,tavily:true,decodo:false,browser:false,groq:false,...capabilities}};if(history)t.researchMemory=createResearchMemory({...t,reads:[{requestedUrl:t.urls[0],url:'https://provider.example/help',outcome:'OK'}]},ref);return t;}
function assess(t,limits={}){const state=initializeAdaptiveState({targets:[t],conditionalFollowupTargets:[]},{limits});return {state,result:assessAdaptiveService(state,t.service)};}
test('allowed semantic reason never means exhausted',()=>{assert.equal(exhaustedExecutionBudget({executable:true,reason:'CAPABILITY_AND_BUDGET_ALLOWED'}),false);assert.equal(exhaustedExecutionBudget({executable:false,reason:'DESTINATION_OR_ORIGIN_LIMIT'}),false);assert.equal(exhaustedExecutionBudget({executable:true,reason:'DIRECT_BUDGET_EXHAUSTED'}),false);});
for(const reason of ['DIRECT_BUDGET_EXHAUSTED','DISCOVERY_BUDGET_EXHAUSTED','DECODO_BUDGET_EXHAUSTED'])test('explicit failed budget '+reason,()=>assert(exhaustedExecutionBudget({executable:false,reason})));
test('fresh relevant URL remains Direct first',()=>{const {state,result}=assess(target());assert.equal(result.next.plan.route,'DIRECT');const t=state.targets['fixture-catalog'],c=targetExecutionContext(state,t);assert.equal(destinationDiscoveryNeeded(t,c.bounds,c.usage),false);});
test('history suppresses Direct but no longer suppresses bounded discovery',()=>{const {state,result}=assess(target({history:true}));assert.equal(result.next.plan.route,'DISCOVERY');assert.equal(result.next.plan.candidates.length,0);assert.equal(result.stop,null);assert.equal(result.next.plan.avoidedRepeatedDestinations,1);assert.deepEqual(state.services.fixture.used,{reads:0,searches:0,acquisitions:0,retainedReviews:0});});
test('single-service map and 36 new-request ceiling remain unchanged',()=>{const {state,result}=assess(target({history:true}));assert.deepEqual(state.serviceOrder,['fixture']);assert.equal(result.next.targetId,'fixture-catalog');const budget=lifecycleBudgets({targets:[{service:'fixture'}],cohort:{manifest:{serviceIds:['fixture']}},config:{executionServices:['fixture']}});assert.equal(budget.total,36);assert.equal(state.turn,0);});
test('a fresh alternative beats discovery even with historical support',()=>{const {result}=assess(target({history:true,extra:['https://provider.example/billing']}));assert.equal(result.next.plan.route,'DIRECT');assert.equal(result.next.plan.url,'https://provider.example/billing');});
test('irrelevant known offer cannot suppress discovery',()=>{const t=target();t.leads=t.leads.slice(1);t.urls=t.urls.slice(1);assert.equal(assess(t).result.next.plan.route,'DISCOVERY');});
test('disabled discovery preserves capability stop',()=>{const r=assess(target({history:true,capabilities:{tavily:false}})).result;assert.equal(r.next,null);assert.equal(r.stop.reason,'CAPABILITY_DISABLED_TAVILY');assert.notEqual(r.stop.kind,'BUDGET_LIMITED');});
test('disabled Direct and Tavily never force acquisition',()=>{const r=assess(target({capabilities:{direct:false,tavily:false}})).result;assert.equal(r.next,null);assert.equal(r.stop.reason,'CAPABILITY_DISABLED_TAVILY');});
test('explicit discovery policy denial preserves real cause despite allowed Direct metadata',()=>{const t=target({history:true});const p=planResearch(t,{discoveryAllowed:false,unreadUrls:t.leads.map(l=>l.url)});assert.equal(p.reason,'KNOWN_DESTINATION_NEEDS_EVIDENCE_NOT_SEARCH');assert(p.evaluated.some(x=>x.eligible&&x.capability.executable));});
test('zero read budget is explicit exhaustion',()=>assert.equal(assess(target(),{reads:0,searches:0}).result.stop.reason,'BUDGET_EXHAUSTED'));
test('zero search budget after historical read is explicit exhaustion',()=>assert.equal(assess(target({history:true}),{searches:0}).result.stop.reason,'BUDGET_EXHAUSTED'));
test('acquisition budget failure remains explicit',()=>{const t=target();t.capabilities.decodo=true;assert.equal(executableAction(t,{route:'CONDITIONAL_DECODO',escalation:{eligible:true}},{bounds:{perServiceAcquisitions:0,acquisitions:0},usage:{acquisitions:0}}).reason,'DECODO_BUDGET_EXHAUSTED');});
test('provider-access stop is not budget exhaustion',()=>{const t=target({history:true});t.blockedOrigins=['https://provider.example'];const r=assess(t).result;assert.equal(r.next,null);assert.equal(r.stop.reason,'PROVIDER_ACCESS_POLICY_STOP');});
test('historical discovery limit remains exhaustion of discovery, not new request budget',()=>{const t=target({history:true});t.researchMemory=createResearchMemory({...t,reads:[{requestedUrl:t.urls[0],outcome:'OK'}],queries:[{query:'first'},{query:'second'}]},ref);const r=assess(t).result;assert.equal(r.next,null);assert.equal(r.stop.reason,'DISCOVERY_EXHAUSTED');});
test('same retained memory on repeated assessment never grants duplicate Direct',()=>{const t=target({history:true});for(let i=0;i<3;i++)assert.equal(assess(structuredClone(t)).result.next.plan.route,'DISCOVERY');assert.equal(t.reads.length,0);});
test('completed objective never forces discovery',()=>{const t=target({history:true});t.catalogEligibility.status='LOGIN_MANAGE_ESTABLISHED';t.loginManageEstablished=true;assert.equal(assess(t).result.next,null);});
