import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {snapshotLifecycle,lifecycleSeed,lifecycleBudgets,validateLifecycleSnapshot} from './lifecycle-continuation.mjs';
import {initializeAdaptiveState} from './adaptive-campaign.mjs';
import {continuationLocation} from './reviewed-cohort-execution.mjs';
const generation='11111111-1111-1111-1111-111111111111';
function fixture(t){const cwd=process.cwd(),root=fs.mkdtempSync(path.join(os.tmpdir(),'fresh-execution-'));process.chdir(root);t.after(()=>{process.chdir(cwd);fs.rmSync(root,{recursive:true,force:true});});const targets=['north','south'].map(service=>({service,id:service+'-catalog',serviceName:service,authorities:[],gaps:[],researchObjective:'CATALOG_ONLY'})),handoff={config:{runsRoot:'runs'},cohort:{manifest:{serviceIds:targets.map(t=>t.service)}},document:{bindings:[]},inputHashes:{},targets,rows:[],summary:{historicalRequests:0}};const dir='runs/mature-lifecycle-old';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/lineage.json',JSON.stringify({cohort:handoff.cohort.manifest.serviceIds,fingerprint:'old'}));fs.writeFileSync(dir+'/network.jsonl',JSON.stringify({service:'north',kind:'DIRECT'})+'\n');fs.writeFileSync(dir+'/summary.json',JSON.stringify({executionComplete:false,additionalRequests:1}));fs.mkdirSync(dir+'/catalog');fs.writeFileSync(dir+'/catalog/adaptive-state.json',JSON.stringify({turn:55,cursor:1,pending:{uncommitted:true},targets:{'north-catalog':{...targets[0],verified:[{unproven:true}],done:'BUDGET_EXHAUSTED'}}}));return {dir,handoff,targets,args:{handoff,runsRoot:'runs',researchMarkets:{},codeHash:'current',executionGeneration:generation}};}
test('fresh generation excludes interrupted checkpoint and preserves historical accounting without spending fresh budget',t=>{const f=fixture(t);assert.throws(()=>snapshotLifecycle({...f.args,executionGeneration:undefined}),/LIFECYCLE_PARENT_NOT_RECONCILED/);const snapshot=snapshotLifecycle(f.args);assert.deepEqual(snapshot.parents,[]);assert.deepEqual(snapshot.states,{});assert.deepEqual(snapshot.sources,{});assert.equal(snapshot.parentRequests,0);assert.equal(snapshot.supersededRequests,1);assert.equal(snapshot.supersededExecutions.length,1);const seeds=f.targets.map(t=>lifecycleSeed(t,snapshot)),state=initializeAdaptiveState({targets:f.targets,conditionalFollowupTargets:[]},{retainedStates:seeds});assert.equal(state.turn,0);assert.equal(state.cursor,0);assert.equal(state.pending,null);assert.deepEqual(state.decisionHistory,[]);assert.equal(state.complete,false);for(const s of Object.values(state.services))assert.deepEqual(s.used,{reads:0,searches:0,acquisitions:0,retainedReviews:0});assert.deepEqual(lifecycleBudgets(f.handoff),{byService:{north:36,south:36},total:72});assert(!JSON.stringify(seeds).includes('unproven'));const next=snapshotLifecycle({...f.args,executionGeneration:'22222222-2222-2222-2222-222222222222'});assert.notEqual(continuationLocation(f.handoff,{},false,null,null,snapshot).directory,continuationLocation(f.handoff,{},false,null,null,next).directory);});
test('historical ledger remains bound and cannot silently change after snapshot',t=>{const f=fixture(t),snapshot=snapshotLifecycle(f.args);fs.appendFileSync(f.dir+'/network.jsonl',JSON.stringify({service:'south',kind:'DIRECT'})+'\n');assert.throws(()=>validateLifecycleSnapshot(snapshot),/LIFECYCLE_IMMUTABLE_INPUT_CHANGED/);});
test('fresh generation cannot abandon an active execution',t=>{const f=fixture(t);fs.writeFileSync(f.dir+'/catalog/adaptive.lock',String(process.pid));assert.throws(()=>snapshotLifecycle(f.args),/LIFECYCLE_PARENT_ACTIVE/);});
test('out-of-cohort and partial historical ledger fail closed',t=>{const f=fixture(t);fs.writeFileSync(f.dir+'/network.jsonl',JSON.stringify({service:'foreign',kind:'DIRECT'})+'\n');assert.throws(()=>snapshotLifecycle(f.args),/LIFECYCLE_HISTORICAL_ACCOUNTING/);fs.writeFileSync(f.dir+'/network.jsonl',JSON.stringify({service:'north',kind:'DIRECT'}));assert.throws(()=>snapshotLifecycle(f.args),/LIFECYCLE_HISTORICAL_ACCOUNTING/);});

test('missing historical ledger cannot erase reported usage',t=>{const f=fixture(t);fs.unlinkSync(f.dir+'/network.jsonl');assert.throws(()=>snapshotLifecycle(f.args),/LIFECYCLE_HISTORICAL_ACCOUNTING/);});

for(const entry of ['services/api/src/v2-operations/worker.mjs','docs/catalog/global-47/research-v2/run-v15-mature-v2.mjs'])test('fresh snapshot preserves active parent exclusion: '+entry,async t=>{
 const f=fixture(t),{spawn}=await import('node:child_process'),file=path.resolve(entry);
 fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,"console.log('ready');setInterval(()=>{},1000);");
 const child=spawn(process.execPath,[file,...(entry.endsWith('/worker.mjs')?['--execute','33333333-3333-3333-3333-333333333333']:['--lifecycle','--live'])],{stdio:['ignore','pipe','pipe']});t.after(()=>child.kill());await new Promise((resolve,reject)=>{child.once('error',reject);child.stdout.once('data',resolve);});
 const lock=f.dir+'/handoff.lock';fs.writeFileSync(lock,String(child.pid));
 for(let i=0;i<2;i++)assert.throws(()=>snapshotLifecycle(f.args),/LIFECYCLE_PARENT_ACTIVE/);
 assert.equal(fs.readFileSync(lock,'utf8'),String(child.pid));
 const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;
 assert.equal(snapshotLifecycle(f.args).supersededRequests,1);assert.equal(fs.readFileSync(lock,'utf8'),String(child.pid));
});
