// Shadow refresh identity and semantic fingerprints. Never a price-admission gate.
import {createHash} from 'node:crypto';
import {monetary} from '../offline-recovery/extract.mjs';
export const stable=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
export const digest=x=>createHash('sha256').update(typeof x==='string'?x:stable(x)).digest('hex');
export const normalizeText=x=>String(x??'').normalize('NFKC').replace(/\s+/g,' ').trim();
export function publicUrl(value){const u=new URL(value);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||/^(localhost|127\.|0\.|\[|10\.|192\.168\.)/i.test(u.hostname))throw Error('PUBLIC_PROVIDER_URL_REQUIRED');u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(gclid|fbclid)$/i.test(k))u.searchParams.delete(k);u.searchParams.sort();return u.href;}
export function semanticValue(x){if(x==null)return null;if(Array.isArray(x))return x.map(semanticValue);if(typeof x!=='object')return x;const excluded=new Set(['sourceHash','bodyHash','path','ownerPath','raw','start','end','evidence','originalWording','coordinate']);return Object.fromEntries(Object.entries(x).filter(([k])=>!excluded.has(k)).map(([k,v])=>[k,semanticValue(v)]));}
export function priceFacts(o){const context=normalizeText(o.qualifiers?.sourceCommercialContext??'');let text=context;const ownMoney=monetary(context).filter(m=>m.amount===String(o.amount));for(const m of ownMoney.length===1?ownMoney:[])text=text.slice(0,m.start)+'[OWN_PRICE]'+text.slice(m.end);
 return {service:o.service,market:o.market??null,plan:o.plan??null,providerPlanId:o.providerPlanId??null,amount:String(o.amount),currency:o.currency,interval:o.billingInterval?.normalized??o.cadence??o.exactInterval??null,role:o.commercialRole??'ORDINARY_RECURRING',scope:semanticValue(o.scope??{}),commitment:semanticValue(o.commitment??o.qualifiers?.commitment??null),variants:semanticValue(o.qualifiers?.offerVariants??o.offerObject?.dimensions??{}),product:semanticValue(o.qualifiers?.product??[]),priceQualifiers:semanticValue(o.qualifiers?.price??[]),qualification:o.refreshQualification??null,commercialContext:text||null,nationallyUniversal:false};}
export function offerKey(f){return digest({...f,amount:undefined,commercialContext:undefined});}
export function fingerprints(body,facts){const offer={...facts,amount:undefined};return {raw:digest(body),normalizedContent:digest(normalizeText(body)),offer:digest(offer),price:digest({amount:facts.amount,currency:facts.currency,interval:facts.interval})};}
export function createProviderSource({service,provider,url,finalUrl=url,market=null,scope={},authority,receipt,route='DIRECT',observedAt=null,geoRequired=false,reference}){
 const first=publicUrl(url),last=publicUrl(finalUrl);if(!service||!provider||!authority?.checkedAt||authority.provider!==provider||authority.hostname!==new URL(last).hostname||!['OFFICIAL_PROVIDER','OFFICIAL_SUPPORT','OFFICIAL_PARTNER'].includes(authority.sourceType)||!receipt?.intact||!receipt.serviceEstablished||receipt.service!==service||!reference?.path||!reference.hash)throw Error('SOURCE_AUTHORITY_PROVENANCE_REQUIRED');
 const scopeKey=digest({market,scope:semanticValue(scope)}),id='provider-source:'+digest({service,provider,anchor:first,scopeKey});return {version:1,id,service,provider,market,scope:semanticValue(scope),scopeKey,anchorUrl:first,lastSuccessfulUrl:last,aliases:[...new Set([first,last])],authority:structuredClone(authority),route,lastSuccessfulAcquisition:observedAt,geoRequired,reference:structuredClone(reference),authoritative:true,requiresConfigurator:false,requiresRendering:false};
}
export function seedRefreshUnit({observation,source,body,observedAt=null,interpretationVersion,reference}){
 if(observation.source?.kind!=='ORIGINAL_PROVIDER'||observation.source.hash!==digest(body)||source.service!==observation.service||!['HIGH','MEDIUM'].includes(observation.confidence??(observation.trustworthy?'HIGH':null))||!interpretationVersion||!reference?.path||!reference.hash)throw Error('ACCEPTED_BOUND_OBSERVATION_REQUIRED');
 const facts=priceFacts(observation);if(!/^\d+(?:\.\d+)?$/.test(facts.amount)||Number(facts.amount)<=0||!/^[A-Z]{3}$/.test(facts.currency)||!facts.interval)throw Error('EXACT_PRICE_REQUIRED');const key=offerKey(facts),id='refresh-unit:'+digest([source.id,key]),confidence=observation.confidence??'HIGH';
 const entry={id:'price-history:'+digest([id,observation.source.hash,facts]),facts,confidence,firstObserved:observedAt,lastObserved:observedAt,lastConfirmed:observedAt,effectiveDate:null,evidence:structuredClone(observation.source),reference:structuredClone(reference),supersededBy:null};
 return {version:1,id,source:structuredClone(source),offerKey:key,current:entry.id,history:[entry],lastEvidence:{fingerprints:fingerprints(body,facts),interpretationVersion,sourceHash:observation.source.hash,reference:structuredClone(reference)},lastConfirmed:observedAt,lastAttempt:null,failures:0,nextRetryAt:null,state:'RETAINED',freshness:'UNCONFIRMED',events:[],recovery:null,shadow:true};
}
export const currentPrice=u=>u.history.find(h=>h.id===u.current);
export {refreshPolicy,dueState,planRefresh} from './planning.mjs';
