// Pure refresh scheduling. Safe to import in API/worker; no interpreter or transport side effects.
import {createHash} from 'node:crypto';
export const stable=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
export const digest=x=>createHash('sha256').update(typeof x==='string'?x:stable(x)).digest('hex');
export function refreshPolicy({priceStrategy,evidence=true,complexScope=false,cost='LOW',changeCount=0}={}){
 if(!evidence||priceStrategy==='MANUAL_ONLY')return {kind:'NONE',days:null,reason:'NO_ROUTINE_PROVIDER_PRICE_REQUIREMENT'};
 if(priceStrategy==='USER_PRICE_PREFERRED')return {kind:complexScope?'CHANGE_DRIVEN':'LOW_FREQUENCY',days:complexScope?null:90,reason:'USER_PRICE_REMAINS_PREFERRED'};
 if(priceStrategy!=='SUGGESTED_PRICE')return {kind:'NONE',days:null,reason:'UNREVIEWED_PRICE_STRATEGY'};
 return cost==='HIGH'||complexScope?{kind:'MONTHLY',days:30,reason:'COST_OR_SCOPE_LIMIT'}:{kind:'WEEKLY',days:7,reason:changeCount?'RECENT_CHANGE_MONITORING':'KNOWN_PROVIDER_SUGGESTION'};
}
export function dueState(unit,policy,now,{changed=false}={}){const at=Date.parse(now);if(!Number.isFinite(at))throw Error('VALID_CLOCK_REQUIRED');if(policy.kind==='NONE'||unit.superseded)return {status:'NO_REFRESH_REQUIRED',freshness:'UNCONFIRMED'};if(unit.source.requiresConfigurator||unit.source.requiresRendering||!unit.source.authoritative)return {status:'NO_REFRESH_REQUIRED',freshness:'BLOCKED',reason:'CAPABILITY_OR_AUTHORITY_BLOCKED'};if(unit.nextRetryAt&&at<Date.parse(unit.nextRetryAt))return {status:'NOT_DUE',freshness:'UNCONFIRMED',reason:'FAILURE_BACKOFF'};if(policy.kind==='CHANGE_DRIVEN'&&!changed)return {status:'NOT_DUE',freshness:unit.lastConfirmed?'STALE':'UNCONFIRMED',reason:'WAIT_FOR_CHANGE_SIGNAL'};const age=(at-Date.parse(unit.lastConfirmed))/86400000,due=!unit.lastConfirmed||!Number.isFinite(age)||changed||age>=policy.days;return {status:due?'DUE':'NOT_DUE',freshness:unit.failures?'UNCONFIRMED':!unit.lastConfirmed?'UNCONFIRMED':due?(age>policy.days*2?'STALE':'DUE'):'FRESH'};}
export function planRefresh(units,catalog,now){const rows=units.map(u=>{const c=catalog.find(c=>c.service===u.source.service),policy=refreshPolicy({priceStrategy:c?.priceStrategy,complexScope:Object.keys(u.source.scope??{}).length>0,cost:u.source.geoRequired?'HIGH':'LOW'});return {unitId:u.id,service:u.source.service,sourceId:u.source.id,policy,...dueState(u,policy,now),requestKey:digest([u.source.service,u.source.provider,u.source.scopeKey,u.source.lastSuccessfulUrl,u.source.geoRequired])};});
 const queue=[...new Set(rows.filter(r=>r.status==='DUE').map(r=>r.requestKey))].map(key=>{const rs=rows.filter(r=>r.status==='DUE'&&r.requestKey===key),u=units.find(u=>u.id===rs[0].unitId);return {id:key,unitIds:rs.map(r=>r.unitId),source:structuredClone(u.source),route:'DIRECT',url:u.source.lastSuccessfulUrl,discovery:false,decodo:false};});
 const eligible=new Set(rows.filter(r=>r.policy.kind!=='NONE'&&r.freshness!=='BLOCKED').map(r=>r.service)),due=new Set(rows.filter(r=>r.status==='DUE').map(r=>r.service));return {version:1,now,rows,queue,metrics:{catalog:catalog.length,refreshEligibleServices:eligible.size,dueServices:due.size,notDueServices:[...eligible].filter(s=>!due.has(s)).length,noRefreshRequiredServices:catalog.length-eligible.size,refreshUnits:units.length,uniqueSources:new Set(units.map(u=>u.source.id)).size,uniqueSourcesDue:queue.length,deduplicatedDirectRequests:queue.length,expectedDiscovery:0,expectedDecodo:0},executionEnabled:false};}
