// Offline recognition only; never execute a provider request or promote navigation to evidence.
import {sourceLinks} from '../live/source-frontier-links.mjs';import {normalizeFrontierUrl} from '../live/source-frontier.mjs';import {navigationRank} from '../live/provider-navigation.mjs';
const text=x=>x.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ');
const dimensions={location:/choose (?:a |your )?(?:location|club|gym)|select (?:a |your )?(?:location|club|gym)|find a (?:club|gym)|velg (?:ditt )?senter|välj (?:ditt )?(?:gym|center|klubb)|valj (?:gym|klubb)|choisir (?:un |votre )?club|kies (?:een |je )?club|wähle.{0,20}studio|selecion.{0,20}(?:clube|ginasio)|elige.{0,20}(?:club|gimnasio)/iu,city:/choose (?:a |your )?city|select (?:a |your )?city|välj stad|velg by/iu,activity:/choose.{0,15}activit|select.{0,15}activit|välj.{0,15}träning|velg.{0,15}trening/iu,plan:/choose (?:a |your )?(?:plan|membership)|select (?:a |your )?(?:plan|membership)|velg medlemskap|välj medlemskap|kies.{0,12}abonnement/iu};
export function recognizeConfigurator({body,sourceHash,url,target,monetaryCandidates=0}){
 if(typeof body!=='string'||Buffer.byteLength(body)>8000000)throw Error('JOURNEY_SOURCE_BOUND');
 const visible=text(body),commercial=/membership|subscription|pricing|medlemskap|abonnement|abonnem|lidmaatschap|mitglied|gym|fitness|club/iu.test(visible),signals=[];
 for(const [dimension,re]of Object.entries(dimensions)){const m=visible.match(re);if(m)signals.push({dimension,wording:m[0],locator:{coordinate:'NORMALIZED_VISIBLE_TEXT',offset:m.index,length:m[0].length},sourceHash,priceEffect:'UNKNOWN'});}
 const controls=[...body.matchAll(/<(select|form)\b[^>]*>[\s\S]*?<\/\1>/gi)].map(m=>({tag:m[1].toLowerCase(),raw:m[0].slice(0,1600),locator:{coordinate:'UTF16_CODE_UNITS',offset:m.index,length:m[0].length},sourceHash}));
 const links=sourceLinks(body,{maxBytes:8000000,maxLinks:10000}).links.flatMap(l=>{const n=normalizeFrontierUrl(l.url,url);return n.url?[{...l,url:n.url,reviewed:target.authorities.some(a=>a.hostname===new URL(n.url).hostname),sourceHash,discoveryOnly:true}]:[];});
 const stateReferences=[...body.matchAll(/(?:cityId|locationId|clubId|gymId|activityId|accessType|membershipType|planId|productId)/g)].map(m=>({key:m[0],locator:{coordinate:'UTF16_CODE_UNITS',offset:m.index,length:m[0].length},sourceHash,meaning:'UNBOUND_STATE_KEY_NOT_REQUEST_SCHEMA'}));
 const literalEndpoints=[...body.matchAll(/[\"']((?:https:\/\/[^\"'<>\s]+|\/(?:api|graphql)\/[^\"'<>\s]*|\/graphql))[\"']/g)].flatMap(m=>{const n=normalizeFrontierUrl(m[1],url);return n.url&&/price|pricing|membership|member|subscription|club|location|plan|product|offer|graphql/i.test(n.url)?[{url:n.url,label:'literal endpoint reference',reviewed:target.authorities.some(a=>a.hostname===new URL(n.url).hostname),reference:{coordinate:'UTF16_CODE_UNITS',offset:m.index,length:m[0].length},sourceHash,discoveryOnly:true,readOnlyEstablished:false}]:[];});
 const entries=links.filter(l=>l.reviewed&&(navigationRank(target,l)<=15||/join|membership|medlems|abonn|signup|checkout/i.test(l.url+' '+l.label))),endpoints=[...links,...literalEndpoints].filter(l=>l.reviewed&&/\/api\/|graphql|\.json(?:\?|$)|endpoint/i.test(l.url));
 const selectedDimension=signals.some(s=>s.dimension!=='plan'),config=commercial&&selectedDimension,checkout=/\/checkout(?:\/|$)/i.test(new URL(url).pathname),client=/enable javascript|javascript (?:is )?required/i.test(visible)&&/<script\b/i.test(body);
 const classification=config?'CONFIGURATOR':checkout?'CHECKOUT_PRICING':monetaryCandidates>0?'STATIC_PRICING':entries.length?'NAVIGATION_TO_STATIC_PRICING':client?'CLIENT_RENDERED_PRICING':'UNKNOWN';
 const futurePath=config?(endpoints.length?'DIRECT_PROVIDER_ENDPOINT':controls.some(c=>c.tag==='form'&&!/method\s*=\s*["']?post/i.test(c.raw))||entries.length?'DIRECT_FORM_PATH':'UNKNOWN'):client?'UNKNOWN':'STATIC_HTML';
 return {classification,signals,controls,stateReferences,entryPoints:entries,endpoints,futurePath,clientRenderingSignal:client,browserRequired:false,scopePriceProved:false,priceExistsProved:false,monetarySignalsPresent:monetaryCandidates>0,executable:false,executionBlocker:config?'NO_REVIEWED_REQUEST_AND_SELECTION_BINDING':null,source:{url,hash:sourceHash},evidenceStatus:'JOURNEY_METADATA_ONLY'};
}
export const boundedConfiguratorStrategy=Object.freeze({status:'DESIGN_ONLY_NOT_LIVE_ENABLED',entryReads:'Existing navigation allowance',maxConfigurations:1,maxSelectionRequests:3,maxVariationConfigurations:1,variationRequires:'Provider evidence of variation and separate explicit remaining allowance',planPricesPerResponse:'Preserve all returned plan observations within existing input byte/node bounds; no per-plan traversal',rules:['Identify dimensions and provider-supplied allowed values first','Use target market only when provider establishes selectable value','Use meaningful provider default, else stable provider-listed valid non-sensitive configuration','Never fabricate IDs, query parameters, endpoints or bodies','No authentication, payment, purchase, agreement or irreversible form submission','Only separately reviewed read-only requests; POST/GraphQL must prove read-only operation','Stop when unknown transition, access control, sensitive requirement or byte/request limit appears','Preserve exact configuration as scope; never infer nationwide price','Browser is not implied by configurator'],newBudgetActivated:false});
