// Eligibility objective for the existing adaptive engine. Provider facts only; no transport.
import {inspectCatalogCapabilities,capabilityTextAllowed} from './catalog-capabilities.mjs';
import {decodeEntities} from '../live/source-frontier-links.mjs';
export const eligibilityStates=Object.freeze(['LOGIN_MANAGE_ESTABLISHED','LOGIN_ONLY_ESTABLISHED','MANAGE_ONLY_ESTABLISHED','LOGIN_MANAGE_UNRESOLVED','LOGIN_MANAGE_NOT_SUPPORTED','NOT_RELEVANT_CONSUMER_SUBSCRIPTION','INSUFFICIENT_EVIDENCE']);
export const catalogObjective=t=>t.researchObjective==='CATALOG_ONLY';
const dangerous=/(?:logout|signout|delete|remove-account|unsubscribe|reset-password|password-reset|oauth|authorize|callback|employee|staff|partner|affiliate|developer|business|enterprise)/iu;
const useful=/(?:^|[.\/_\s-])(?:log[ -]?in|sign[ -]?in|account|members?|membership|subscriptions?|billing|payment|support|help|faq|manage|management|cancel|cancellation|pause|freeze|renew|konto|kundeservice|medlemskap|medlemsbetingelser|abonnement|abonnemang|connexion|compte|cuenta|abonelik)(?:$|[.\/_\s-])|ログイン|マイページ|契約|구독|로그인|เข้าสู่ระบบ/iu;
export function capabilityDestination(url,label=''){let u;try{u=new URL(url);}catch{return {eligible:false,value:0};}const text=u.pathname+' '+label;if(/(?:^|\/)(?:show|watch|episodes?|books|features|gifts?|checkout|buy-checkout|amz-books)(?:\/|$)|betrieblich|corporate|business/iu.test(u.pathname))return {eligible:false,value:0};if(/(?:^|\/)(?:login|signin|servicelogin)(?:\/|$)/i.test(u.pathname))return {eligible:false,value:0,reason:'AUTHENTICATION_DESTINATION_POLICY'};if(/(?:action|do)=(?:logout|delete|cancel)/i.test(u.search)||/\.(?:js|css|png|jpg|pdf|zip)$/i.test(u.pathname)||dangerous.test(text)||/privacy|cookie|careers|investor|press/.test(text))return {eligible:false,value:0};return {eligible:true,value:useful.test(u.hostname+' '+text)?8:u.pathname==='/'?2:1};}
// A FAQ heading is not a claim; an explicit answer in the same bounded paragraph may be.
export function managementAssertion(text){const q=text.search(/[?？]/);if(q<0)return capabilityTextAllowed(text)?text:null;if(q>200)return null;const answer=text.slice(q+1).trim();return answer&&capabilityTextAllowed(answer)&&/^(?:you can|it means|to |simply |just |yes[, .]|sie können|du kannst|vous pouvez|du kan|se puede)/iu.test(answer)?answer:null;}
export function inspectLoginManage(input){
 const p=inspectCatalogCapabilities(input),scope={market:input.market??null,channel:input.channel??'PROVIDER_WEB',provider:input.provider??null};
 if(input.authorityEstablished&&p.reason!=='UNBOUND_PROVIDER_SOURCE'){
 const visible=input.body.replace(/<!--[\s\S]*?-->|<(script|style)\b[^>]*>[\s\S]*?<\/\1\s*>/gi,m=>' '.repeat(m.length));
 const action=/(?:cancel|pause|renew|upgrade|downgrade|change|update|manage|view) (?:your |my |the )?(?:subscription|membership|plan|billing|payment method)|(?:kündigen|verwalten|ändern).{0,30}(?:Abonnement|Mitgliedschaft|Zahlungsmethode)|(?:Abonnement|Mitgliedschaft).{0,30}(?:kündigen|verwalten)|(?:si opp|endre|administrere|avslutte).{0,30}(?:abonnement|medlemskap|betalingsmåte)|(?:avsluta|ändra|hantera).{0,30}(?:abonnemang|medlemskap|betalningsmetod)|(?:zrušit|spravovat|změnit).{0,25}(?:předplatné|členství)|(?:abonelik|üyelik).{0,25}(?:iptal|yönet)|(?:구독|멤버십).{0,15}(?:취소|관리)|(?:契約|サブスクリプション).{0,15}(?:解約|管理)|(?:ยกเลิก|จัดการ).{0,20}(?:สมาชิก|การสมัคร)/iu;
 const web=/\b(?:account|website|web browser|online account|konto|min side|mina sidor|compte|cuenta|conta|účtu|hesabınız)\b|マイページ|アカウント|계정|บัญชี/iu;
 for(const m of visible.matchAll(/<(p|li)\b[^>]*>([\s\S]*?)<\/\1\s*>/gi)){const text=decodeEntities(m[2].replace(/<[^>]*>/g,' ')).replace(/\s+/g,' ').trim();const assertion=managementAssertion(text);const explicitSettings=assertion&&/\b(?:subscription|membership)\b/iu.test(assertion)&&/\bcancel (?:via|through|from|in) (?:your |my |the )?account settings\b/iu.test(assertion);if(text.length<=650&&assertion&&(action.test(assertion)||explicitSettings)&&web.test(assertion))p.management.push({sourceHash:input.sourceHash,url:input.url,locator:{offset:m.index,length:m[0].length,coordinate:'UTF16_CODE_UNITS'},providerText:text,meaning:'EXPLICIT_WEB_ACCOUNT_SUBSCRIPTION_ACTION'});}
 }
 // A generic login label adjacent to a business/employee portal cannot establish consumer login.
 const safeProof=x=>{if(/\b(?:nicht|keine?|ingen|ikke|inte|nej|non|pas|no se puede|não|nemůžete|yalnızca)\b|できません|불가|ไม่สามารถ/iu.test(x.providerText??''))return false;const offset=x.locator?.offset;if(!Number.isInteger(offset))return false;const around=input.body.slice(Math.max(0,offset-100),offset+(x.locator.length??100)+100);return !/employee|staff portal|partner portal|affiliate|developer|business login|enterprise login|app only|mobile app only/iu.test(around);};
 return {...p,login:p.login.filter(safeProof),management:p.management.filter(safeProof),scope,reference:input.reference??null,authorityEstablished:input.authorityEstablished===true,priceRequired:false};
}
const unsafeManagement=text=>/\b(?:app|apps|telephone|phone|call|email|contact|reach out|they will help|cannot|can't|unable|nicht|ikke|inte)\b|できません|불가|ไม่สามารถ/iu.test(text);
export function eligibilityState(service,proofs=[]){
 const valid=proofs.filter(p=>p.service===service&&p.authorityEstablished&&p.sourceHash&&p.reference),groups=new Map();for(const p of valid){const key=JSON.stringify(p.scope);if(!groups.has(key))groups.set(key,{scope:p.scope,login:[],management:[]});const g=groups.get(key);g.login.push(...p.login);g.management.push(...p.management.filter(x=>!unsafeManagement(x.providerText??'')));}
 const scopes=[...groups.values()],both=scopes.filter(g=>g.login.length&&g.management.length),login=scopes.some(g=>g.login.length),manage=scopes.some(g=>g.management.length);
 return {service,status:both.length?'LOGIN_MANAGE_ESTABLISHED':login&& !manage?'LOGIN_ONLY_ESTABLISHED':manage&&!login?'MANAGE_ONLY_ESTABLISHED':'LOGIN_MANAGE_UNRESOLVED',scopes,establishedScopes:both.map(g=>g.scope),scopeConflict:login&&manage&&!both.length,negativeEvidence:[],priceRequired:false,productionPromoted:false};
}
export function mergeTargetCapabilities(t,proof){t.catalogCapabilityProofs??=[];if(proof&&!t.catalogCapabilityProofs.some(p=>p.sourceHash===proof.sourceHash&&JSON.stringify(p.scope)===JSON.stringify(proof.scope)))t.catalogCapabilityProofs.push(proof);t.catalogEligibility=eligibilityState(t.service,t.catalogCapabilityProofs);t.loginManageEstablished=t.catalogEligibility.status==='LOGIN_MANAGE_ESTABLISHED';t.gaps=t.loginManageEstablished?[]:t.catalogEligibility.status==='LOGIN_ONLY_ESTABLISHED'?['WEB_MANAGEMENT']:t.catalogEligibility.status==='MANAGE_ONLY_ESTABLISHED'?['LOGIN']:['LOGIN','WEB_MANAGEMENT'];return t.catalogEligibility;}
