import '../offline-replay/offline-guard.mjs';
import test,{after} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {projectPriceEvidenceNeeds,readPriceEvidenceNeeds,mergePriceEvidenceNeeds,researchablePriceNeeds,priceNeedsBounds} from './price-evidence-needs.mjs';
import {researchKnowledge,createResearchMemory} from '../live/research-memory.mjs';
import {planResearch,contextualQuery} from '../live/research-planner.mjs';
import {initializeAdaptiveState,assessAdaptiveService,runAdaptiveCampaign} from '../inventory/adaptive-campaign.mjs';
import {reconstructOfferIntelligence} from './offer-intelligence.mjs';
const cwd=process.cwd(),root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'price-needs-')));process.chdir(root);after(()=>{process.chdir(cwd);fs.rmSync(root,{recursive:true});});
const sha=x=>createHash('sha256').update(x).digest('hex');fs.writeFileSync('memory.json','[]');const reference={path:'memory.json',hash:sha('[]')};
const known='https://provider.example/offer';
const target=(market='NO')=>({id:'fixture-price-'+market,service:'fixture',serviceName:'Fixture',market,researchObjective:'SERVICE_COVERAGE',smartResearch:{version:2},authorities:[{hostname:'provider.example',provider:'Fixture',checkedAt:'2026-01-01',sourceType:'OFFICIAL_PROVIDER'}],urls:[known],leads:[{url:known,title:'Membership plans',rank:0}],reads:[],queries:[],decisions:[],verified:[],blockedOrigins:[],capabilities:{direct:true,tavily:true,decodo:false,browser:false,groq:false}});
const keys=['service','provenance','plan','amount','currency','billingInterval','recurringSemantics','ordinaryPriceRole','offerOwnership','offerPresentation','market'];
function observation({plan='Solo',cadence='P1M',market='NO',missing=['offerPresentation','market'],blockers=['EMBEDDED_OFFER_ACTIVATION_UNRESOLVED'],...extra}={}){return {service:'fixture',plan,amount:25,currency:'NOK',billingInterval:{normalized:cadence},commercialRole:'RECURRING_MONTHLY',market:missing.includes('market')?null:market,marketApplicability:{requestedMarket:market},scope:{},source:{kind:'ORIGINAL_PROVIDER',url:known,hash:'a'.repeat(64),path:'$/script/price'},fields:Object.fromEntries(keys.map(k=>[k,{status:missing.includes(k)?'UNKNOWN':'ESTABLISHED'}])),blockers,...extra};}
function withNeeds(t=target(),obs=[observation()]){t.priceEvidenceNeeds=projectPriceEvidenceNeeds(t,obs);return t;}
function assess(t,limits={}){const state=initializeAdaptiveState({targets:[t],conditionalFollowupTargets:[]},{limits});return {state,result:assessAdaptiveService(state,t.service)};}
function exhausted(t=withNeeds(),searches=0){t.researchMemory=createResearchMemory({...t,reads:[{requestedUrl:known,outcome:'OK'}],queries:Array.from({length:searches},(_,i)=>({query:'prior '+i}))},reference);return t;}
const missing=t=>t.priceEvidenceNeeds.claims.flatMap(c=>c.missing);

test('presentation and market gaps preserve established amount/cadence and source locator',()=>{const t=withNeeds(),c=t.priceEvidenceNeeds.claims[0];assert.deepEqual(c.missing.map(m=>m.assertion).sort(),['market','offerPresentation']);assert(c.missing.every(m=>m.disposition==='RESEARCHABLE'));assert(c.established.some(f=>f.assertion==='amount'&&f.value===25));assert.equal(c.identity.cadence,'P1M');assert.equal(t.priceEvidenceNeeds.sources[0].references[0].sourceHash,'a'.repeat(64));assert.equal(t.priceEvidenceNeeds.sources[0].references[0].domLocator,'$/script/price');});
test('presentation established leaves only market need',()=>assert.deepEqual(missing(withNeeds(target(),[observation({missing:['market'],blockers:[]})])).map(m=>m.assertion),['market']));
for(const [field,expected]of [['service','HUMAN_REVIEW'],['provenance','POLICY']])test(field+' failure cannot become a research workaround',()=>{const t=withNeeds(target(),[observation({missing:[field,'offerPresentation']})]);assert(missing(t).every(m=>m.disposition===expected));assert.equal(assess(t).result.next,null);});
test('unsupported runtime relationship remains interpretation and does not loop',()=>{const t=target();t.demonstratedRendering=true;withNeeds(t);assert.equal(researchablePriceNeeds(t).length,0);for(let i=0;i<3;i++)assert.equal(assess(t).result.next,null);});
test('same-scope conflict cannot cherry-pick or research around conflict',()=>{const t=withNeeds(target(),[observation({blockers:['SAME_SCOPE_INCOMPATIBLE_AMOUNTS']})]);assert(missing(t).every(m=>m.disposition==='CONFLICT'));assert.equal(assess(t).result.next,null);});
test('independent offers do not union missing assertions',()=>{const t=withNeeds(target(),[observation({plan:'Solo',missing:['offerPresentation'],blockers:[]}),observation({plan:'Duo',cadence:'P1Y',missing:['market'],blockers:[]})]);assert.equal(t.priceEvidenceNeeds.claims.length,2);assert.deepEqual(t.priceEvidenceNeeds.claims.find(c=>c.identity.plan==='Solo').missing.map(m=>m.assertion),['offerPresentation']);assert.equal(t.priceEvidenceNeeds.claims.find(c=>c.identity.plan==='Duo').identity.cadence,'P1Y');assert.equal(researchKnowledge(t).priceEvidenceNeeds.claims.length,2);});
test('markets never share identity or observations',()=>{const no=withNeeds(),se=withNeeds(target('SE'),[observation({market:'SE'})]);assert.notEqual(no.priceEvidenceNeeds.claims[0].claimKey,se.priceEvidenceNeeds.claims[0].claimKey);assert.equal(projectPriceEvidenceNeeds(target('SE'),[observation()]).claims.length,0);});
test('unknown offer remains target-level without invented cadence/plan',()=>{const t=withNeeds(target(),[observation({plan:null})]);assert.equal(t.priceEvidenceNeeds.claims[0].identity.plan,null);assert.equal(t.priceEvidenceNeeds.claims[0].identity.cadence,null);assert.equal(researchablePriceNeeds(t).length,0);});
test('canonical ordering and duplicate observation do not change digest',()=>{const a=observation(),b=observation({plan:'Duo'});const p=projectPriceEvidenceNeeds(target(),[a,b]),q=projectPriceEvidenceNeeds(target(),[b,a,a]);assert.deepEqual(p,q);});
test('evidence changes digest but not semantic claim/gap identity',()=>{const a=withNeeds(),o=observation();o.source.hash='b'.repeat(64);o.source.path='$/new';const b=withNeeds(target(),[o]);assert.equal(a.priceEvidenceNeeds.claims[0].claimKey,b.priceEvidenceNeeds.claims[0].claimKey);assert.equal(missing(a)[0].gapKey,missing(b)[0].gapKey);assert.notEqual(a.priceEvidenceNeeds.evidenceDigest,b.priceEvidenceNeeds.evidenceDigest);assert.notEqual(assess(a).result.state,assess(b).result.state);});
test('observation timestamps do not change digest',()=>assert.deepEqual(projectPriceEvidenceNeeds(target(),[observation({acquiredAt:'yesterday'})]),projectPriceEvidenceNeeds(target(),[observation({acquiredAt:'today'})])));
test('unknown projection version and corrupted digest fail closed',()=>{const t=withNeeds();t.priceEvidenceNeeds.derivationVersion='FUTURE';assert.throws(()=>assess(t),/PRICE_NEEDS_SCHEMA/);t.priceEvidenceNeeds=projectPriceEvidenceNeeds(t,[observation()]);t.priceEvidenceNeeds.claims[0].missing=[];assert.throws(()=>readPriceEvidenceNeeds(t),/PRICE_NEEDS_DIGEST/);});
test('older checkpoint without projection preserves planning',()=>assert.equal(assess(target()).result.next.plan.route,'DIRECT'));
test('fresh actionable Direct preferred to discovery',()=>assert.equal(assess(withNeeds()).result.next.plan.route,'DIRECT'));
test('exhausted resource permits gap-specific bounded discovery, never duplicate Direct',()=>{const t=exhausted();t.providerInterpretations=[{blockers:['OFFER_OWNERSHIP_UNRESOLVED']}];const r=assess(t).result;assert.equal(r.next.plan.route,'DISCOVERY');assert.match(r.next.plan.query,/purchase/);assert.equal(r.next.plan.candidates.length,0);assert.equal(r.stop,null);});
test('two exhausted searches stop without false budget exhaustion',()=>{const r=assess(exhausted(withNeeds(),2)).result;assert.equal(r.next,null);assert.equal(r.stop.reason,'DISCOVERY_EXHAUSTED');assert.notEqual(r.stop.kind,'BUDGET_LIMITED');});
for(const cap of ['direct','tavily'])test(cap+' hard block preserved',()=>{const t=cap==='direct'?withNeeds():exhausted();t.capabilities[cap]=false;const r=assess(t).result;if(cap==='direct')assert.notEqual(r.next?.plan.route,'DIRECT');else {assert.equal(r.next,null);assert.equal(r.stop.reason,'CAPABILITY_DISABLED_TAVILY');}});
test('gap grants neither Browser nor Decodo and uses no budget category',()=>{const {state,result}=assess(exhausted());assert.equal(result.next.plan.route,'DISCOVERY');assert.equal(result.next.plan.browserEnabled,false);assert.deepEqual(state.services.fixture.used,{reads:0,searches:0,acquisitions:0,retainedReviews:0});assert.equal(state.bounds.searches,2);});
test('literal search budget zero still blocks',()=>assert.equal(assess(exhausted(),{searches:0}).result.stop.reason,'BUDGET_EXHAUSTED'));
test('no allowance per gap, one resource action identity for multiple needs',()=>{const a=assess(withNeeds()).result.next,b=assess(withNeeds(target(),[observation(),observation({plan:'Duo'})])).result.next;assert.equal(a.actionIdentity,b.actionIdentity);});
test('provider access policy remains stop',()=>{const t=exhausted();t.blockedOrigins=['https://provider.example'];assert.equal(assess(t).result.stop.reason,'PROVIDER_ACCESS_POLICY_STOP');});
test('new interpretation replaces same-source needs; verified observation removes needs',()=>{const t=withNeeds();mergePriceEvidenceNeeds(t,projectPriceEvidenceNeeds(t,[observation({missing:[],blockers:[],trustworthy:true})]));assert.equal(missing(t).length,0);});
test('unchanged evidence merge is idempotent, no reassessment loop',()=>{const t=withNeeds(),a=assess(t).result.state;mergePriceEvidenceNeeds(t,structuredClone(t.priceEvidenceNeeds));assert.equal(assess(t).result.state,a);});
test('source provenance and arbitrary Human Review labels never grant evidence',()=>{const a=observation({humanLead:true});a.fields.service.status='UNKNOWN';assert(missing(withNeeds(target(),[a])).every(m=>m.disposition==='HUMAN_REVIEW'));});
test('catalog-only localized observations never synthesize pricing scope',()=>{const t={...target(),id:'fixture-catalog',market:null,researchObjective:'CATALOG_ONLY',gaps:['WEB_MANAGEMENT']};assert.equal(projectPriceEvidenceNeeds(t,[observation()]),null);mergePriceEvidenceNeeds(t,withNeeds().priceEvidenceNeeds);assert.equal(t.priceEvidenceNeeds,undefined);const state=initializeAdaptiveState({targets:[t],conditionalFollowupTargets:[]});assert.deepEqual(Object.keys(state.targets),['fixture-catalog']);assert.equal(researchKnowledge(t).priceEvidenceNeeds,null);});
test('nonadmitted ID does not acquire structured pricing semantics',()=>assert.equal(projectPriceEvidenceNeeds({...target(),id:'arbitrary'},[observation()]),null));
for(const confidence of ['HIGH','MEDIUM'])test(confidence+' sufficiency outranks remaining diagnostic gaps',()=>{const t=withNeeds(target(),[observation(),observation({plan:'Duo'})]);t.retainedPriceReview={sourceBound:true,amount:'12',confidence,market:'NO'};const r=assess(t).result;assert.equal(r.next,null);assert.equal(r.stop.reason,confidence+'_SUFFICIENT');});
test('sufficient one claim does not require all-SKU research',()=>{const t=withNeeds();t.retainedPriceReview={sourceBound:true,amount:'12',confidence:'MEDIUM',market:'NO'};const other=withNeeds(target('SE'),[observation({market:'SE',plan:'Other'})]);const state=initializeAdaptiveState({targets:[t,other],conditionalFollowupTargets:[]});assert.equal(assessAdaptiveService(state,'fixture').next,null);});
test('excluded trial/credit/tax observations never become needs',()=>{for(const role of ['TRIAL','CREDIT','TAX','INTRO_PROMOTION'])assert.equal(projectPriceEvidenceNeeds(target(),[observation({commercialRole:role})]).claims.length,0);assert.equal(projectPriceEvidenceNeeds(target(),[observation({amount:0})]).claims.length,0);});
test('observation bound produces explicit incomplete planning state',()=>assert.equal(projectPriceEvidenceNeeds(target(),Array(priceNeedsBounds.observations+1).fill(observation())).coverage.complete,false));
test('checkpoint roundtrip preserves gaps, attempts, usage and stable signatures',()=>{const t=exhausted();t.reads=[{requestedUrl:'https://provider.example/old',outcome:'OK'}];const a=assess(t),b=JSON.parse(JSON.stringify(a.state));assert.deepEqual(assessAdaptiveService(b,'fixture'),a.result);assert.equal(b.services.fixture.used.reads,1);assert.equal(b.targets[t.id].researchMemory.attempts.length,1);});
test('offline adaptive checkpoint resume retains pending live action without dispatch',async()=>{let calls=0;const t=exhausted(),options={directory:root+'/adaptive',manifest:{targets:[t],conditionalFollowupTargets:[]},stopBeforeNetwork:true,createAdapters:async()=>{calls++;throw Error('NO_NETWORK');}};const a=await runAdaptiveCampaign(options),b=await runAdaptiveCampaign(options);assert.equal(calls,0);assert.equal(a.services.fixture.pending.plan.route,'DISCOVERY');assert.deepEqual(b.services.fixture.used,a.services.fixture.used);assert.equal(b.targets[t.id].priceEvidenceNeeds.evidenceDigest,t.priceEvidenceNeeds.evidenceDigest);});
test('actual verifier complete first-party offer yields no needs without a second source',()=>{const body='<section><h2>Norway</h2><article id="S"><h3>Solo</h3><p>NOK 25/month</p><form action="/checkout"><input type="hidden" name="sku" value="S"><button>Subscribe</button></form></article><p>Plans auto-renew monthly unless cancelled.</p></section><script>window.catalog = {"name":"Solo","id":"S","price":{"amount":"25","currencyCode":"NOK","period":"month"}};</script>',hash=sha(body);const result=reconstructOfferIntelligence({body,sourceUrl:known,context:{bodyHash:hash,authority:true,service:'fixture',market:'NO',sourceOccurrences:[{id:'fixture',url:known}]},receipt:{intact:true,bodyHash:hash,service:'fixture',serviceEstablished:true,bindingEstablished:true}});const trustworthy=result.offers.filter(o=>o.trustworthy);assert(trustworthy.length);assert.equal(missing(withNeeds(target(),trustworthy)).length,0);});
test('retained intact interpretation is consumed before any gap-directed acquisition',()=>{const t=withNeeds(),doc={summary:{service:t.service,market:t.market,hash:'c'.repeat(64)},receipt:{intact:true,serviceEstablished:true},observations:[]},file=root+'/retained.json';fs.writeFileSync(file,JSON.stringify(doc));t.adaptiveExecution=true;t.researchMemory=createResearchMemory({...t,reads:[{requestedUrl:known,outcome:'OK',bodyHash:'c'.repeat(64)}]},{path:file,hash:sha(JSON.stringify(doc))});assert.equal(assess(t).result.next?.plan.route,'REUSE_RETAINED',JSON.stringify(assess(t).result));});
test('live controller projection persists across reserved-action interruption and resume without duplicate read',async()=>{
 const t=target(),calls=[],projection=projectPriceEvidenceNeeds(t,[observation()]);
 const options={directory:root+'/live-fixture',manifest:{targets:[t],conditionalFollowupTargets:[]},maxActions:1,createAdapters:async()=>({read:async({url})=>{calls.push(url);return {url,outcome:'OK',text:'Fixture'};},search:async()=>({results:[]}),classify:async()=>({eligible:true}),consumeProvider:async()=>({verified:[],monetary:1,blockers:['OFFER_OWNERSHIP_UNRESOLVED'],priceEvidenceNeeds:projection})})};
 await assert.rejects(runAdaptiveCampaign({...options,onTransition:event=>{if(event==='NATIVE_RESULT_PERSISTED')throw Error('INTERRUPTION');}}),/INTERRUPTION/);
 const state=await runAdaptiveCampaign(options);assert.equal(calls.length,1);assert.equal(state.targets[t.id].priceEvidenceNeeds.evidenceDigest,projection.evidenceDigest);assert.equal(state.services.fixture.used.reads,1);assert.equal(state.services.fixture.used.searches,1);assert.equal(state.pending,null);
});
test('missing cadence without grounded interval is interpretation, not generic rediscovery',()=>{const t=withNeeds(target(),[observation({cadence:null,missing:['billingInterval'],blockers:['EXACT_RECURRING_INTERVAL_UNRESOLVED']})]);assert.equal(researchablePriceNeeds(t).length,0);assert.equal(assess(t).result.next,null);});
test('trial/renewal or principal-role ambiguity is interpretation',()=>{const t=withNeeds(target(),[observation({missing:['ordinaryPriceRole'],blockers:['NOT_PROVEN_ORDINARY_RECURRING']})]);assert(missing(t).every(m=>m.disposition==='INTERPRETATION'));assert.equal(assess(t).result.next,null);});
test('qualifier identity keeps distinct eligibility/commitment claims separate',()=>{const a=observation({scope:{eligibility:{value:'student',sourceHash:'old'}}}),b=observation({scope:{eligibility:{value:'standard',sourceHash:'new'}}});assert.equal(projectPriceEvidenceNeeds(target(),[a,b]).claims.length,2);const c=structuredClone(a);c.scope.eligibility.sourceHash='changed';assert.equal(projectPriceEvidenceNeeds(target(),[a]).claims[0].claimKey,projectPriceEvidenceNeeds(target(),[c]).claims[0].claimKey);});
test('bounded needs do not overwrite search history or renew per-service budgets',()=>{const t=exhausted(withNeeds(),2);t.queries=[{query:'current'}];const a=assess(t);assert.equal(a.state.services.fixture.used.searches,1);assert.equal(a.result.stop.reason,'DISCOVERY_EXHAUSTED');assert.equal(t.researchMemory.attempts.length,3);});
test('new projected interpretation changes assessment signature from legacy absence',()=>{const t=target(),a=assess(t).result.state;withNeeds(t);assert.notEqual(assess(t).result.state,a);assert.equal(assess(t).result.state,assess(structuredClone(t)).result.state);});
test('explicit market need changes bounded query intent without proxy permission',()=>{const t=withNeeds(target(),[observation({missing:['market'],blockers:[]})]);assert.match(contextualQuery(t),/country availability/);assert.equal(assess(exhausted(t)).result.next.plan.route,'DISCOVERY');assert.equal(t.capabilities.decodo,false);});
test('tax/credit blocker excludes observation even if monetary role is unknown',()=>assert.equal(projectPriceEvidenceNeeds(target(),[observation({blockers:['NON_CHARGE_MONETARY_AMOUNT']})]).claims.length,0));
test('new market projection cannot be applied to another target',()=>assert.throws(()=>mergePriceEvidenceNeeds(target('SE'),withNeeds().priceEvidenceNeeds),/SCOPE/));

test('projection locators remain source coordinates, not storage filesystem references',async()=>{const {closure}=await import('../storage/references.mjs');const t=withNeeds(),file=root+'/projection.json';fs.writeFileSync(file,JSON.stringify(t.priceEvidenceNeeds));const result=closure(root,[{path:'projection.json',format:'JSON',classification:'PERMANENT_HISTORY'}]);assert.deepEqual(result.errors,[]);assert.equal(result.entries.length,1);});

function incomplete(t){const omitted=observation({plan:'x'.repeat(20000),source:{...observation().source,url:'https://provider.example/omitted'}});t.priceEvidenceNeeds=projectPriceEvidenceNeeds(t,[observation(),omitted]);assert.equal(t.priceEvidenceNeeds.coverage.complete,false);return t;}
test('incomplete projection retains actionable Direct needs and query intent',()=>{const t=incomplete(target());assert(researchablePriceNeeds(t).length);assert.equal(assess(t).result.next.plan.route,'DIRECT');assert.match(contextualQuery(t),/purchase/);});
test('incomplete projection preserves bounded discovery, history, and capability stops',()=>{const t=exhausted(incomplete(target()));assert.equal(assess(t).result.next.plan.route,'DISCOVERY');assert.equal(assess(exhausted(incomplete(target()),2)).result.stop.reason,'DISCOVERY_EXHAUSTED');t.capabilities.tavily=false;assert.equal(assess(t).result.stop.reason,'CAPABILITY_DISABLED_TAVILY');const direct=incomplete(target());direct.capabilities.direct=false;assert.notEqual(assess(direct).result.next?.plan.route,'DIRECT');});
test('incomplete evidence change reassesses without changing accounting or sufficiency',()=>{const t=incomplete(target()),before=assess(t);mergePriceEvidenceNeeds(t,projectPriceEvidenceNeeds(t,[observation({amount:26,source:{...observation().source,hash:'b'.repeat(64)}})]));const after=assess(t);assert.notEqual(after.result.state,before.result.state);assert.deepEqual(after.state.services.fixture.used,before.state.services.fixture.used);assert.equal(t.priceEvidenceNeeds.coverage.complete,false);for(const confidence of ['HIGH','MEDIUM']){t.retainedPriceReview={sourceBound:true,amount:'12',confidence};assert.equal(assess(t).result.stop.reason,confidence+'_SUFFICIENT');}});
test('incomplete coverage never bypasses represented authority, integrity, conflict or interpretation stops',()=>{for(const change of [{missing:['service']},{missing:['provenance']},{blockers:['SAME_SCOPE_INCOMPATIBLE_AMOUNTS']},{cadence:null,missing:['billingInterval']}]){const t=target();t.priceEvidenceNeeds=projectPriceEvidenceNeeds(t,[observation(change),observation({plan:'x'.repeat(20000),source:{...observation().source,url:'https://provider.example/omitted'}})]);assert.equal(t.priceEvidenceNeeds.coverage.complete,false);assert.equal(researchablePriceNeeds(t).length,0);assert.equal(assess(t).result.next,null);assert.notEqual(assess(t).result.stop.reason,'BUDGET_EXHAUSTED');}});
