import '../offline-replay/offline-guard.mjs';
import test from 'node:test';import assert from 'node:assert/strict';
import {projectPriceEvidenceNeeds as project,readPriceEvidenceNeeds as read,mergePriceEvidenceNeeds as merge,priceNeedsStop,researchablePriceNeeds,priceNeedsBounds} from './price-evidence-needs.mjs';
const t=(market='DE')=>({id:'fixture-price-'+market,service:'fixture',serviceName:'Fixture',market,researchObjective:'SERVICE_COVERAGE',authorities:[{hostname:'provider.example',provider:'Fixture',sourceType:'OFFICIAL_PROVIDER',checkedAt:'2026-01-01'}]});
const o=(i=0,s=0)=>({service:'fixture',market:'DE',plan:'Plan '+i,amount:10+i,currency:'EUR',commercialRole:'ORDINARY_RECURRING',billingInterval:{normalized:'P1M'},source:{kind:'ORIGINAL_PROVIDER',url:'https://provider.example/plans/'+s,hash:String(s).padStart(64,'a'),path:'$/offer/'+i},fields:Object.fromEntries(['service','provenance','plan','amount','currency','billingInterval'].map(k=>[k,{status:'ESTABLISHED'}])),blockers:[]});
const bytes=p=>Buffer.byteLength(JSON.stringify(p));
test('V2 persists claims once, evidence references deduplicate, ordering is deterministic',()=>{const a=o(),b=o(1);const p=project(t(),[a,b,a]);assert.equal(p.version,2);assert.equal(p.derivationVersion,'PRICE_EVIDENCE_NEEDS_V2');assert.equal(p.sources[0].claims,undefined);assert.equal(p.sources[0].references.length,2);assert.equal(p.claims.length,2);assert.deepEqual(p,project(t(),[b,a]));assert.deepEqual(read({...t(),priceEvidenceNeeds:JSON.parse(JSON.stringify(p))}),p);});
test('long locator payload is represented by digest, not duplicated evidence',()=>{const row=o();row.source.path='x'.repeat(350000);row.source.body='SECRET_BODY';row.raw='SECRET_OBSERVATION';const p=project(t(),[row]);assert(bytes(p)<10000);assert(!JSON.stringify(p).includes('SECRET'));assert(!JSON.stringify(p).includes('xxxxx'));assert(p.sources[0].references[0].domLocator.digest);});
test('currency cadence role and admitted market remain distinct',()=>{const a=o(),b={...o(),currency:'USD'},c={...o(),billingInterval:{normalized:'P1Y'}},d={...o(),commercialRole:'RECURRING_MONTHLY'};const p=project(t(),[a,b,c,d]);assert.equal(p.claims.length,4);assert.notEqual(project(t('NO'),[{...a,market:'NO'}]).claims[0].claimKey,p.claims[0].claimKey);assert.equal(project({...t(),id:'fixture-catalog',market:null,researchObjective:'CATALOG_ONLY'},[a]),null);});
test('claim bound explicitly remains unresolved and stable across repeated merges',()=>{const rows=Array.from({length:300},(_,i)=>o(i));const p=project(t(),rows);assert.equal(p.coverage.complete,false);assert.equal(p.coverage.omittedClaims,300);assert(p.coverage.omittedDigest);assert.deepEqual(p,project(t(),rows.reverse()));const target={...t(),verified:[{status:'V2_VERIFIED'}],requestCeiling:36,priceEvidenceNeeds:p};const coverage=structuredClone(p.coverage);assert.equal(priceNeedsStop(target),null);merge(target,project(t(),[o()]));assert.equal(target.priceEvidenceNeeds.claims.length,1);assert.equal(target.priceEvidenceNeeds.coverage.complete,false);assert.equal(target.priceEvidenceNeeds.coverage.omittedDigest,coverage.omittedDigest);const before=JSON.stringify(target);merge(target,project(t(),[o()]));assert.equal(JSON.stringify(target),before);assert.equal(target.requestCeiling,36);assert.deepEqual(target.verified,[{status:'V2_VERIFIED'}]);});
test('many duplicate observations are bounded and not presented as resolved',()=>{const p=project(t(),Array.from({length:3000},()=>o()));assert.equal(p.coverage.complete,false);assert.equal(p.coverage.reason,'OBSERVATION_BOUND');assert(bytes(p)<2000);assert.equal(priceNeedsStop({...t(),priceEvidenceNeeds:p}),null);});
test('source replacement removes only that source contribution; no verification mutation',()=>{const target=t();target.verified=[{id:'unchanged'}];merge(target,project(target,[o(0,0),o(1,1)]));merge(target,project(target,[o(2,0)]));assert.deepEqual(target.priceEvidenceNeeds.claims.map(c=>c.identity.plan).sort(),['Plan 1','Plan 2']);assert.deepEqual(target.verified,[{id:'unchanged'}]);});
test('measure synthetic small, multi-source, production-scale and adversarial workloads',()=>{for(const [name,sources,claims,padding]of [['small',1,3,0],['multi',7,32,0],['production-scale',7,32,12000],['adversarial',20,100,500]]){const rows=Array.from({length:sources},(_,s)=>Array.from({length:claims},(_,i)=>{const r=o(i,s);r.source.path+='x'.repeat(padding);return r;})).flat();const p=project(t(),rows);assert(bytes(p)<=priceNeedsBounds.bytes);const equivalentLegacy=bytes(legacy(rows));console.log(JSON.stringify({name,equivalentLegacyBytes:equivalentLegacy,compactBytes:bytes(p),sources:p.sources.length,claims:p.claims.length,needs:p.claims.reduce((n,c)=>n+c.missing.length,0),coverage:p.coverage}));if(name==='production-scale'){assert(equivalentLegacy>2097152);assert(p.coverage.complete);}}});
import {createHash} from 'node:crypto';
import {initializeAdaptiveState,assessAdaptiveService} from '../inventory/adaptive-campaign.mjs';
const stable=x=>JSON.stringify(x,(_,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
const digest=x=>createHash('sha256').update(stable(x)).digest('hex');
function legacy(rows){const p=project(t(),rows.map(r=>({...r,source:{...r.source,path:'short/'+r.plan}})));const sources=p.sources.map(s=>{const ids=new Set(s.references.map(r=>r.evidenceId));return {...s,references:s.references.map(r=>({...r,sourceUrl:s.url,domLocator:rows.find(o=>o.source.url===s.url).source.path})).sort((a,b)=>stable(a).localeCompare(stable(b))),claims:p.claims.map(c=>({...c,established:c.established.map(a=>({...a,evidence:a.evidence.filter(e=>ids.has(e))})).filter(a=>a.evidence.length),missing:c.missing.map(a=>({...a,evidence:a.evidence.filter(e=>ids.has(e))})).filter(a=>a.evidence.length)})).filter(c=>c.established.length||c.missing.length).sort((a,b)=>stable(a).localeCompare(stable(b)))};}).sort((a,b)=>stable(a).localeCompare(stable(b)));
 const value={version:1,derivationVersion:'PRICE_EVIDENCE_NEEDS_V1',targetId:p.targetId,sources,claims:p.claims,meaning:p.meaning};return {...value,evidenceDigest:digest(value)};}
test('valid legacy maps without rewriting or changing assertions; corruption fails closed',()=>{const old=legacy([o()]),before=JSON.stringify(old),p=read({...t(),priceEvidenceNeeds:old});assert.equal(p.version,2);assert.deepEqual(p.originDerivations,['PRICE_EVIDENCE_NEEDS_V1']);assert.deepEqual(p.claims,old.claims);assert.equal(JSON.stringify(old),before);assert.throws(()=>read({...t(),priceEvidenceNeeds:{...old,evidenceDigest:'wrong'}}),/DIGEST/);assert.throws(()=>read({...t(),priceEvidenceNeeds:{...old,version:77}}),/SCHEMA/);});
test('equivalent legacy aggregate exceeds 2MiB while individually valid sources merge compactly',()=>{const target={...t(),verified:[{id:'durable'}],priorUsage:{reads:4,searches:1},requestCeiling:36};const rows=Array.from({length:7},(_,s)=>Array.from({length:32},(_,i)=>{const row=o(i,s);row.source.path='x'.repeat(12000);return row;})).flat();const old=legacy(rows);assert(bytes(old)>2097152);assert.throws(()=>read({...t(),priceEvidenceNeeds:old}),/SIZE_BOUND/);for(let s=0;s<7;s++)merge(target,legacy(rows.filter(r=>r.source.url.endsWith('/'+s))));assert(target.priceEvidenceNeeds.coverage.complete);assert(bytes(target.priceEvidenceNeeds)<2097152);assert.deepEqual(target.verified,[{id:'durable'}]);assert.deepEqual(target.priorUsage,{reads:4,searches:1});assert.equal(target.requestCeiling,36);console.log(JSON.stringify({legacyEquivalentAggregate:bytes(old),compactMerged:bytes(target.priceEvidenceNeeds)}));});
test('incompleteness permits existing bounded planning and never manufactures sufficiency',()=>{const target={...t(),smartResearch:{version:2},urls:[],verified:[],priceEvidenceNeeds:project(t(),Array.from({length:300},(_,i)=>o(i)))};const result=assessAdaptiveService(initializeAdaptiveState({targets:[target],conditionalFollowupTargets:[]}),target.service);assert.equal(result.next?.plan.route,'DISCOVERY');assert.notEqual(result.stop?.reason,'PRICE_EVIDENCE_PROJECTION_INCOMPLETE');assert.notEqual(result.stop?.reason,'BUDGET_EXHAUSTED');for(const confidence of ['HIGH','MEDIUM']){target.retainedPriceReview={sourceBound:true,amount:'12',confidence};const r=assessAdaptiveService(initializeAdaptiveState({targets:[target],conditionalFollowupTargets:[]}),target.service);assert.equal(r.stop.reason,confidence+'_SUFFICIENT');}});
test('incomplete serialized projection validates and unchanged input has stable digest',()=>{const p=project(t(),Array.from({length:300},(_,i)=>o(i)));const copy=JSON.parse(JSON.stringify(p));assert.deepEqual(read({...t(),priceEvidenceNeeds:copy}),p);assert.equal(copy.coverage.omittedDigest,p.coverage.omittedDigest);});
test('oversized semantic field is explicitly omitted, never truncated into a different plan',()=>{const row=o();row.plan='long'.repeat(5000);const p=project(t(),[row]);assert.equal(p.claims.length,0);assert.equal(p.coverage.complete,false);assert.deepEqual(p.coverage.reasons,['FIELD_BOUND']);assert.equal(p.coverage.omittedClaims,1);assert.deepEqual(read({...t(),priceEvidenceNeeds:JSON.parse(JSON.stringify(p))}),p);});
test('missing and established evidence remain separate and evidence change updates digest',()=>{const a=o(),b={...o(),source:{...o().source,hash:'b'.repeat(64)},fields:{...o().fields,offerPresentation:{status:'ESTABLISHED'}}};const p=project(t(),[a,b]),c=p.claims[0];assert(c.established.some(a=>a.assertion==='offerPresentation'));assert(c.missing.some(a=>a.assertion==='offerPresentation'));assert.notEqual(p.evidenceDigest,project(t(),[a]).evidenceDigest);assert.deepEqual(p,project(t(),[b,a,b]));});
test('over-bound input ordering and duplicate-set digest are deterministic',()=>{const rows=Array.from({length:2050},(_,i)=>o(i));const p=project(t(),rows),q=project(t(),rows.reverse());assert.deepEqual(p,q);assert.equal(p.coverage.omittedObservations,2050);assert.deepEqual(read({...t(),priceEvidenceNeeds:p}),p);});

test('incomplete evidence updates represented claims and repeated incomplete merges are idempotent',()=>{const target=t(),a=project(target,[o(),{...o(2,2),plan:'x'.repeat(20000)}]),b=project(target,[o(1,1),{...o(3,3),plan:'y'.repeat(20000)}]);merge(target,a);merge(target,b);const before=JSON.stringify(target.priceEvidenceNeeds);merge(target,b);assert.equal(JSON.stringify(target.priceEvidenceNeeds),before);merge(target,a);assert.equal(JSON.stringify(target.priceEvidenceNeeds),before);const prior=target.priceEvidenceNeeds.evidenceDigest;merge(target,project(target,[{...o(),amount:29,source:{...o().source,hash:'b'.repeat(64)}}]));assert.notEqual(target.priceEvidenceNeeds.evidenceDigest,prior);assert.equal(target.priceEvidenceNeeds.coverage.complete,false);assert.deepEqual(read(target),target.priceEvidenceNeeds);assert.equal(target.priceEvidenceNeeds.coverage.omittedClaims,2);});

test('incremental bound omission validates and repeated over-bound source is stable',()=>{const target=t(),a=project(target,Array.from({length:180},(_,i)=>o(i,0))),b=project(target,Array.from({length:180},(_,i)=>o(i+180,1)));merge(target,a);merge(target,b);assert.equal(target.priceEvidenceNeeds.coverage.complete,false);assert.deepEqual(read(target),target.priceEvidenceNeeds);const before=JSON.stringify(target.priceEvidenceNeeds);merge(target,b);assert.equal(JSON.stringify(target.priceEvidenceNeeds),before);assert(bytes(target.priceEvidenceNeeds)<=priceNeedsBounds.bytes);});
