import test,{after} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {inspectServiceAdmission,observeAdmissionSource} from './service-admission-source.mjs';
import {evaluateServiceAdmission,revalidateTargetAdmission,admissionContract} from './service-admission.mjs';
import {catalogProductPolicy} from './catalog-capabilities.mjs';
import {finalState} from '../live/new-service-runtime.mjs';
import {lifecycleSeed,writeLifecycleDisposition} from '../inventory/lifecycle-continuation.mjs';
import {priceTargets,replayTarget} from '../inventory/reviewed-cohort-execution.mjs';
import {initializeAdaptiveState} from '../inventory/adaptive-campaign.mjs';
const sourceRoot=fs.mkdtempSync(path.join(os.tmpdir(),'admission-sources-'));after(()=>fs.rmSync(sourceRoot,{recursive:true,force:true}));
const at=Date.now(),capturedAt=new Date(at-1000).toISOString(),sha=s=>createHash('sha256').update(s).digest('hex');
const authority={status:'CONFIGURED_REVIEWED',provider:'Example',hostname:'example.com',sourceType:'OFFICIAL_PROVIDER'};
const base=()=>({id:'example-catalog',service:'example',serviceName:'Example',authorities:[authority],urls:['https://example.com/'],researchObjective:'CATALOG_ONLY'});
const p=s=>'<p>'+s+'</p>';
const monthly='Your membership automatically renews each month.';
const size='Example has 100,000 subscribers.';
const capabilities='<a href="/account">Log in</a><p>You can manage your subscription in your online account.</p>';
const full=p(size)+p(monthly)+capabilities;
function source(body,overrides={}){const sourceHash=sha(body),file=path.join(sourceRoot,sourceHash+'.txt');fs.writeFileSync(file,body);return {body,sourceHash,url:'https://example.com/membership',service:'example',serviceName:'Example',authority,capturedAt,reference:{path:file,hash:sourceHash},...overrides};}
const proof=(body,overrides)=>inspectServiceAdmission(source(body,overrides));
const evaluate=(body,overrides)=>evaluateServiceAdmission('example',[proof(body,overrides)].filter(Boolean),{at,authorities:[authority]});
const dimension=(text,name='monthlyRecurring')=>evaluate(p(text)).dimensions[name];

test('manifest is normative: four independent requirements, 100000 users',()=>{assert.equal(admissionContract.minimumUsers,100000);const r=evaluate('');assert.deepEqual(Object.keys(r.dimensions),['serviceSize','monthlyRecurring','accountLogin','membershipManagement']);assert.equal(r.status,'UNRESOLVED');assert.equal(r.providerPriceRequired,false);assert.equal(r.cancellationRequired,false);});
test('Peloton-like monthly renewal proves cadence without any price',()=>{const d=dimension('Your membership renews automatically every month.');assert.equal(d.status,'ESTABLISHED');assert.equal(d.evidence[0].billingInterval,'P1M');assert.equal(d.evidence[0].source.sourceHash.length,64);});
test('both monthly and annual options: one genuine monthly offer suffices',()=>{const r=evaluate(p('Your subscription is billed monthly.')+p('Your subscription is billed annually.'));assert.equal(r.dimensions.monthlyRecurring.status,'ESTABLISHED');});
for(const [label,statement] of [
 ['Autoliitto annual','Example Plus membership costs €133 / 12 months.'],
 ['yearly','Your membership is billed yearly.'],
 ['monthly equivalent','Your subscription costs €120 annually and works out as €10/month.'],
 ['benefit value','Your membership includes insurance benefit value ca €169 / 12 months.'],
 ['installments','Your subscription is billed monthly in installments for the annual purchase.'],
 ['generic recurring','Your membership renews automatically.'],
 ['monthly-looking value','Your subscription is €10 per month.'],
 ['usage','Your subscription includes a monthly usage allowance.'],
 ['hypothetical','Your subscription could be billed monthly.'],
 ['negation','Your subscription is not billed monthly.'],
 ['business','Your business subscription is billed monthly.'],
 ['other service','OtherProvider membership is billed monthly.'],
 ['monthly equivalent misleading predicate','Your subscription is billed monthly equivalent to an annual fee.'],
 ['annual commitment','Your subscription is billed monthly with an annual commitment.']
])test(label+' cannot establish monthly recurrence',()=>assert.equal(dimension(statement).status,'UNRESOLVED'));
test('script, dictionary, navigation and footer are not qualification statements',()=>{assert.equal(evaluate('<script>'+JSON.stringify({text:monthly})+'</script><footer>'+p(monthly)+'</footer><nav>'+p(monthly)+'</nav>').dimensions.monthlyRecurring.status,'UNRESOLVED');});
test('a single annual offer does not prove absence of all monthly offers',()=>assert.equal(dimension('Your membership is billed annually.').status,'UNRESOLVED'));
for(const [statement,status] of [
 ['Example has 100,000 subscribers.','ESTABLISHED'],['Example serves 1 million customers.','ESTABLISHED'],['Example has 99999 users.','DISQUALIFIED'],
 ['Example has over 99999 users.','UNRESOLVED'],['Example has about 100000 users.','UNRESOLVED'],['Example has many subscribers.','UNRESOLVED'],
 ['Example has 100000 downloads.','UNRESOLVED'],['Example has 100000 visits.','UNRESOLVED'],['Example has 100000 followers.','UNRESOLVED'],
 ['Example Group has 100000 customers.','UNRESOLVED'],['Example has 100000 customers across its parent group.','UNRESOLVED'],['Other has 100000 subscribers.','UNRESOLVED'],
 ['Example expects 100000 subscribers.','UNRESOLVED']
])test('size: '+statement,()=>assert.equal(dimension(statement,'serviceSize').status,status));
test('conflicting exact size evidence remains reviewable',()=>assert.equal(evaluate(p(size)+p('Example has 99999 users.')).dimensions.serviceSize.status,'UNRESOLVED'));
test('login alone does not establish management or admission',()=>{const r=evaluate('<a href="/account">Log in</a>');assert.equal(r.dimensions.accountLogin.status,'ESTABLISHED');assert.equal(r.dimensions.membershipManagement.status,'UNRESOLVED');assert.equal(r.status,'UNRESOLVED');});
test('management does not imply monthly cadence',()=>{const r=evaluate(capabilities);assert.equal(r.dimensions.membershipManagement.status,'ESTABLISHED');assert.equal(r.dimensions.monthlyRecurring.status,'UNRESOLVED');assert.equal(r.status,'UNRESOLVED');});
test('all four dimensions admit without price, cancellation or geographic breadth',()=>{const r=evaluate(full);assert.equal(r.status,'ESTABLISHED');assert(Object.values(r.dimensions).every(d=>d.status==='ESTABLISHED'));assert.equal(r.providerPriceRequired,false);const policy=catalogProductPolicy({slug:'example',disposition:'NEW_INCLUDE'},{admissionEvidence:[proof(full)],admissionOptions:{at},confidence:'NONE'});assert(policy.catalogEligible);assert(policy.readyForNewCatalogPublication);assert.equal(policy.priceStrategy,'MANUAL_ONLY');});
test('NEW_INCLUDE and legacy subscription/management/price flags never grant admission',()=>{for(const disposition of ['NEW_INCLUDE','EXISTING','RESEARCH']){const r=catalogProductPolicy({slug:'example',disposition},{consumerSubscriptionEstablished:true,confidence:'HIGH'});assert.equal(r.catalogEligible,false);assert(r.researchEligible);}for(const stage of ['MANAGEMENT','PRICING'])assert.equal(finalState({[stage]:{established:true}}).subscriptionQualification,'UNRESOLVED');});
test('new establishment requires freshness, authority, source hash and reference integrity',()=>{for(const overrides of [{sourceHash:'0'.repeat(64)},{reference:{path:'x',hash:'bad'}},{authority:{...authority,status:'UNREVIEWED'}},{authority:{...authority,hostname:'foreign.test'}},{capturedAt:'invalid'},{capturedAt:new Date(at-31*86400000).toISOString()}])assert.equal(evaluate(full,overrides).status,'UNRESOLVED');});
test('legacy and tampered serialized proofs do not qualify on replay',()=>{const original=proof(full);for(const bad of [{...original,version:'LEGACY'}, {...original,facts:[{dimension:'monthlyRecurring',status:'ESTABLISHED'}]}])assert.equal(evaluateServiceAdmission('example',[bad],{at}).status,'UNRESOLVED');assert.equal(evaluateServiceAdmission('other',[original],{at}).status,'UNRESOLVED');});
test('retained save/reload revalidates proof and keeps usage, price and capabilities separate',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)],reads:[{requestedUrl:'https://example.com/',outcome:'OK'}],queries:[],verified:[],capabilities:{direct:false,decodo:true,tavily:false}};revalidateTargetAdmission(t,{at});const seed=lifecycleSeed(base(),{states:{[t.id]:{target:JSON.parse(JSON.stringify(t)),reference:{path:'prior.json',hash:'a'.repeat(64)}}}});assert.equal(seed.serviceAdmission.status,'ESTABLISHED');assert.equal(seed.priorUsage.reads,1);assert.deepEqual(seed.capabilities,t.capabilities);assert.deepEqual(seed.verified,[]);const legacy=lifecycleSeed(base(),{states:{[t.id]:{target:{...t,serviceAdmission:undefined,serviceAdmissionEvidence:[],subscriptionQualification:'ESTABLISHED',productionEligible:true},reference:{path:'prior',hash:'b'.repeat(64)}}}});assert.equal(legacy.productionEligible,false);assert.equal(legacy.serviceAdmission.dimensions.monthlyRecurring.status,'UNRESOLVED');});
test('authority changes cannot grandfather earlier admission',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};const changed={...base(),authorities:[]};assert.equal(lifecycleSeed(changed,{states:{[t.id]:{target:t}}}).serviceAdmission.status,'UNRESOLVED');});
test('research pricing targets remain explicitly non-admitted hypotheses',()=>{const t=priceTargets([base()],{example:['FI']},['example'])[0];assert.equal(t.pricingExposure,'RESEARCH_HYPOTHESIS_ONLY');assert.equal(t.productionEligible,false);assert.equal(t.scopeBasis,'OPERATOR_RESEARCH_HYPOTHESIS_NOT_AVAILABILITY');assert.equal(t.serviceAdmission.dimensions.monthlyRecurring.status,'UNRESOLVED');const state=initializeAdaptiveState({targets:[t],conditionalFollowupTargets:[]},{retainedStates:[{...t,productionEligible:true,subscriptionQualification:'ESTABLISHED'}]});assert.equal(state.targets[t.id].productionEligible,false);assert.equal(state.services.example.used.reads,0);});
test('source observation persists dimension proofs rather than inheriting normalized price',()=>{const t={...base(),verified:[{amount:'169',billingInterval:'P1M'}]};const s=source(p('Your membership costs €133 / 12 months.'));observeAdmissionSource(t,{bodyHash:s.sourceHash,url:s.url,authority,capturedAt},s.body,s.reference,{at});assert.equal(t.serviceAdmission.dimensions.monthlyRecurring.status,'UNRESOLVED');assert.equal(t.verified.length,1);assert(t.serviceAdmissionEvidence.length);});
test('final disposition preserves research price but gates admitted exposure and ignores generic price qualification',t=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),'admission-disposition-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const catalog={...base(),catalogEligibility:{status:'LOGIN_MANAGE_ESTABLISHED'},serviceAdmissionEvidence:[proof(full)]};const price={...base(),id:'example-price-FI',market:'FI',verified:[]};const args={directory,handoff:{cohort:{manifest:{serviceIds:['example']}},targets:[base()]},phases:{catalog:{targets:{[catalog.id]:catalog}},pricing:{targets:{[price.id]:price}}},events:[],bootstrap:[],researchMarkets:{example:['FI']},executionComplete:true};let row=writeLifecycleDisposition(args)[0];assert.equal(row.serviceAdmission.status,'ESTABLISHED');assert.equal(row.pricing[0].status,'UNRESOLVED');assert.equal(row.productionEligible,true);assert.equal(row.pricing[0].publicationEligible,false);catalog.serviceAdmissionEvidence=[];row=writeLifecycleDisposition(args)[0];assert.equal(row.productionEligible,false);assert.equal(row.pricing[0].exposure,'RESEARCH_HYPOTHESIS_ONLY');assert.equal(row.subscriptionQualification.status,'UNRESOLVED');});
test('a later annual/installment qualification in the same paragraph cannot be dropped',()=>{for(const qualifier of ['The commitment is annual.','The charge is an installment.','The fee is a benefit value.'])assert.equal(dimension('Your subscription is billed monthly. '+qualifier).status,'UNRESOLVED');});
test('missing bytes or invalidation cannot create admission without a prior receipt',()=>{const body=p(size)+p(monthly)+'<!--missing-reference-->',value=proof(body);fs.unlinkSync(value.reference.path);const r=evaluateServiceAdmission('example',[value],{at});assert.equal(r.status,'UNRESOLVED');assert.equal(r.rejectedEvidence[0].reason,'QUALIFICATION_SOURCE_REVALIDATION_REQUIRED');const t={...base(),serviceAdmissionEvidence:[proof(full)],invalidatedEvidence:[sha(full)]};assert.equal(revalidateTargetAdmission(t,{at}).status,'UNRESOLVED');});
test('a changed source or forged semantic fact cannot satisfy the new contract',()=>{const b=full+'<!--tamper-test-->',value=proof(b);fs.writeFileSync(value.reference.path,b+'changed');assert.equal(evaluateServiceAdmission('example',[value],{at}).status,'UNRESOLVED');});
test('native retained replay collects qualification from bytes without verified pricing',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'admission-replay-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const body=full,bodyHash=sha(body),bodyFile='bodies/'+bodyHash+'.txt';fs.mkdirSync(root+'/input/bodies',{recursive:true});fs.writeFileSync(root+'/input/'+bodyFile,body);const page={outcome:'OK',httpStatus:200,url:'https://example.com/membership',requestedUrl:'https://example.com/membership',bodyHash,bodyFile,authority,checkedAt:capturedAt,sourceIntegrity:{sha256:bodyHash,checkedAt:capturedAt},accessDecisions:[{decision:'ALLOWED'}]};fs.writeFileSync(root+'/input/pages.json',JSON.stringify([page]));const target=base(),registry={domains:[{service:'example',hostname:'example.com',validated:true,role:'OFFICIAL_PROVIDER',reference:{kind:'REVIEWED_OWNERSHIP'}}]};const result=await replayTarget({target,directory:root+'/output',sourceDirectory:root+'/input',registry});assert.equal(result.accepted,1,JSON.stringify(result.rejected));assert.equal(result.target.serviceAdmission.status,'ESTABLISHED');assert.equal(result.networkCalls,0);const saved=JSON.parse(fs.readFileSync(root+'/output/retained-replay.json'));assert.equal(saved.target.serviceAdmission.dimensions.monthlyRecurring.status,'ESTABLISHED');});

function independentProof(statement,root,{service='example',reviewed=true,url='https://example.com/'+root}={}){
 const body=p(statement),s=source(body,{url,service}),review={version:'QUALIFICATION_INDEPENDENCE_REVIEW_V1',proofKind:'CORROBORATING_OBSERVATION',status:reviewed?'REVIEWED':'UNREVIEWED',reviewer:'offline-reviewer',reason:'Independently originated evidence, not a quotation, mirror or reused assertion',service,url,sourceHash:s.sourceHash,rootIds:[root]},bytes=JSON.stringify(review),file=path.join(sourceRoot,sha(bytes)+'.json');fs.writeFileSync(file,bytes);
 return inspectServiceAdmission({...s,authority:{...authority,sourceType:'OFFICIAL_SUPPORT',qualificationEvidenceReview:{path:file,sha256:sha(bytes)}}});
}
const independentMonthly=()=>['Your membership is billed monthly.','Your subscription is charged every calendar month.','Your membership renews automatically each month.'].map((s,i)=>independentProof(s,'origin-'+i));
test('policy 1: three strong independent valid monthly proofs establish; two do not',()=>{const proofs=independentMonthly();assert.equal(evaluateServiceAdmission('example',proofs.slice(0,2),{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');const r=evaluateServiceAdmission('example',proofs,{at});assert.equal(r.dimensions.monthlyRecurring.status,'ESTABLISHED');assert.equal(r.dimensions.monthlyRecurring.decision.positive.rule,'INDEPENDENT_STRONG_CORROBORATION');assert.equal(r.dimensions.monthlyRecurring.decision.positive.independentGroups.length,3);});
test('policy 2: duplicate, derivative and mirrored observations are dependent',()=>{const one=independentMonthly()[0];assert.equal(evaluateServiceAdmission('example',[one,one,one],{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');const statements=['Your membership is billed monthly.','Your subscription is charged every calendar month.','Your membership renews automatically each month.'];const derived=statements.map((s,i)=>independentProof(s,'same-origin',{url:'https://example.com/derivative-'+i}));assert.equal(evaluateServiceAdmission('example',derived,{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');const mirrors=Array.from({length:3},(_,i)=>independentProof(statements[0],'mirror-'+i));assert.equal(evaluateServiceAdmission('example',mirrors,{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');});
test('independence requires an intact reviewed source-specific provenance record',()=>{const proofs=['Your membership is billed monthly.','Your subscription is charged every calendar month.','Your membership renews automatically each month.'].map((s,i)=>independentProof(s,'unreviewed-'+i,{reviewed:false}));assert.equal(evaluateServiceAdmission('example',proofs,{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');});
test('policy 3/11: three semantically invalid annual/equivalent/benefit proofs never establish monthly',()=>{const proofs=['Your membership is billed annually.','Your subscription costs €120 annually and works out as €10/month.','Your membership includes insurance benefit value ca €169 / 12 months.'].map((s,i)=>independentProof(s,'invalid-'+i));assert.equal(evaluateServiceAdmission('example',proofs,{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');});
for(const [label,patch] of [
 ['policy 4: failure to rediscover',{serviceAdmissionEvidence:[]}],
 ['policy 5: acquisition failure',{reads:[{outcome:'ACCESS_CONTROL_STOP',failure:{code:'ROBOTS_ACCESS_STOP'}}]}],
 ['policy 6: missing current authority metadata',{authorities:[]}],
 ['age alone is not contradiction',{retainedMaxAgeDays:0}],
 ['missing current capture metadata',{serviceAdmissionEvidence:[{capturedAt:null}]}],
 ['invalidated acquisition reference alone is not a counterfact',{invalidatedEvidence:[sha(full)]}]
])test(label+' preserves established typed admission',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});assert.equal(t.serviceAdmission.status,'ESTABLISHED');Object.assign(t,patch);assert.equal(revalidateTargetAdmission(t,{at:at+90*86400000}).status,'ESTABLISHED');});
test('policy 5/9/10: missing original bytes preserves typed monthly and size receipts across save/reload',()=>{const body=full+'<!--persistence-->',t={...base(),serviceAdmissionEvidence:[proof(body)]};revalidateTargetAdmission(t,{at});fs.unlinkSync(t.serviceAdmissionEvidence[0].reference.path);const restored=JSON.parse(JSON.stringify(t));revalidateTargetAdmission(restored,{at:at+365*86400000});for(const d of ['monthlyRecurring','serviceSize']){assert.equal(restored.serviceAdmission.dimensions[d].status,'ESTABLISHED');assert(restored.serviceAdmission.dimensions[d].decision.retainedObservationIds.length);}assert.equal(restored.serviceAdmission.status,'ESTABLISHED');});
test('changed page structure does not negate a previously established proposition',()=>{const body=full+'<!--structure-->',t={...base(),serviceAdmissionEvidence:[proof(body)]};revalidateTargetAdmission(t,{at});fs.writeFileSync(t.serviceAdmissionEvidence[0].reference.path,'<p>New page layout without the prior statement.</p>');assert.equal(revalidateTargetAdmission(t,{at}).status,'ESTABLISHED');});
test('policy 7: source-bound actual size contradiction triggers durable re-evaluation',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});t.serviceAdmissionEvidence=[proof(p('Example has 99999 users.'))];const r=revalidateTargetAdmission(t,{at});assert.equal(r.dimensions.serviceSize.status,'UNRESOLVED');assert.equal(r.dimensions.serviceSize.decision.reason,'ESTABLISHED_CONTRADICTORY_EVIDENCE');assert.equal(r.dimensions.serviceSize.decision.negative.established,true);t.serviceAdmissionEvidence=[];assert.equal(revalidateTargetAdmission(t,{at}).dimensions.serviceSize.status,'UNRESOLVED');});
test('service-wide annual-only counterfact contradicts monthly, an annual option does not',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});t.serviceAdmissionEvidence=[proof(p('Your subscription is billed annually.'))];assert.equal(revalidateTargetAdmission(t,{at}).dimensions.monthlyRecurring.status,'ESTABLISHED');t.serviceAdmissionEvidence=[proof(p('Example offers only annual consumer memberships.'))];assert.equal(revalidateTargetAdmission(t,{at}).dimensions.monthlyRecurring.status,'UNRESOLVED');assert.equal(t.serviceAdmission.dimensions.monthlyRecurring.decision.negative.established,true);});
test('unrelated service counterfacts cannot defeat typed admission',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});t.serviceAdmissionEvidence=[proof(p('Other has 90000 users. Other offers only annual consumer memberships.'))];assert.equal(revalidateTargetAdmission(t,{at}).status,'ESTABLISHED');});
test('policy 8: legacy booleans and typed-looking statuses without receipts cannot be grandfathered',()=>{const t={...base(),productionEligible:true,subscriptionQualification:'ESTABLISHED',serviceAdmission:{version:'SERVICE_ADMISSION_V1',service:'example',status:'ESTABLISHED',dimensions:{monthlyRecurring:{status:'ESTABLISHED'}}}};assert.equal(revalidateTargetAdmission(t,{at}).status,'UNRESOLVED');});
test('policy 12: three service-unbound size observations remain unresolved',()=>{const proofs=['Other has 100000 users.','Example Group has 200000 subscribers.','Example has 1000000 downloads.'].map((s,i)=>independentProof(s,'bad-size-'+i));assert.equal(evaluateServiceAdmission('example',proofs,{at}).dimensions.serviceSize.status,'UNRESOLVED');});
test('typed size corroboration respects exact service threshold and persists',()=>{const proofs=['Example has 100000 users.','Example serves over 200000 customers.','Example counts 300000 subscribers.'].map((s,i)=>independentProof(s,'size-'+i));const t={...base(),serviceAdmissionEvidence:proofs};assert.equal(revalidateTargetAdmission(t,{at}).dimensions.serviceSize.status,'ESTABLISHED');t.serviceAdmissionEvidence=[];assert.equal(revalidateTargetAdmission(t,{at}).dimensions.serviceSize.status,'ESTABLISHED');});
test('policy 13: corroborated monthly evidence cannot compensate for unresolved size/login/manage',()=>{const r=evaluateServiceAdmission('example',independentMonthly(),{at});assert.equal(r.dimensions.monthlyRecurring.status,'ESTABLISHED');for(const d of ['serviceSize','accountLogin','membershipManagement'])assert.equal(r.dimensions[d].status,'UNRESOLVED');assert.equal(r.status,'UNRESOLVED');});
test('lifecycle seed retains typed facts when current ownership metadata is absent',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});const seed=lifecycleSeed({...base(),authorities:[]},{states:{[t.id]:{target:t}}});assert.equal(seed.serviceAdmission.status,'ESTABLISHED');assert.deepEqual(seed.authorities,[]);});
test('tampered persistence receipt is not valid typed establishment',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});t.serviceAdmissionEvidence=[];t.serviceAdmission.dimensions.serviceSize.decision.receipt.observations[0].evidence.count=99999;assert.equal(revalidateTargetAdmission(t,{at}).dimensions.serviceSize.status,'UNRESOLVED');});
test('reviewed provider support FAQ can directly establish genuine monthly billing',()=>{const r=evaluate(p('Your subscription is billed monthly.'),{authority:{...authority,sourceType:'OFFICIAL_SUPPORT'}});assert.equal(r.dimensions.monthlyRecurring.status,'ESTABLISHED');assert.equal(r.dimensions.monthlyRecurring.decision.positive.rule,'DIRECT_TYPED_PROOF');});
for(const [dimension,statement]of [['accountLogin','Example subscribers cannot log in to their account.'],['membershipManagement','Example members can no longer manage their membership in their account.']])test('relevant negative '+dimension+' triggers re-evaluation',()=>{const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});t.serviceAdmissionEvidence=[proof(p(statement))];assert.equal(revalidateTargetAdmission(t,{at}).dimensions[dimension].status,'UNRESOLVED');assert.equal(t.serviceAdmission.dimensions[dimension].decision.negative.established,true);});
test('unrelated quoted membership and other-service prose do not qualify',()=>{for(const b of ['<blockquote>'+p(monthly)+'</blockquote>',p('Your subscription to another provider is billed monthly.')])assert.equal(evaluate(b).dimensions.monthlyRecurring.status,'UNRESOLVED');});
test('subset audience count cannot disqualify the global service total',()=>assert.equal(dimension('Example has 99999 users in one country.','serviceSize').status,'UNRESOLVED'));
test('conditional, interrogative and scoped statements cannot become service-wide contradictions',()=>{for(const statement of ['Example subscribers cannot log in to their account?','Example subscribers cannot log in to their account if cookies are disabled.','Example offers only annual memberships for business customers.']){const t={...base(),serviceAdmissionEvidence:[proof(full)]};revalidateTargetAdmission(t,{at});t.serviceAdmissionEvidence=[proof(p(statement))];assert.equal(revalidateTargetAdmission(t,{at}).status,'ESTABLISHED');}});
