import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {submission,leadContext,snapshotDocument,freezeLeads,readLeadSnapshot,candidateLeads,verifyAdmittedLeads} from './snapshot.mjs';
import {canonical,sha} from '../storage/core.mjs';import {closure} from '../storage/references.mjs';
import {validateGenesisExecutionSelection} from '../storage/genesis-deployment.mjs';
import {Operations} from '../../v2-operations/control.mjs';import {operationsRequest} from '../../v2-operations/http.mjs';
import {executableAction} from '../live/execution-capabilities.mjs';import {destinationInformation} from '../live/information-routing.mjs';import {leadOutcomeRecorder} from './outcomes.mjs';
const caps={direct:true,tavily:true,decodo:false,browser:false,groq:false};
function fixture(t){const root=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'human-lead-')));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const put=(p,v)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,JSON.stringify(v));};const config={version:1,cohortManifest:'manifest.json',universe:'universe.json',runsRoot:'.savlivo/research-v2/test',executionServices:['film'],capabilities:caps};put('manifest.json',{serviceIds:['film']});put('universe.json',{existing:[{service:'netflix',name:'Netflix'}],new_include:[{slug:'film',name:'Film',markets:['NO','SE']}],research:[]});put('input.json',config);const ops=new Operations({root:root+'/ops',repo:root,lifecycleInput:'input.json',read:true,control:true,scheduling:false});ops.index=()=>[];ops.conflicts=()=>[];const context=leadContext(config,root);const record=(patch={})=>({...submission({type:'PRICING',url:'https://provider.example/pricing',marketScope:['NO']}),leadId:randomUUID(),serviceId:'film',createdBy:'actor-a',createdAt:'2026-09-23T00:00:00Z',updatedAt:'2026-09-23T00:00:00Z',status:'UNVERIFIED',...patch});const request=(method,body,actor='actor-a',suffix='')=>operationsRequest({method,body,actor,url:new URL('http://local/v1/admin/v2-operations/services/film/leads'+suffix)},ops);return {root,put,ops,config,context,record,request};}
test('snapshot order is canonical, exact-byte hash stable; changes change identity',t=>{const f=fixture(t),a=f.record(),b=f.record({marketScope:['SE','NO'],url:'https://provider.example/plans'});const one=freezeLeads(f.root,f.context,[a,b]),two=freezeLeads(f.root,f.context,[{...b,marketScope:['NO','SE']},a]);assert.deepEqual(one,two);assert.equal(readLeadSnapshot(f.root,one,f.context).leads.length,2);assert.notEqual(freezeLeads(f.root,f.context,[a,{...b,url:'https://provider.example/other'}]).sha256,one.sha256);});
test('snapshot excludes inactive, other service and non-applicable markets',t=>{const f=fixture(t);assert.equal(snapshotDocument(f.context,[f.record(),f.record({status:'DEACTIVATED'}),f.record({serviceId:'netflix'}),f.record({marketScope:['DE']})]).leads.length,1);});
for(const url of ['file:///etc/passwd','javascript:alert(1)','data:text/html,hello','not a url','http://localhost/','http://127.0.0.1/','http://169.254.169.254/','https://user:secret@provider.example/'])test('unsafe submission rejected: '+url,()=>assert.throws(()=>submission({type:'PRICING',url}),/HUMAN_LEAD_URL/));
test('market and client identity fields are rejected; note remains plain text',()=>{assert.throws(()=>submission({type:'PRICING',url:'https://example.com',marketScope:['ZZ']}),/MARKET/);assert.throws(()=>submission({type:'PRICING',url:'https://example.com',createdBy:'forged'}),/SCHEMA/);assert.equal(submission({type:'PRICING',url:'https://example.com',note:'<script>alert(1)</script>'}).note,'<script>alert(1)</script>');});
test('authenticated creation records server actor, no evidence/job, creator-only deactivation preserves original',async t=>{const f=fixture(t),body={type:'PRICING',url:'https://provider.example/pricing'};await assert.rejects(f.request('POST',body,null),/UNAUTHORIZED/);const lead=await f.request('POST',body);assert.equal(lead.status,'UNVERIFIED');f.ops.config.control=false;assert.equal((await f.request('GET')).rows[0].canDeactivate,false);await assert.rejects(f.request('POST',body),/RUN_CONTROL_DISABLED/);f.ops.config.control=true;assert.equal(f.ops.db().humanLeads[0].createdBy,'actor-a');assert.equal(f.ops.db().jobs.length,0);assert.equal(f.ops.db().humanLeads[0].authority,undefined);await assert.rejects(f.request('POST',{action:'deactivate'},'actor-b','/'+lead.leadId),/LEAD_NOT_FOUND/);await f.request('POST',{action:'deactivate'},'actor-a','/'+lead.leadId);const saved=f.ops.db().humanLeads[0];assert.equal(saved.status,'DEACTIVATED');assert.equal(saved.url,body.url);assert.equal(f.ops.db().events.length,2);assert.equal((await f.request('GET',undefined,'actor-b')).rows[0].createdBy,'Admin operator');});
for(const mutation of ['missing','bytes','binding','scope','escape'])test('snapshot fails closed: '+mutation,t=>{const f=fixture(t),binding=freezeLeads(f.root,f.context,[f.record()]);if(mutation==='missing')fs.renameSync(f.root+'/'+binding.path,f.root+'/'+binding.path+'.held');if(mutation==='bytes')fs.appendFileSync(f.root+'/'+binding.path,' ');if(mutation==='binding')binding.sha256='a'.repeat(64);if(mutation==='escape')binding.path='../escape';const context=mutation==='scope'?{...f.context,services:['netflix']}:f.context;assert.throws(()=>readLeadSnapshot(f.root,binding,context));});
test('explicit Genesis extension verifies lead snapshot independently and still rejects baseline/unknown overrides',t=>{const f=fixture(t);const g={lifecycle:{productionInput:'input.json'},cohort:['film']};const binding=freezeLeads(f.root,f.context,[f.record()]);const check=c=>validateGenesisExecutionSelection(f.root,'.savlivo/v2-operations-inputs/'+sha(JSON.stringify(c))+'.json',c,g);check({...f.config,humanLeadSnapshot:binding});assert.throws(()=>check({...f.config,humanLeadSnapshot:{...binding,sha256:'f'.repeat(64)}}));assert.throws(()=>check({...f.config,humanLeadSnapshot:null}));assert.throws(()=>check({...f.config,executionServices:['netflix'],humanLeadSnapshot:binding}));assert.throws(()=>check({...f.config,reviewedBindings:'other.json',humanLeadSnapshot:binding}),/EXECUTION_INPUT_CHANGED/);assert.equal(JSON.parse(fs.readFileSync(f.root+'/input.json')).humanLeadSnapshot,undefined);});
test('reference closure protects snapshot and treats notes as metadata, never filesystem dependencies',t=>{const f=fixture(t),binding=freezeLeads(f.root,f.context,[f.record({note:'docs/not-a-reference.json'})]);const c=closure(f.root,[{...binding,format:'JSON',classification:'RESUME_CRITICAL'}]);assert.equal(c.errors.length,0);assert.equal(c.entries.length,1);});
test('frozen candidates retain IDs but cannot grant authority or bypass capabilities/budgets',t=>{const f=fixture(t),lead=f.record(),binding=freezeLeads(f.root,f.context,[lead]);const snapshot=readLeadSnapshot(f.root,binding,f.context);const target={service:'film',serviceName:'Film',market:'NO',researchObjective:'PRICING',leads:[],authorities:[],reads:[],capabilities:caps};const next=candidateLeads(target,snapshot,binding);assert.equal(next.leads[0].humanLead.leadId,lead.leadId);assert.equal(next.leads[0].authoritative,false);assert.deepEqual(next.authorities,[]);assert.equal(destinationInformation(next,lead.url,{}).reason,'AUTHORITY_UNRESOLVED');assert.equal(next.verified,undefined);assert.equal(candidateLeads({...target,market:'SE'},snapshot,binding).leads.length,0);assert.equal(candidateLeads({...target,researchObjective:'CATALOG_ONLY'},snapshot,binding).leads.length,0);assert.equal(executableAction({...next,capabilities:{...caps,direct:false}},{route:'DIRECT',url:lead.url}).reason,'DIRECT_DISABLED');assert.equal(executableAction({...next,reads:Array(4).fill({requestedUrl:lead.url})},{route:'DIRECT',url:lead.url}).reason,'DIRECT_BUDGET_EXHAUSTED');assert.equal(executableAction(next,{route:'CONDITIONAL_DECODO',url:lead.url}).executable,false);});
test('new Preflight removes deactivated historical human hints; frozen resume does not',t=>{const f=fixture(t),lead=f.record(),binding=freezeLeads(f.root,f.context,[lead]),snapshot=readLeadSnapshot(f.root,binding,f.context),target={service:'film',market:'NO',leads:[]};const seeded=candidateLeads(target,snapshot,binding);assert.equal(candidateLeads(seeded,snapshot,binding).leads.length,1);const empty=freezeLeads(f.root,f.context,[{...lead,status:'DEACTIVATED'}]);assert.equal(candidateLeads(seeded,readLeadSnapshot(f.root,empty,f.context),empty).leads.length,0);});
test('outcomes remain separate from immutable snapshot, temporary failure does not reject lead',t=>{const f=fixture(t),lead=f.record(),binding=freezeLeads(f.root,f.context,[lead]),before=fs.readFileSync(f.root+'/'+binding.path);const record=leadOutcomeRecorder(f.root,binding,readLeadSnapshot(f.root,binding,f.context));const target={service:'film',market:'NO'};record(target,lead.url,'ACQUISITION_ATTEMPTED',{route:'DIRECT'});record(target,lead.url,'ACQUISITION_RESULT',{outcome:'TIMEOUT'});const rows=fs.readFileSync(f.root+'/human-lead-outcomes.jsonl','utf8').trim().split('\n').map(JSON.parse);assert.equal(rows.length,2);assert(rows.every(r=>r.snapshotHash===binding.sha256&&r.leadId===lead.leadId));assert.deepEqual(fs.readFileSync(f.root+'/'+binding.path),before);assert.equal(readLeadSnapshot(f.root,binding,f.context).leads[0].status,'UNVERIFIED');});
test('Preflight freezes leads; Start and subsequent execution planning use same snapshot after mutable changes',async t=>{const f=fixture(t),child=await import('node:child_process'),{syncBuiltinESMExports}=await import('node:module');const seen=[];const stub=t.mock.method(child.default,'spawnSync',(_cmd,args)=>{const file=args[args.indexOf('--input')+1],input=JSON.parse(fs.readFileSync(file));const snap=readLeadSnapshot(f.root,input.humanLeadSnapshot,leadContext(input,f.root));seen.push(snap);return {status:0,stdout:JSON.stringify({output:'.savlivo/research-v2/test/'+sha(JSON.stringify(input)),networkCalls:0,onlineStarted:false,servicesSelected:1,maximumNewRequests:36,liveReady:true})};});syncBuiltinESMExports();try{const lead=await f.request('POST',{type:'PRICING',url:'https://provider.example/pricing'});const p=f.ops.preflight({objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:['film'],capabilities:caps},'actor-a');assert.equal(p.humanLeads.length,1);await f.request('POST',{action:'deactivate'},'actor-a','/'+lead.leadId);await f.request('POST',{type:'GENERAL',url:'https://provider.example/new'});const job=f.ops.start(p.token,'actor-a',true);assert.deepEqual(job.config.humanLeadSnapshot,p.config.humanLeadSnapshot);assert.equal(f.ops.prepareQueued(f.ops.db(),job),true);assert.equal(seen.length,3);assert(seen.every(s=>s.leads.length===1&&s.leads[0].leadId===lead.leadId));assert.equal(f.ops.db().jobs.length,1);assert.equal(f.ops.start(p.token,'actor-a',true).id,job.id);fs.appendFileSync(f.root+'/'+p.config.humanLeadSnapshot.path,'!');assert.throws(()=>f.ops.prepareQueued(f.ops.db(),job),/HASH/);}finally{stub.mock.restore();syncBuiltinESMExports();}});

test('mocked mature candidate execution acquires through existing controller, accounts once, resumes without re-fetch',async t=>{
 const {runAdaptiveCampaign}=await import('../inventory/adaptive-campaign.mjs');const f=fixture(t),lead=f.record(),binding=freezeLeads(f.root,f.context,[lead]);const target=candidateLeads({id:'film-no',service:'film',serviceName:'Film',market:'NO',urls:[],authorities:[{hostname:'provider.example',provider:'Film',sourceType:'OFFICIAL_PROVIDER',checkedAt:'2026-09-23'}],smartResearch:{version:2},researchObjective:'PRICING',priceStrategy:'MANUAL_ONLY',capabilities:caps},readLeadSnapshot(f.root,binding,f.context),binding);let reads=0,proxy=0;const args={directory:f.root+'/execution',manifest:{targets:[target],conditionalFollowupTargets:[]},createAdapters:async()=>({read:async({url})=>{reads++;assert.equal(url,lead.url);return {url,outcome:'UNRESOLVED',failure:{code:'TIMEOUT'}};},search:async()=>({results:[]}),classify:async()=>({eligible:false}),acquire:async()=>{proxy++;throw Error('Forbidden');}})};
 const state=await runAdaptiveCampaign(args);assert.equal(reads,1);assert.equal(state.services.film.used.reads,1);assert.equal(proxy,0);assert.equal(state.targets[target.id].verified.length,0);await runAdaptiveCampaign(args);assert.equal(reads,1);
});
test('fresh Preflight after lead change does not reuse an earlier successful operation',async t=>{
 const {beginPreflight}=await import('../../v2-operations/preflight-operations.mjs');const f=fixture(t);const input={objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:['film']};let launches=0;const launch=(_c,_i,_a,done)=>{launches++;done({result:{token:randomUUID(),expiresAt:new Date(Date.now()+1800000).toISOString()}});};const a=beginPreflight(f.ops,input,'actor-a',launch);const same=beginPreflight(f.ops,input,'actor-a',launch);assert.equal(a.id,same.id);await f.request('POST',{type:'GENERAL',url:'https://provider.example/new'});const b=beginPreflight(f.ops,input,'actor-a',launch);assert.notEqual(a.id,b.id);assert.equal(launches,2);assert.equal(f.ops.db().jobs.length,0);
});

test('execution/resume require identical job, manifest and derived-input bindings; never consult latest store',t=>{const f=fixture(t),binding=freezeLeads(f.root,f.context,[f.record()]),config={...f.config,humanLeadSnapshot:binding};f.put('derived.json',config);const manifest={humanLeadSnapshot:binding,lifecycle:{input:'derived.json',inputHash:sha(fs.readFileSync(f.root+'/derived.json'))}};assert.equal(verifyAdmittedLeads(f.root,config,manifest).leads.length,1);assert.throws(()=>verifyAdmittedLeads(f.root,config,{...manifest,humanLeadSnapshot:{...binding,sha256:'0'.repeat(64)}}),/ADMITTED_BINDING/);assert.throws(()=>verifyAdmittedLeads(f.root,{...config,humanLeadSnapshot:null},manifest),/ADMITTED_BINDING/);fs.renameSync(f.root+'/'+binding.path,f.root+'/'+binding.path+'.preserved');assert.throws(()=>verifyAdmittedLeads(f.root,config,manifest));});

test('normal catalog verifier, not a human submission, produces a source-bound proof and audit observation',async t=>{
 const {runAdaptiveCampaign}=await import('../inventory/adaptive-campaign.mjs');const f=fixture(t),lead=f.record({type:'MANAGEMENT',url:'https://provider.example/help/subscription'}),binding=freezeLeads(f.root,f.context,[lead]),snapshot=readLeadSnapshot(f.root,binding,f.context),record=leadOutcomeRecorder(f.root,binding,snapshot);
 const target=candidateLeads({id:'film-no',service:'film',serviceName:'Film',market:'NO',urls:[],authorities:[{hostname:'provider.example',provider:'Film',sourceType:'OFFICIAL_PROVIDER',checkedAt:'2026-09-23'}],smartResearch:{version:2},researchObjective:'CATALOG_ONLY',capabilities:caps},snapshot,binding);
 let proofs=0;const state=await runAdaptiveCampaign({directory:f.root+'/catalog',manifest:{targets:[target],conditionalFollowupTargets:[]},createAdapters:async()=>({read:async({url})=>({url,outcome:'OK',body:'<title>Film</title><p>You can manage your subscription in your online account.</p>',authority:{status:'CONFIGURED_REVIEWED'}}),search:async()=>({results:[]}),classify:async()=>({eligible:true}),onSourceObservation:({target,url,page,proof,directory})=>{proofs++;assert(proof.management.length>0);assert.equal(sha(fs.readFileSync(directory+'/'+page.bodyFile)),proof.sourceHash);record(target,url,'VERIFIER_RESULT',{route:'DIRECT',source:proof.reference,verificationHash:sha(JSON.stringify(proof)),verifierOutcome:'CATALOG_CAPABILITY_INTERPRETATION'});}})});
 assert.equal(proofs,1);assert(state.targets[target.id].catalogCapabilityProofs.some(p=>p.management.length));const audit=JSON.parse(fs.readFileSync(f.root+'/human-lead-outcomes.jsonl','utf8').trim());assert.equal(audit.leadId,lead.leadId);assert.equal(audit.snapshotHash,binding.sha256);assert.equal(snapshot.leads[0].status,'UNVERIFIED');
});

test('one market-unspecified pricing URL supplies independent market hints, never a proxy instruction',t=>{const f=fixture(t),lead=f.record({marketScope:[]}),binding=freezeLeads(f.root,f.context,[lead]),snapshot=readLeadSnapshot(f.root,binding,f.context);for(const market of ['NO','SE']){const target=candidateLeads({service:'film',market,capabilities:caps,authorities:[],leads:[]},snapshot,binding);assert.equal(target.leads.length,1);assert.equal(target.leads[0].url,lead.url);assert.equal(target.leads[0].proxy,undefined);assert.equal(target.marketApplicabilityEstablished,undefined);assert.equal(executableAction(target,{route:'CONDITIONAL_DECODO',url:lead.url}).executable,false);}});
test('public Preflight rejects client-supplied snapshot including null',async t=>{const f=fixture(t);for(const humanLeadSnapshot of [null,{path:'forged',sha256:'f'.repeat(64)}])await assert.rejects(operationsRequest({method:'POST',url:new URL('http://local/v1/admin/v2-operations/preflight'),actor:'actor-a',body:{objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:['film'],humanLeadSnapshot}},f.ops),/CLIENT_LEAD_SNAPSHOT_FORBIDDEN/);assert.equal(f.ops.db().jobs.length,0);});

test('service-wide account targets preserve null market while matching the frozen investigation scope',t=>{const f=fixture(t),lead=f.record({type:'MANAGEMENT'}),binding=freezeLeads(f.root,f.context,[lead]),snapshot=readLeadSnapshot(f.root,binding,f.context);const target=candidateLeads({service:'film',market:null,researchObjective:'CATALOG_ONLY',leads:[]},snapshot,binding);assert.equal(target.leads.length,1);assert.equal(target.market,null);assert.deepEqual(target.leads[0].humanLead.investigationMarkets,['NO']);});
