import test from 'node:test';import assert from 'node:assert/strict';import {mountOperations} from './v2-operations.js';
class Element{children=[];listeners={};textContent='';value='';append(...n){this.children.push(...n);}replaceChildren(...n){this.children=n;}addEventListener(k,v){this.listeners[k]=v;}setAttribute(k,v){this[k]=v;}remove(){this.removed=true;}set innerHTML(_){throw Error('Unsafe HTML');}}
const descendants=n=>[n,...n.children.flatMap(descendants)],text=n=>descendants(n).map(x=>x.textContent).join(' '),button=(n,name)=>descendants(n).find(x=>x.textContent===name&&x.listeners.click);
function setup(){globalThis.document={createElement:()=>new Element()};globalThis.window={confirm:()=>false};return new Element();}
const summary={flags:{read:true,control:false,scheduling:false},worker:{at:new Date().toISOString()},metrics:{catalog:2,complete:1,noPrice:1},refresh:null,health:{running:0,resumable:0,nextAutomatic:null,enabledSchedules:0},timezone:'Europe/Oslo'};
const request=async p=>p.endsWith('/summary')?summary:{rows:[],total:0};
test('operations empty/read-only state preserves price independence',async()=>{const root=setup();const dispose=await mountOperations(root,request);assert(text(root).includes('V2 Operations'));assert(text(root).includes('No provider price is not a catalog failure'));assert(button(root,'Preflight').disabled);dispose();});
test('operations loading state before response',async()=>{const root=setup();let resolve;const pending=mountOperations(root,()=>new Promise(r=>{resolve=r;}));assert(text(root).includes('Loading operations'));resolve(summary);const dispose=await pending;dispose();});
test('operations error state allows retry',async()=>{const root=setup(),dispose=await mountOperations(root,async()=>{throw Error('fixture unavailable');});assert(text(root).includes('Operations unavailable'));assert(button(root,'Retry'));dispose();});
test('empty schedules and scheduling-disabled controls',async()=>{const root=setup(),dispose=await mountOperations(root,request);await button(root,'Schedules').listeners.click();assert(text(root).includes('No automatic schedules'));assert(button(root,'Create schedule').disabled);dispose();});
for(const enabled of [true,false])test('schedule '+(enabled?'enabled':'disabled')+' display',async()=>{const root=setup(),dispose=await mountOperations(root,async p=>p.endsWith('/summary')?{...summary,flags:{read:true,control:true,scheduling:true}}:p.endsWith('/schedules')?{rows:[{id:'fixture',config:{objective:'LOGIN_MANAGE',scope:'UNRESOLVED_ONLY',reads:2,discovery:true,totalRequests:50,services:[]},enabled,frequency:'WEEKLY',nextRunAt:enabled?'2026-10-01':null,lastResult:'SKIPPED_CONFLICT'}]}:{rows:[],total:0});await button(root,'Schedules').listeners.click();assert(text(root).includes('SKIPPED_CONFLICT'));assert(button(root,enabled?'Disable':'Enable'));assert(button(root,'Run now'));dispose();});
for(const status of ['RUNNING','COMPLETE','INTERRUPTED','RESUMABLE','SKIPPED_CONFLICT'])test('run status '+status+' visible',async()=>{const root=setup(),dispose=await mountOperations(root,async p=>p.endsWith('/summary')?summary:{rows:[{id:'a'.repeat(24),name:'Fixture',objective:'LOGIN_MANAGE',origin:'CLI',status,requests:3}],total:1});await button(root,'Runs').listeners.click();assert(text(root).includes(status));dispose();});
test('session invalidation prevents operations rendering',async()=>{const root=setup();await mountOperations(root,request,()=>false);assert(!text(root).includes('Current knowledge'));});
