import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {adaptDocument,adaptSnapshot} from './schema-adapters.mjs';import {sha} from './core.mjs';import {closure} from './references.mjs';import {inspectLegacySnapshot,certifyLegacyBoundary} from './legacy-boundary.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'v2-final-blockers-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return {root,put(p,v){fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,typeof v==='string'?v:JSON.stringify(v));}};}
const extract=()=>({source:'/Users/absent/original.xlsx',sha256:'a'.repeat(64),mainSheet:'V15 Gate',mainRange:'A1:G216',rows:Array.from({length:215},(_,i)=>({sheetRow:i+2})),sidepoolRows:[]});
function workbook(t){const f=fixture(t),v=extract();f.put('discovery/discovery-input.json',v);f.put('discovery/manifest.json',{version:1,authorityBootstrap:1,scope:'NEW_SERVICES_ONLY',inputHashes:{'discovery/discovery-input.json':sha(JSON.stringify(v))},workbookSha256:v.sha256});return {...f,v};}
test('authenticated extracted workbook source is provenance only, companion manifest remains required',t=>{const f=workbook(t);const a=adaptDocument(f.root,f.v,'discovery/discovery-input.json');assert.deepEqual(a.provenanceOnly,['source']);assert(!Object.hasOwn(a.value,'source'));assert.equal(a.references[0].path,'discovery/manifest.json');assert.equal(JSON.parse(fs.readFileSync(f.root+'/discovery/discovery-input.json')).source,f.v.source);});
test('unfrozen extraction cannot exempt an absolute source path',t=>{const f=workbook(t);f.v.rows.push({sheetRow:300});f.put('discovery/discovery-input.json',f.v);assert.throws(()=>adaptDocument(f.root,f.v,'discovery/discovery-input.json'),/SCHEMA/);});
test('arbitrary absolute source outside the recognized extract still fails',t=>{const f=fixture(t);f.put('state.json',{source:'/Users/absent/provider.json'});assert(!closure(f.root,[{path:'state.json',format:'JSON',classification:'PERMANENT_CANONICAL'}]).complete);});
function snapshotFixture(t){const f=fixture(t),dir='runs/parent/pricing/direct-acquisitions/direct-fixture';f.put(dir+'/proof.txt','proof');const s={version:1,cohort:['a'],parents:[{directory:'runs/parent'}],inputHashes:{[dir+'/proof.txt']:sha('proof')},sources:{},states:{a:{target:{providerInterpretations:[{url:'https://provider.example/',classification:'UNRESOLVED',blockers:[],needsGeo:false,runDirectory:dir}]}}},quarantine:[]};return {...f,s,dir};}
test('nested interpretation runDirectory resolves only fingerprinted child files',t=>{const f=snapshotFixture(t),a=adaptSnapshot(f.root,f.s),r=a.states.a.target.providerInterpretations[0];assert.equal(r.runDirectory,undefined);assert.deepEqual(r.childRunReferences,[{path:f.dir+'/proof.txt',sha256:sha('proof')}]);});
test('unfingerprinted additions to a child interpretation fail closed',t=>{const f=snapshotFixture(t);f.put(f.dir+'/new.txt','new');assert.throws(()=>adaptSnapshot(f.root,f.s),/NOT_FINGERPRINTED/);});
test('nested child cannot escape root or parent namespace',t=>{const f=snapshotFixture(t);f.s.states.a.target.providerInterpretations[0].runDirectory='../outside';assert.throws(()=>adaptSnapshot(f.root,f.s),/ESCAPE/);});
test('child symlink cycle is not traversed',t=>{const f=snapshotFixture(t);fs.symlinkSync('.',f.root+'/'+f.dir+'/cycle');assert.throws(()=>adaptSnapshot(f.root,f.s),/SYMLINK/);});
test('unknown runDirectory outside providerInterpretations is not whitelisted',t=>{const f=fixture(t);f.put('state.json',{runDirectory:'runs/parent'});assert(closure(f.root,[{path:'state.json',format:'JSON',classification:'PERMANENT_CANONICAL'}]).errors.includes('STORAGE_UNKNOWN_PATH_FIELD:runDirectory'));});
test('absent seal is reported as absent, not a different hash algorithm or an exception',t=>{const f=fixture(t),payload={version:1,cohort:['a'],inputHashes:{}};f.put('snapshot.json',payload);const bytes=fs.readFileSync(f.root+'/snapshot.json'),a=inspectLegacySnapshot(f.root,'snapshot.json');assert.equal(a.storedSnapshotHash,null);assert.equal(a.sealPresent,false);assert.equal(a.recomputedSnapshotHash,sha(JSON.stringify(payload)));assert.equal(a.exceptionAuthorized,false);assert.throws(()=>certifyLegacyBoundary({root:f.root,destination:path.join(os.tmpdir(),'should-not-publish-receipt.json'),snapshots:['snapshot.json'],cohort:['a'],baseline:['netflix'],createdAt:'2026-09-22',versions:{engine:'fixture',policy:'legacy',schema:1}}),/SEAL_MISSING/);assert.deepEqual(fs.readFileSync(f.root+'/snapshot.json'),bytes);});
