import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {adaptDocument} from './schema-adapters.mjs';
import {closure} from './references.mjs';
import {sha} from './core.mjs';
const stages=['IDENTITY_SUBSCRIPTION','MARKETS','LOGIN','MANAGEMENT','CANCELLATION','PRICING','VALIDATION'];
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'genesis-references-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const put=(p,v)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,JSON.stringify(v));};return {root,put};}
function checkpoint(t){const f=fixture(t),v={version:1,fingerprint:'a'.repeat(64),requests:0,searches:0,reads:0,services:{aaa:{id:'aaa',status:'UNRESOLVED',stages:Object.fromEntries(stages.map(s=>[s,{status:'UNRESOLVED',artifact:`services/aaa/${s}.json`}]))}}};f.put('run/checkpoint.json',v);f.put('run/run-manifest.json',{version:1,fingerprint:v.fingerprint,cohort:['aaa'],stages});for(const s of stages)f.put(`run/services/aaa/${s}.json`,{status:'UNRESOLVED'});return {...f,v};}
test('controller checkpoint resolves every stage against owning run and preserves bytes',t=>{const f=checkpoint(t),before=fs.readFileSync(f.root+'/run/checkpoint.json');const r=closure(f.root,[{path:'run/checkpoint.json',format:'JSON',classification:'RESUME_CRITICAL'}]);assert(r.complete,JSON.stringify(r.errors));assert.equal(r.entries.length,9);assert.deepEqual(fs.readFileSync(f.root+'/run/checkpoint.json'),before);});
for(const value of ['../escape.json','/tmp/escape.json','services/other/LOGIN.json'])test('checkpoint rejects substituted artifact '+value,t=>{const f=checkpoint(t);f.v.services.aaa.stages.LOGIN.artifact=value;assert.throws(()=>adaptDocument(f.root,f.v,'run/checkpoint.json'),/ARTIFACT_SCOPE/);});
test('checkpoint rejects manifest identity mismatch',t=>{const f=checkpoint(t);f.v.fingerprint='b'.repeat(64);assert.throws(()=>adaptDocument(f.root,f.v,'run/checkpoint.json'),/CHECKPOINT_SCHEMA/);});
test('unknown path fields remain errors and arbitrary services paths are not reinterpreted',t=>{const f=fixture(t);f.put('run/unknown.json',{artifact:'services/aaa/LOGIN.json'});f.put('run/services/aaa/LOGIN.json',{});assert(!closure(f.root,[{path:'run/unknown.json',format:'JSON',classification:'RESUME_CRITICAL'}]).complete);});
test('versioned verification DOM locator preserves filesystem evidence references',t=>{const f=fixture(t),v={version:'V2_FIELD_VERIFICATION_V1',quote:{path:'$/html[1]/body[2]'},source:{path:'run/evidence.json'}};const a=adaptDocument(f.root,v,'run/verification.json');assert.equal(a.value.quote.domLocator,v.quote.path);assert.equal(a.value.source.path,v.source.path);});
test('journal validates original seal and inline body before removing redundant body locator',t=>{const f=fixture(t),p={version:'MARKET_RUN_STORE_V1',sequence:1,previous:null,type:'V2_ACQUISITION_RESULT',payload:{result:{attempts:[{page:{bodyFile:'bodies/'+sha('body')+'.txt',bodyHash:sha('body'),rawSource:{text:'body'}}}]}}};const v={...p,hash:sha(JSON.stringify(p))};assert.equal(adaptDocument(f.root,v,'run/journal/record-00000001.json').value.payload.result.attempts[0].page.bodyFile,undefined);v.payload.result.attempts[0].page.rawSource.text='changed';assert.throws(()=>adaptDocument(f.root,v,'run/journal/record-00000001.json'),/JOURNAL_HASH/);});
test('monthly input hash references remain portable and escape is rejected',t=>{const f=fixture(t),v={version:'EXPERIMENTAL_MONTHLY_DOMAIN_V1',method:'READ_ALL_PERSISTED_CANDIDATES_AND_HASH_VERIFIED_OWNING_SOURCE_STRUCTURE_NO_REEXTRACTION',inputDirectory:'/original/repo/run/input',corpusDirectory:'/original/repo/run/corpus',inputHashes:{'facts.json':sha('[]')},sourceIndexHash:sha('{}')};const a=adaptDocument(f.root,v,'run/monthly/manifest.json');assert.equal(a.references[0].path,'run/input/facts.json');assert.equal(a.references[0].sha256,sha('[]'));v.inputDirectory='/wrong/run/../input';assert.throws(()=>adaptDocument(f.root,v,'run/monthly/manifest.json'),/SCOPE/);});
test('robots rule URL path is not filesystem authority',t=>{const f=fixture(t);const v={robotsUrl:'https://provider.example/robots.txt',rule:{directive:'disallow',path:'/'}};assert.equal(adaptDocument(f.root,v,'run/pages.json').value.rule.robotsPattern,'/');assert.equal(adaptDocument(f.root,{path:'/'},'run/pages.json').value.path,'/');});
test('native adaptive body lookup uses exact target acquisition directory and hash',t=>{const f=fixture(t),body='body',hash=sha(JSON.stringify(body));f.put('run/targets/a/open-web-discovery/bodies/'+hash+'.txt',body);const s={version:1,serviceOrder:['a'],initialIds:['a'],services:{a:{}},targets:{a:{id:'a',reads:[{bodyHash:hash,bodyFile:'bodies/'+hash+'.txt'}]}}};assert.equal(adaptDocument(f.root,s,'run/adaptive-state.json').value.targets.a.reads[0].bodyReference.sha256,hash);s.targets.a.reads[0].bodyHash='a'.repeat(64);assert.throws(()=>adaptDocument(f.root,s,'run/adaptive-state.json'),/SCOPE/);});
test('prior interpretation cannot escape its original acquisition subtree',t=>{const f=fixture(t),s={version:1,targets:[{providerInterpretations:[{url:'https://example.com',blockers:[],runDirectory:'other/direct-acquisitions/direct-x'}]}],usage:{},cache:{}};assert.throws(()=>adaptDocument(f.root,s,'run/open-web-discovery/state.json'),/SCOPE/);});
test('reconciliation service roots are exact parent bootstrap scopes',t=>{const f=fixture(t),s={cohort:['a'],reconciliation:{schemaVersion:1,mode:'OFFLINE_REPLAY_ONLY',parentDirectory:'parent',services:['a'],sources:{a:'parent/bootstrap/a'}}};assert.equal(adaptDocument(f.root,s,'run/lineage.json').value.reconciliation.sources[0].directory,'parent/bootstrap/a');s.reconciliation.sources.a='parent/bootstrap/b';assert.throws(()=>adaptDocument(f.root,s,'run/lineage.json'),/SCOPE/);});
test('provider analysis attributes remain structural locators including data attributes',t=>{const f=fixture(t),v={version:1,bodyHash:'a'.repeat(64),records:[{pattern:'EXACT_SELF_ALTERNATE_AND_CANONICAL_COUNTRY_ROUTE',scopePaths:['$'],fields:[{path:'$/html[1]/a[2]/@data-location',value:'region'}]}],diagnostics:[]};assert.equal(adaptDocument(f.root,v,'run/source.json').value.records[0].fields[0].domLocator,'$/html[1]/a[2]/@data-location');});
test('standalone quarantine decision preserves source hash and rejection',t=>{const f=fixture(t),v={status:'REJECTED_INVALID_PRICE_INTERPRETATION',source:'run/adaptive-state.json',sourceHash:'a'.repeat(64),originalVerified:{version:'V2_FIELD_VERIFICATION_V1'}};const a=adaptDocument(f.root,v,'run/projection.json').value;assert.equal(a.status,v.status);assert.equal(a.sourceReference.sha256,v.sourceHash);});
test('genesis archival lock requires independently sealed terminal state and never changes normal continuation policy',t=>{const f=fixture(t);const objects={'run/summary.json':{executionComplete:true,additionalRequests:0},'run/catalog/adaptive-state.json':{complete:true,pending:null}};for(const [p,v]of Object.entries(objects))f.put(p,v);fs.writeFileSync(f.root+'/run/network.jsonl','');fs.writeFileSync(f.root+'/run/catalog/adaptive.lock','12345');const hashes=Object.fromEntries([...Object.keys(objects),'run/network.jsonl','run/catalog/adaptive.lock'].map(p=>[p,sha(fs.readFileSync(f.root+'/'+p))]));const p={version:1,cohort:['a'],parents:[{directory:'run',requests:0}],inputHashes:hashes};f.put('snapshot.json',{...p,snapshotHash:sha(JSON.stringify(p))});const roots=[{path:'snapshot.json',format:'SNAPSHOT',classification:'PERMANENT_HISTORY'}];assert(closure(f.root,roots).errors.includes('STORAGE_LOCK_REFERENCE_UNSAFE'));const a=closure(f.root,roots,{genesisArchive:true});assert(a.complete,JSON.stringify(a.errors));assert.equal(a.entries.find(e=>e.path.endsWith('.lock')).classification,'PERMANENT_HISTORY');f.put('run/catalog/adaptive-state.json',{complete:false,pending:{}});assert(!closure(f.root,roots,{genesisArchive:true}).complete);});
test('journal reference hashes bind canonical record payload, not pretty-printed file bytes',t=>{const f=fixture(t),p={version:'MARKET_RUN_STORE_V1',sequence:1,previous:null,type:'TEST',payload:{answer:'value'}},record={...p,hash:sha(JSON.stringify(p))};f.put('run/journal/record-00000001.json',record);f.put('reference.json',{path:'run/journal/record-00000001.json',hash:record.hash,sequence:1,pointer:'/answer'});const root=[{path:'reference.json',format:'JSON',classification:'REFERENCED_EVIDENCE'}];assert(closure(f.root,root).complete);f.put('reference.json',{path:'run/journal/record-00000001.json',hash:record.hash,sequence:1,pointer:'/missing'});assert(closure(f.root,root).errors.includes('STORAGE_JOURNAL_POINTER'));});
test('service result uses checkpoint run root, not the service subdirectory',t=>{const f=checkpoint(t),v={service:'aaa',productionPromoted:false,stages:f.v.services.aaa.stages};f.put('run/services/aaa/result.json',v);const a=adaptDocument(f.root,v,'run/services/aaa/result.json');assert.equal(a.value.stages.LOGIN.artifact,'run/services/aaa/LOGIN.json');assert.deepEqual(JSON.parse(fs.readFileSync(f.root+'/run/services/aaa/result.json')),v);});
test('historical READ operation body is owned by service directory and operation key is verified',t=>{const f=fixture(t),key='https://provider.example',p='run/services/a/operations/'+sha(JSON.stringify(['READ',key]))+'.json',v={kind:'READ',key,status:'COMPLETE',result:{bodyHash:'a'.repeat(64),bodyFile:'bodies/'+'a'.repeat(64)+'.txt'}};const a=adaptDocument(f.root,v,p);assert.equal(a.value.result.bodyReference.path,'run/services/a/bodies/'+'a'.repeat(64)+'.txt');v.key='changed';assert.throws(()=>adaptDocument(f.root,v,p),/SCHEMA/);});
test('provider workbook provenance exemption is restricted to exact decoded schema',t=>{const f=fixture(t),v={sheet:'Provider Homepage Candidates',source:'/original/input.xlsx',sha256:'a'.repeat(64),rows:Array.from({length:188},(_,i)=>({service_id:'service-'+i}))};assert(!('source'in adaptDocument(f.root,v,'input/provider-workbook-input.json').value));assert.equal(adaptDocument(f.root,v,'input/unknown.json').value.source,v.source);v.rows.pop();assert.throws(()=>adaptDocument(f.root,v,'input/provider-workbook-input.json'),/SCHEMA/);});
