import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {sha,digest,canonical,sealed} from './core.mjs';
import {prepareGenesisStartup,verifyGenesisPlacement,deploymentContract,restoreGenesisFiles,registerGenesisOverlay,ensureGenesisRepositoryInputs} from './genesis-deployment.mjs';
function fixture(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'genesis-deployment-')),source=base+'/export',dest=base+'/deployed';fs.mkdirSync(source);fs.mkdirSync(dest);t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const input='.savlivo/v2-operations-inputs/genesis-test.json',genesis='.savlivo/research-v2/storage/genesis/test.json',data='docs/catalog/global-47/research-v2/v15-discovery-20260921/base-targets.json',code='packages/contracts/src/catalog.ts';const put=(root,p,b)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,b);};put(source,data,'{"frozen":188,"baselineExcluded":275}');put(source,code,'export const catalog = [];');const entry=p=>{const b=fs.readFileSync(source+'/'+p);return {path:p,bytes:b.length,sha256:sha(b)};};const inputBytes=canonical({version:1,productionGenesis:genesis});put(source,input,inputBytes);const payload={schema:'PRODUCTION_GENESIS_V1',lineage:{kind:'NEW_PRODUCTION_GENESIS',continuesHistoricalSnapshot:false},lifecycle:{originalInput:'historical-input.json',productionInput:input,productionInputHash:sha(inputBytes)},protectedReferences:sealed({schema:'V2_FINALIZED_REFERENCES_V1',boundaryKind:'PRODUCTION_GENESIS_V1',complete:true,unknownRequiredDependencies:0,entries:[entry(data),entry(code)]}),excludedUntrustedHistoricalArtifacts:[{path:'unsealed.json',sha256:'f'.repeat(64)}]};const g={...payload,genesisHash:digest(payload)};put(source,genesis,canonical(g));const manifest=sealed({schema:'PRODUCTION_GENESIS_EXPORT_V1',genesis,genesisHash:g.genesisHash,productionInput:input,files:[entry(data),entry(code),entry(input),entry(genesis)]});put(source,'genesis-export.json',canonical(manifest));put(dest,code,fs.readFileSync(source+'/'+code));return {source,dest,input,genesis,data,code,g,manifest,put};}
test('exact missing repository input is restored and persisted for fresh deployments',t=>{const f=fixture(t);for(const p of [f.input,f.genesis])f.put(f.dest,p,fs.readFileSync(f.source+'/'+p));assert.throws(()=>ensureGenesisRepositoryInputs(f.dest,f.input),/genesis-register-overlay/);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input).status,'READY');fs.renameSync(f.dest+'/'+f.data,f.dest+'/'+f.data+'.test-backup');assert.throws(()=>ensureGenesisRepositoryInputs(f.dest,f.input,{repair:false}),/REPOSITORY_INPUTS_MISSING/);assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input).restored,1);assert.deepEqual(fs.readFileSync(f.dest+'/'+f.data),fs.readFileSync(f.source+'/'+f.data));assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input).restored,0);});
test('existing manual overlay registers idempotently without rewriting evidence',t=>{const f=fixture(t);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);const bytes=fs.readFileSync(f.dest+'/'+f.genesis);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);assert.deepEqual(fs.readFileSync(f.dest+'/'+f.genesis),bytes);});
test('conflicts fail before any missing destination is copied',t=>{const f=fixture(t);f.put(f.dest,f.data,'wrong');assert.throws(()=>restoreGenesisFiles(f.source,f.dest,f.g.genesisHash),/HASH_CONFLICT/);assert(!fs.existsSync(f.dest+'/'+f.genesis));});
test('code must be deployed by Git and cannot be silently replaced',t=>{const f=fixture(t);fs.renameSync(f.dest+'/'+f.code,f.dest+'/'+f.code+'.backup');assert.throws(()=>restoreGenesisFiles(f.source,f.dest,f.g.genesisHash),/MATCHING_DEPLOYED_CODE_REQUIRED/);assert(!fs.existsSync(f.dest+'/'+f.data));});
test('manifest must equal the sealed protected closure; extra paths cannot be injected',t=>{const f=fixture(t),{contentHash,...m}=f.manifest;m.files.push({path:'services/api/src/server.ts',bytes:0,sha256:sha('')});assert.throws(()=>deploymentContract(f.source,sealed(m),f.g.genesisHash),/MANIFEST_CLOSURE/);});
test('tampered persistent overlay blocks startup, with no alternate source fallback',t=>{const f=fixture(t);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);const r=registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);f.put(f.dest,r.bundle+'/repository/'+f.data,'bad');assert.throws(()=>ensureGenesisRepositoryInputs(f.dest,f.input),/HASH_CONFLICT/);});
test('symlink escape and wrong expected genesis fail closed',t=>{const f=fixture(t);assert.throws(()=>restoreGenesisFiles(f.source,f.dest,'a'.repeat(64)),/EXPECTED_GENESIS_HASH/);fs.renameSync(f.dest+'/packages',f.dest+'/packages-backup');fs.symlinkSync(f.source+'/packages',f.dest+'/packages');assert.throws(()=>restoreGenesisFiles(f.source,f.dest,f.g.genesisHash),/STORAGE_SYMLINK/);});
test('startup without configured genesis does not initialize research or storage',t=>{const f=fixture(t);assert.deepEqual(ensureGenesisRepositoryInputs(f.dest,null),{status:'NOT_CONFIGURED',researchStarted:false});assert(!fs.existsSync(f.dest+'/.savlivo'));});

test('register preflight names a missing repository dependency before lifecycle validation',t=>{const f=fixture(t);for(const p of [f.input,f.genesis])f.put(f.dest,p,fs.readFileSync(f.source+'/'+p));assert.throws(()=>verifyGenesisPlacement(f.dest,f.manifest,f.g.genesisHash),/GENESIS_DEPLOYMENT_MISSING_OR_UNSAFE_FILE:docs\/catalog.*base-targets.json.*genesis-restore/);assert(!fs.existsSync(f.dest+'/.savlivo/research-v2/storage/deployment'));});

test('startup rejects registered Genesis original input without silently selecting or repairing',t=>{const f=fixture(t);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);f.put(f.dest,'historical-input.json',JSON.stringify({version:1,runsRoot:'historical-runs'}));fs.renameSync(f.dest+'/'+f.data,f.dest+'/'+f.data+'.backup');assert.throws(()=>prepareGenesisStartup(f.dest,'historical-input.json'),/LIFECYCLE_INPUT_REQUIRES_GENESIS:set V2_OPERATIONS_LIFECYCLE_INPUT=/);assert(!fs.existsSync(f.dest+'/'+f.data));assert.equal(prepareGenesisStartup(f.dest,f.input).restored,1);assert.equal(prepareGenesisStartup(f.dest,f.input).restored,0);});
test('non-Genesis configuration without a corresponding registered Genesis remains supported',t=>{const f=fixture(t);f.put(f.dest,'legacy.json','{"version":1}');assert.equal(prepareGenesisStartup(f.dest,'legacy.json').status,'NOT_GENESIS');});
test('actual production launcher rejects stale input then repairs before either offline fixture child starts',async t=>{
 const {spawn,spawnSync}=await import('node:child_process');const {fileURLToPath}=await import('node:url');const f=fixture(t);
 restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);
 f.put(f.dest,'historical-input.json','{"version":1}');fs.renameSync(f.dest+'/'+f.data,f.dest+'/'+f.data+'.backup');
 for(const [from,to]of [['../../../scripts/production-runtime.mjs','services/api/scripts/production-runtime.mjs'],['./genesis-deployment.mjs','services/api/src/research-v2/storage/genesis-deployment.mjs'],['./core.mjs','services/api/src/research-v2/storage/core.mjs'],['../capabilities/config.mjs','services/api/src/research-v2/capabilities/config.mjs']])f.put(f.dest,to,fs.readFileSync(new URL(from,import.meta.url)));
 fs.symlinkSync(fileURLToPath(new URL('../../../../../node_modules',import.meta.url)),f.dest+'/node_modules','dir');
 const children=['services/api/dist/services/api/src/server.js','services/api/src/v2-operations/worker.mjs'];
 for(const p of children)f.put(f.dest,p,`import fs from 'node:fs';if(!fs.existsSync(${JSON.stringify(f.data)}))throw Error('REPAIR_ORDER');if(process.env.ANALYTICS_V2_RUN_CONTROL_ENABLED!=='false'||process.env.ANALYTICS_V2_SCHEDULING_ENABLED!=='false')throw Error('GATES');fs.writeFileSync(${JSON.stringify(p+'.started')},'offline');process.on('SIGTERM',()=>process.exit(0));process.on('disconnect',()=>process.exit(0));setInterval(()=>{},1000);`);
 f.put(f.dest,'services/api/package.json','{"type":"module"}');
 const env={...process.env,TSX_DISABLE_CACHE:'1',V2_OPERATIONS_REPOSITORY_ROOT:fs.realpathSync(f.dest),V2_OPERATIONS_LIFECYCLE_INPUT:'historical-input.json',ANALYTICS_V2_OPERATIONS_ENABLED:'true',ANALYTICS_V2_RUN_CONTROL_ENABLED:'false',ANALYTICS_V2_SCHEDULING_ENABLED:'false'};
 const bad=spawnSync(process.execPath,['services/api/scripts/production-runtime.mjs'],{cwd:f.dest,env,encoding:'utf8'});assert.equal(bad.status,1);assert.match(bad.stderr,/LIFECYCLE_INPUT_REQUIRES_GENESIS/);assert(!fs.existsSync(f.dest+'/'+f.data));assert(!bad.stdout.includes('CHILD_STARTED'));
 const child=spawn(process.execPath,['services/api/scripts/production-runtime.mjs'],{cwd:f.dest,env:{...env,V2_OPERATIONS_LIFECYCLE_INPUT:f.input},stdio:['ignore','pipe','pipe']});let output='';child.stdout.on('data',b=>output+=b);child.stderr.on('data',b=>output+=b);const exit=new Promise(resolve=>child.once('exit',resolve));
 t.after(()=>{if(child.exitCode===null)child.kill('SIGTERM');});
 const deadline=Date.now()+10000;while(!children.every(p=>fs.existsSync(f.dest+'/'+p+'.started'))&&Date.now()<deadline&&child.exitCode===null)await new Promise(r=>setTimeout(r,25));
 assert(children.every(p=>fs.existsSync(f.dest+'/'+p+'.started')),output);assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input,{repair:false}).status,'READY');assert(output.indexOf('GENESIS_DEPLOYMENT_PREFLIGHT')<output.indexOf('CHILD_STARTED'));child.kill('SIGTERM');assert.equal(await exit,0,output);
});

test('execution selection cannot change Genesis trust inputs or widen research scopes',async t=>{
 const {validateGenesisExecutionSelection}=await import('./genesis-deployment.mjs');const f=fixture(t);
 const original={version:1,productionGenesis:f.genesis,cohortManifest:'frozen.json',runsRoot:'.savlivo/research-v2/production',researchScopes:'scopes.json',universe:'universe.json'};
 f.put(f.dest,f.input,JSON.stringify(original));f.put(f.dest,'scopes.json',JSON.stringify({researchMarkets:{film:['NO','SE']}}));f.put(f.dest,'universe.json',JSON.stringify({new_include:[{slug:'film',markets:['NO','SE']}],research:[]}));
 const capabilities={direct:true,tavily:true,decodo:false,browser:false,groq:false};const g={lifecycle:{productionInput:f.input},cohort:['film']};
 const check=c=>validateGenesisExecutionSelection(f.dest,'.savlivo/v2-operations-inputs/'+sha(JSON.stringify(c))+'.json',c,g);
 const c={...original,capabilities,executionServices:['film']};check(c);
 for(const patch of [{runsRoot:'.savlivo/research-v2/history'},{cohortManifest:'other.json'},{productionGenesis:'other.json'},{executionServices:['netflix']},{capabilities:{...capabilities,unknown:true}}])assert.throws(()=>check({...c,...patch}));
 const scope={researchMarkets:{film:['NO']}},file='.savlivo/v2-operations-inputs/'+sha(JSON.stringify(scope))+'.json';f.put(f.dest,file,JSON.stringify(scope));check({...c,researchScopes:file});
 f.put(f.dest,file,JSON.stringify({researchMarkets:{film:['DE']}}));assert.throws(()=>check({...c,researchScopes:file}),/EXECUTION_SCOPE_HASH/);
 const wrong={researchMarkets:{film:['DE']}},wrongFile='.savlivo/v2-operations-inputs/'+sha(JSON.stringify(wrong))+'.json';f.put(f.dest,wrongFile,JSON.stringify(wrong));assert.throws(()=>check({...c,researchScopes:wrongFile}),/EXECUTION_SCOPE_EXPANSION/);
});

test('bounded startup child restores authenticated inputs before supervision and conflicts remain fatal',async t=>{
 const {prepareGenesisStartupIsolated}=await import('../../../scripts/production-runtime.mjs');const f=fixture(t);
 restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);
 fs.renameSync(f.dest+'/'+f.data,f.dest+'/'+f.data+'.backup');
 const r=prepareGenesisStartupIsolated(f.dest,f.input);assert.equal(r.status,'READY');assert.equal(r.restored,1);assert.equal(r.researchStarted,false);
 assert.deepEqual(fs.readFileSync(f.dest+'/'+f.data),fs.readFileSync(f.source+'/'+f.data));assert.equal(prepareGenesisStartupIsolated(f.dest,f.input).restored,0);
 f.put(f.dest,f.data,'conflict');assert.throws(()=>prepareGenesisStartupIsolated(f.dest,f.input),/HASH_CONFLICT/);
});
