import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {sha,digest,canonical,sealed} from './core.mjs';
import {verifyGenesisPlacement,deploymentContract,restoreGenesisFiles,registerGenesisOverlay,ensureGenesisRepositoryInputs} from './genesis-deployment.mjs';
function fixture(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'genesis-deployment-')),source=base+'/export',dest=base+'/deployed';fs.mkdirSync(source);fs.mkdirSync(dest);t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const input='.savlivo/v2-operations-inputs/genesis-test.json',genesis='.savlivo/research-v2/storage/genesis/test.json',data='docs/catalog/global-47/research-v2/v15-discovery-20260921/base-targets.json',code='packages/contracts/src/catalog.ts';const put=(root,p,b)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,b);};put(source,data,'{"frozen":188,"baselineExcluded":275}');put(source,code,'export const catalog = [];');const entry=p=>{const b=fs.readFileSync(source+'/'+p);return {path:p,bytes:b.length,sha256:sha(b)};};const inputBytes=canonical({version:1,productionGenesis:genesis});put(source,input,inputBytes);const payload={schema:'PRODUCTION_GENESIS_V1',lineage:{kind:'NEW_PRODUCTION_GENESIS',continuesHistoricalSnapshot:false},lifecycle:{productionInput:input,productionInputHash:sha(inputBytes)},protectedReferences:sealed({schema:'V2_FINALIZED_REFERENCES_V1',boundaryKind:'PRODUCTION_GENESIS_V1',complete:true,unknownRequiredDependencies:0,entries:[entry(data),entry(code)]}),excludedUntrustedHistoricalArtifacts:[{path:'unsealed.json',sha256:'f'.repeat(64)}]};const g={...payload,genesisHash:digest(payload)};put(source,genesis,canonical(g));const manifest=sealed({schema:'PRODUCTION_GENESIS_EXPORT_V1',genesis,genesisHash:g.genesisHash,productionInput:input,files:[entry(data),entry(code),entry(input),entry(genesis)]});put(source,'genesis-export.json',canonical(manifest));put(dest,code,fs.readFileSync(source+'/'+code));return {source,dest,input,genesis,data,code,g,manifest,put};}
test('exact missing repository input is restored and persisted for fresh deployments',t=>{const f=fixture(t);for(const p of [f.input,f.genesis])f.put(f.dest,p,fs.readFileSync(f.source+'/'+p));assert.throws(()=>ensureGenesisRepositoryInputs(f.dest,f.input),/genesis-register-overlay/);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input).status,'READY');fs.renameSync(f.dest+'/'+f.data,f.dest+'/'+f.data+'.test-backup');assert.throws(()=>ensureGenesisRepositoryInputs(f.dest,f.input,{repair:false}),/REPOSITORY_INPUTS_MISSING/);assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input).restored,1);assert.deepEqual(fs.readFileSync(f.dest+'/'+f.data),fs.readFileSync(f.source+'/'+f.data));assert.equal(ensureGenesisRepositoryInputs(f.dest,f.input).restored,0);});
test('existing manual overlay registers idempotently without rewriting evidence',t=>{const f=fixture(t);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);const bytes=fs.readFileSync(f.dest+'/'+f.genesis);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);assert.deepEqual(fs.readFileSync(f.dest+'/'+f.genesis),bytes);});
test('conflicts fail before any missing destination is copied',t=>{const f=fixture(t);f.put(f.dest,f.data,'wrong');assert.throws(()=>restoreGenesisFiles(f.source,f.dest,f.g.genesisHash),/HASH_CONFLICT/);assert(!fs.existsSync(f.dest+'/'+f.genesis));});
test('code must be deployed by Git and cannot be silently replaced',t=>{const f=fixture(t);fs.renameSync(f.dest+'/'+f.code,f.dest+'/'+f.code+'.backup');assert.throws(()=>restoreGenesisFiles(f.source,f.dest,f.g.genesisHash),/MATCHING_DEPLOYED_CODE_REQUIRED/);assert(!fs.existsSync(f.dest+'/'+f.data));});
test('manifest must equal the sealed protected closure; extra paths cannot be injected',t=>{const f=fixture(t),{contentHash,...m}=f.manifest;m.files.push({path:'services/api/src/server.ts',bytes:0,sha256:sha('')});assert.throws(()=>deploymentContract(f.source,sealed(m),f.g.genesisHash),/MANIFEST_CLOSURE/);});
test('tampered persistent overlay blocks startup, with no alternate source fallback',t=>{const f=fixture(t);restoreGenesisFiles(f.source,f.dest,f.g.genesisHash);const r=registerGenesisOverlay(f.dest,f.manifest,f.g.genesisHash);f.put(f.dest,r.bundle+'/repository/'+f.data,'bad');assert.throws(()=>ensureGenesisRepositoryInputs(f.dest,f.input),/HASH_CONFLICT/);});
test('symlink escape and wrong expected genesis fail closed',t=>{const f=fixture(t);assert.throws(()=>restoreGenesisFiles(f.source,f.dest,'a'.repeat(64)),/EXPECTED_GENESIS_HASH/);fs.renameSync(f.dest+'/packages',f.dest+'/packages-backup');fs.symlinkSync(f.source+'/packages',f.dest+'/packages');assert.throws(()=>restoreGenesisFiles(f.source,f.dest,f.g.genesisHash),/STORAGE_SYMLINK/);});
test('startup without configured genesis does not initialize research or storage',t=>{const f=fixture(t);assert.deepEqual(ensureGenesisRepositoryInputs(f.dest,null),{status:'NOT_CONFIGURED',researchStarted:false});assert(!fs.existsSync(f.dest+'/.savlivo'));});

test('register preflight names a missing repository dependency before lifecycle validation',t=>{const f=fixture(t);for(const p of [f.input,f.genesis])f.put(f.dest,p,fs.readFileSync(f.source+'/'+p));assert.throws(()=>verifyGenesisPlacement(f.dest,f.manifest,f.g.genesisHash),/GENESIS_DEPLOYMENT_MISSING_OR_UNSAFE_FILE:docs\/catalog.*base-targets.json.*genesis-restore/);assert(!fs.existsSync(f.dest+'/.savlivo/research-v2/storage/deployment'));});
