import {claimLeases,releaseLeases} from '../../v2-operations/leases.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {canonical,digest,sha,safe,relative,stableBytes,immutable,read,sealed,verifySeal} from './core.mjs';
const nullable=v=>v===undefined?null:v;
const state=v=>typeof v==='string'?v:v?.status??null;
export function accounting(events,capabilityEvents=null){
 const names=['DIRECT','TAVILY','DECODO','BROWSER','GROQ'];const counts=Object.fromEntries(names.map(n=>[n,events===null?null:0]));let unknown=events===null?null:0;
 for(const e of events??[]){const route=e.route??e.kind;const n=['DISCOVERY','TAVILY'].includes(route)?'TAVILY':['DIRECT','ROBOTS','HTTP','REDIRECT','page','robots'].includes(route)?'DIRECT':names.includes(route)?route:null;if(n)counts[n]++;else unknown++;}
 const intents=capabilityEvents?.filter(e=>e.type==='INTENT'),results=capabilityEvents?.filter(e=>e.type==='RESULT');
 return {requests:events?.length??null,byRoute:counts,unknownRouteRequests:unknown,capabilityReservations:intents?.length??null,uncertainReservations:intents?.filter(i=>!results.some(r=>r.key===i.key)).length??null,browserAttempts:intents?.filter(i=>i.kind==='browser').length??null,groqCalls:intents?.filter(i=>i.kind==='groq').length??null,browserResources:results&&results.filter(r=>r.kind==='browser').every(r=>Number.isInteger(r.result?.execution?.used?.requests))?results.filter(r=>r.kind==='browser').reduce((n,r)=>n+r.result.execution.used.requests,0):null,failures:events?.some(e=>'failure' in e)?events.filter(e=>e.failure).length:null};
}
function projection(s,before){return {schema:'V2_ANALYTICS_SERVICE_V1',serviceId:s.service_id,finalStatus:nullable(s.finalStatus),researchComplete:nullable(s.researchComplete),authority:state(s.providerAuthority),beforeQualification:before?state(before.subscriptionQualification):null,afterQualification:state(s.subscriptionQualification),identity:state(s.identity),markets:nullable(s.markets?.researched),verifiedMarketCount:s.markets?.verified?.length??null,login:state(s.login),management:state(s.management),cancellation:state(s.cancellation),pricing:Array.isArray(s.pricing)?s.pricing.map(p=>({market:p.market,status:p.status,confidence:p.confidence??null,quarantined:p.quarantine?.length??null,observations:p.observations?.map(o=>({amount:nullable(o.amount??o.price?.amount),currency:nullable(o.currency??o.price?.currency),cadence:nullable(o.cadence??o.interval),sourceHash:nullable(o.sourceHash),url:nullable(o.url)}))??null})):null,unresolvedReasons:nullable(s.unresolvedReasons),humanReview:nullable(s.humanReview),evidenceCount:s.evidence?.length??null,evidenceFreshness:nullable(s.evidenceFreshness),evidenceAdded:nullable(s.evidenceAdded),evidenceReused:nullable(s.evidenceReused),providerChanges:nullable(s.providerChanges),urlChanges:nullable(s.urlChanges),priceChanges:nullable(s.priceChanges),requests:nullable(s.requests),stopReason:nullable(s.stopReason),failureCategory:nullable(s.failureCategory),before:before?{authority:state(before.providerAuthority),login:state(before.login),management:state(before.management),cancellation:state(before.cancellation),pricing:projection({...before,pricing:before.pricing},null).pricing}:null};}
function jsonl(file){return fs.existsSync(file)?String(stableBytes(file)).split('\n').filter(Boolean).map(JSON.parse):null;}
export function publishHistory(root,{directory,store='.savlivo/research-v2/storage',receipt=null,before=null}){
 const get=name=>read(safe(root,directory+'/'+name)),summary=get('summary.json'),final=get('final-dispositions.json'),lineage=get('lineage.json');
 if(summary.executionComplete!==true||final.executionComplete!==true)throw Error('STORAGE_NOT_FINAL');
 const id=digest(directory),dest=`${store}/history/${id}`,rows=final.services.map(s=>projection(s,before?.find(b=>b.service_id===s.service_id))).sort((a,b)=>a.serviceId.localeCompare(b.serviceId));
 const parents=[...(lineage.lifecycle?.parents??[])].reverse();
 const previous=new Map();for(const parent of parents){const file=safe(root,`${store}/history/${digest(parent.directory)}/summary.json`);if(!fs.existsSync(file))continue;const p=verifySeal(read(file),'V2_ANALYTICS_RUN_V1'),bytes=stableBytes(safe(root,p.observations.path));if(sha(bytes)!==p.observations.sha256)throw Error('STORAGE_HISTORY_HASH');for(const row of String(bytes).split('\n').filter(Boolean).map(JSON.parse))if(!previous.has(row.serviceId))previous.set(row.serviceId,row);}
 for(const row of rows){const old=previous.get(row.serviceId);if(!old)continue;row.beforeQualification=old.afterQualification;row.before={authority:old.authority,login:old.login,management:old.management,cancellation:old.cancellation,pricing:old.pricing};if(row.priceChanges===null&&row.pricing!==null&&old.pricing!==null)row.priceChanges=digest(old.pricing)===digest(row.pricing)?[]:[{before:old.pricing,after:row.pricing}];}
 const observations=rows.map(canonical).join('\n')+'\n',counts=accounting(jsonl(safe(root,directory+'/network.jsonl')),jsonl(safe(root,directory+'/capability-ledger.jsonl')));
 const result=sealed({schema:'V2_ANALYTICS_RUN_V1',runId:directory,createdAt:summary.startedAt??lineage.createdAt??null,finishedAt:summary.finishedAt??null,durationMs:summary.durationMs??null,objective:'MATURE_LIFECYCLE',scope:lineage.cohort??null,capabilities:lineage.capabilities??lineage.lifecycle?.capabilities??null,executionComplete:true,researchComplete:summary.researchComplete??null,stopReason:summary.stopReason??null,versions:receipt?.versions??{engine:lineage.lifecycle?.codeHash??null,policy:null,schema:1},finalizationHash:receipt?.contentHash??null,sourceFinalHash:sha(stableBytes(safe(root,directory+'/final-dispositions.json'))),serviceCount:rows.length,dispositions:rows.reduce((v,r)=>(v[r.finalStatus??'UNKNOWN']=(v[r.finalStatus??'UNKNOWN']??0)+1,v),{}),accounting:counts,requestBudget:lineage.additionalRequestCeiling??null,historicalRequests:lineage.historicalRequests??null,parentRequests:lineage.parentRequests??null,observations:{path:dest+'/services.jsonl',sha256:sha(observations)}});
 immutable(safe(root,dest+'/services.jsonl'),observations);immutable(safe(root,dest+'/summary.json'),canonical(result));rebuildHistoryIndex(root,store);return result;
}
export function rebuildHistoryIndex(root,store='.savlivo/research-v2/storage'){
 const dir=safe(root,store+'/history');if(!fs.existsSync(dir))return {rows:[]};const held=claimLeases([safe(root,store+'/history-index.lock')]);try{const rows=[];
 for(const id of fs.readdirSync(dir).sort()){if(!/^[a-f0-9]{64}$/.test(id))continue;const file=safe(root,store+'/history/'+id+'/summary.json');if(!fs.existsSync(file))continue;const r=verifySeal(read(file),'V2_ANALYTICS_RUN_V1');if(sha(stableBytes(safe(root,r.observations.path)))!==r.observations.sha256)throw Error('STORAGE_HISTORY_HASH');rows.push(r);}
 const index=sealed({schema:'V2_ANALYTICS_INDEX_V1',rows});const file=safe(root,store+'/history-index-'+index.contentHash+'.json');immutable(file,canonical(index));
 // A pointer is rebuildable, never authoritative. Atomic replacement only of this new projection.
 const pointer=safe(root,store+'/history-index.json'),tmp=pointer+'.next-'+index.contentHash;immutable(tmp,canonical({schema:'V2_HISTORY_INDEX_POINTER_V1',path:relative(root,file),sha256:sha(stableBytes(file))}));fs.renameSync(tmp,pointer);return index;}finally{releaseLeases(held,process.pid);}
}
export function historyIndex(root,store='.savlivo/research-v2/storage'){
 try{const p=read(safe(root,store+'/history-index.json'));if(p.schema!=='V2_HISTORY_INDEX_POINTER_V1'||fs.statSync(safe(root,p.path)).size>16*1024**2||sha(stableBytes(safe(root,p.path)))!==p.sha256)throw Error();return verifySeal(read(safe(root,p.path)),'V2_ANALYTICS_INDEX_V1');}catch{return {rows:[],status:'UNAVAILABLE'};}
}
