import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {closure} from './references.mjs';import {sha} from './core.mjs';
import {certifyLegacyBoundary,revalidateLegacyBoundary} from './legacy-boundary.mjs';
import {scanEntries,streamingInventory,normalizeRoots,classifyAlias} from './stream-scan.mjs';
const ref=p=>({path:p,format:'JSON',classification:'PERMANENT_CANONICAL'});
function setup(t){const outer=fs.mkdtempSync(path.join(os.tmpdir(),'legacy-storage-')),root=outer+'/source';fs.mkdirSync(root);t.after(()=>fs.rmSync(outer,{recursive:true,force:true}));return {outer,root,put(p,v){fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,typeof v==='string'?v:JSON.stringify(v));}};}
function manifest(){return {version:1,authorityBootstrap:1,scope:'NEW_SERVICES_ONLY',expectedServices:1,serviceIds:['candidate'],inputHashes:{},outputHashes:{},controller:{version:1,entrypoint:'docs/catalog/global-47/research-v2/run-v15-full-v2.mjs',automaticAuthorityGrants:false,unknownEvidenceRemainsUnresolved:true,stages:['IDENTITY_SUBSCRIPTION','MARKETS','LOGIN','MANAGEMENT','CANCELLATION','PRICING','VALIDATION']}};}
test('real discovery contract treats controller entrypoint as code provenance only',t=>{const f=setup(t),m=manifest();f.put(m.controller.entrypoint,'throw Error("must not execute")');f.put('manifest.json',m);const r=closure(f.root,[ref('manifest.json')]);assert(r.complete,r.errors);assert.equal(r.entries.find(e=>e.format==='CODE').path,m.controller.entrypoint);});
test('entrypoint outside recognized versioned contract still fails closed',t=>{const f=setup(t);f.put('state.json',{entrypoint:'docs/run.json'});assert(!closure(f.root,[ref('state.json')]).complete);});
test('unknown field inside known contract still fails closed',t=>{const f=setup(t);f.put('state.json',{...manifest(),futureFile:'docs/missing.json'});assert(closure(f.root,[ref('state.json')]).errors.includes('STORAGE_UNKNOWN_PATH_FIELD:futureFile'));});
test('quarantine source has hash reference, DOM path is not a filesystem path',t=>{const f=setup(t);f.put('run/adaptive-state.json',{});f.put('q.json',{schemaVersion:1,scope:'EXACT_RETAINED_INTERPRETATIONS_ONLY',entries:[{source:'run/adaptive-state.json',sourceHash:sha('{}'),status:'REJECTED_INVALID_PRICE_INTERPRETATION',originalVerified:{version:'V2_FIELD_VERIFICATION_V1',quote:{path:'$/html[2]/body[3]'}}}]});assert(closure(f.root,[ref('q.json')]).complete);});
function certFixture(t,unknown=false){const f=setup(t);f.put('proof.txt','evidence');const p={version:1,cohort:['candidate'],inputHashes:{'proof.txt':sha('evidence')},...(unknown?{future:'missing.json'}:{})};f.put('snapshot.json',{...p,snapshotHash:sha(JSON.stringify(p))});return {...f,args:{root:f.root,destination:f.outer+'/receipt.json',snapshots:['snapshot.json'],cohort:['candidate'],baseline:['netflix'],createdAt:'2026-09-22',versions:{engine:'test',policy:'legacy',schema:1}}};}
test('legacy receipt certifies unchanged contract externally and revalidates',t=>{const f=certFixture(t),before=fs.readFileSync(f.root+'/snapshot.json');const r=certifyLegacyBoundary(f.args);assert(r.complete);assert.equal(revalidateLegacyBoundary(f.root,f.args.destination).contentHash,r.contentHash);assert.deepEqual(fs.readFileSync(f.root+'/snapshot.json'),before);assert.equal(certifyLegacyBoundary(f.args).contentHash,r.contentHash);f.put('proof.txt','changed');assert.throws(()=>revalidateLegacyBoundary(f.root,f.args.destination));});
test('incomplete legacy closure never publishes a complete receipt',t=>{const f=certFixture(t,true);assert.equal(certifyLegacyBoundary(f.args).complete,false);assert(!fs.existsSync(f.args.destination));});
test('legacy certificate cannot be written into source',t=>{const f=certFixture(t);assert.throws(()=>certifyLegacyBoundary({...f.args,destination:f.root+'/receipt.json'}),/EXTERNAL/);});
test('safe internal alias records target once without duplicate traversal',t=>{const f=setup(t);f.put('scope/real/file','x');fs.symlinkSync('real',f.root+'/scope/alias');const rows=[...scanEntries(f.root,['scope','scope/real'])];assert.equal(rows.filter(r=>r.kind==='file').length,1);assert.equal(rows.find(r=>r.kind==='alias').classification,'INTERNAL_SAFE_ALIAS');assert.deepEqual(normalizeRoots(['scope/real','scope','scope']),['scope']);});
test('escaping symlink remains unsafe and is never followed',t=>{const f=setup(t);fs.symlinkSync(os.tmpdir(),f.root+'/escape');const rows=[...scanEntries(f.root,['escape'])];assert.equal(rows.length,1);assert.equal(rows[0].classification,'PATH_ESCAPE');});
test('cycles are rejected including ancestor and link cycles',t=>{const f=setup(t);fs.mkdirSync(f.root+'/scope');fs.symlinkSync('.',f.root+'/scope/back');assert.equal(classifyAlias(f.root,'scope/back').classification,'CYCLE');fs.symlinkSync('b',f.root+'/a');fs.symlinkSync('a',f.root+'/b');assert.equal(classifyAlias(f.root,'a').classification,'CYCLE');});
test('deterministic streaming inventory protects all unknown files',t=>{const f=setup(t);f.put('scope/a.txt','a');const spec={schema:'V2_STORAGE_ROOTS_V1',roots:[],scan:['scope']},a=streamingInventory(f.root,spec),b=streamingInventory(f.root,spec);assert.deepEqual(a,b);assert(a.traversalComplete);assert.equal(a.reclaimableBytes,0);assert.equal(a.safeToGc,false);});
test('stream scan cancellation and resource ceilings fail closed',t=>{const f=setup(t);f.put('scope/a','a');assert.throws(()=>[...scanEntries(f.root,['scope'],{signal:{aborted:true}})],/CANCELLED/);assert.throws(()=>[...scanEntries(f.root,['scope'],{limits:{maxEntries:1}})],/BUDGET/);assert.throws(()=>[...scanEntries(f.root,['scope'],{clock:(()=>{let n=0;return ()=>n+=2;})(),limits:{maxDurationMs:1}})],/TIMEOUT/);});
test('over one million virtual files stream with bounded per-directory buffering',()=>{let outstanding=0,peak=0;const io={lstatSync(p){const directory=p==='/virtual/scope'||/\/d\d+$/.test(p);return {dev:1,ino:1,mtimeMs:1,ctimeMs:1,size:1,blocks:1,nlink:1,isSymbolicLink:()=>false,isDirectory:()=>directory,isFile:()=>!directory};},opendirSync(p){const parent=p==='/virtual/scope';let i=0;outstanding++;peak=Math.max(peak,outstanding);return {readSync(){return i<(parent?1001:1000)?{name:(parent?'d':'f')+i++}:null;},closeSync(){outstanding--;}};}};let count=0;for(const r of scanEntries('/virtual',['scope'],{io,limits:{maxEntries:1010000,maxDirectoryEntries:1100}}))if(r.kind==='file')count++;assert.equal(count,1001000);assert.equal(peak,1);});
test('snapshot source and state bodies resolve in acquisition directory; robots path is a URL rule',t=>{const f=setup(t),hash=sha('body'),body='bodies/'+hash+'.txt';f.put('acquired/'+body,'body');f.put('state.json',{});const page={url:'https://example.test/',bodyHash:hash,bodyFile:body,accessDecisions:[{robotsUrl:'https://example.test/robots.txt',rule:{directive:'allow',path:'/',line:1}}]};const p={version:1,cohort:['candidate'],inputHashes:{['acquired/'+body]:hash,'state.json':sha('{}')},parents:[],sources:{candidate:[{directory:'acquired',page}]},states:{candidate:{target:{reads:[page]},reference:{path:'state.json',hash:sha('{}')}}}};f.put('snapshot.json',{...p,snapshotHash:sha(JSON.stringify(p))});const r=closure(f.root,[{...ref('snapshot.json'),format:'SNAPSHOT'}]);assert(r.complete,r.errors);assert(r.entries.some(e=>e.path==='acquired/'+body));});
test('snapshot cannot invent body association absent from fingerprinted sources',t=>{const f=setup(t);const p={version:1,cohort:['candidate'],inputHashes:{},parents:[],sources:{},states:{candidate:{bodyFile:'bodies/'+sha('x')+'.txt',bodyHash:sha('x'),url:'https://example.test'}}};f.put('snapshot.json',{...p,snapshotHash:sha(JSON.stringify(p))});assert(!closure(f.root,[{...ref('snapshot.json'),format:'SNAPSHOT'}]).complete);});
test('streaming audit does not follow alias whose target lies outside selected roots',t=>{const f=setup(t);f.put('target/proof','x');fs.symlinkSync('target',f.root+'/alias');const r=streamingInventory(f.root,{schema:'V2_STORAGE_ROOTS_V1',roots:[],scan:['alias']});assert.equal(r.filesScanned,0);assert.equal(r.traversalComplete,false);assert(!r.safeToGc);});
test('original snapshot hash mismatch blocks legacy certification without repair',t=>{const f=certFixture(t);const s=JSON.parse(fs.readFileSync(f.root+'/snapshot.json'));s.extra='changed without recomputing original seal';f.put('snapshot.json',s);const before=fs.readFileSync(f.root+'/snapshot.json');assert.throws(()=>certifyLegacyBoundary(f.args),/CONTRACT_HASH/);assert.deepEqual(fs.readFileSync(f.root+'/snapshot.json'),before);assert(!fs.existsSync(f.args.destination));});
test('alias report memory has explicit bounds',t=>{const f=setup(t);f.put('scope/target/a','x');fs.symlinkSync('target',f.root+'/scope/a');fs.symlinkSync('target',f.root+'/scope/b');const r=streamingInventory(f.root,{schema:'V2_STORAGE_ROOTS_V1',roots:[],scan:['scope']},{limits:{maxAliases:1}});assert.equal(r.traversalComplete,false);assert(r.errors.includes('STORAGE_ALIAS_BUDGET'));});
