import {closure} from './references.mjs';
import {snapshotLifecycle} from '../inventory/lifecycle-continuation.mjs';
import {inspectLifecycleInput} from '../inventory/reviewed-cohort-handoff.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {buildProductionGenesis,validateGenesisExport,prepareGenesisActions} from './production-genesis.mjs';import {sha} from './core.mjs';
function fixture(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'production-genesis-')),root=base+'/source';fs.mkdirSync(root);t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const put=(p,v)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,JSON.stringify(v));};const ids=Array.from({length:188},(_,i)=>'candidate-'+i),baseline=Array.from({length:275},(_,i)=>({slug:'existing-'+i}));put('manifest.json',{expectedServices:188,serviceIds:ids});put('universe.json',{existing:baseline,new_include:ids.map(slug=>({slug,name:slug,disposition:'NEW_INCLUDE',markets:[]})),research:[]});put('bindings.json',{schemaVersion:1,scope:'SHADOW_RESEARCH_ONLY',bindings:[]});const hash=p=>sha(fs.readFileSync(root+'/'+p));put('input.json',{version:1,cohortManifest:'manifest.json',universe:'universe.json',reviewedBindings:'bindings.json',runsRoot:'.savlivo/research-v2/old-runs',frozenHashes:{'manifest.json':hash('manifest.json'),'universe.json':hash('universe.json')}});const s={version:1,key:'fixture',cohort:ids,parents:[],states:{},sources:{},quarantine:[],historicalRequests:0,parentRequests:0,inputHashes:Object.fromEntries(['manifest.json','universe.json','bindings.json','input.json'].map(p=>[p,hash(p)]))};const save=()=>put('sealed.json',{...s,snapshotHash:sha(JSON.stringify(s))});save();const args={root,destination:base+'/export',snapshotPath:'sealed.json',lifecycleInput:'input.json',expected:{cohort:188,baseline:275,reviewed:0,retainedTargets:0,historicalRequests:0,parentRequests:0},excluded:[{path:'unsealed.json',sha256:'a'.repeat(64),reason:'UNSEALED_HISTORICAL_CONTROL_SNAPSHOT_NOT_USED_AS_GENESIS_INPUT'}],createdAt:'2026-09-22T00:00:00Z',creationIdentity:'TEST',versions:{engine:'fixture',policy:'PRODUCTION_GENESIS_V1'}};return {base,root,put,s,save,args};}
test('independent genesis has new lineage, exact exclusions, frozen scope and deterministic hash',t=>{const f=fixture(t),before=fs.readFileSync(f.root+'/sealed.json'),a=buildProductionGenesis(f.args),b=buildProductionGenesis({...f.args,destination:f.base+'/second'});assert.equal(a.genesis.genesisHash,b.genesis.genesisHash);assert.equal(a.genesis.lineage.continuesHistoricalSnapshot,false);assert.equal(a.genesis.cohort.length,188);assert.equal(a.genesis.baselineExcluded.length,275);assert.equal(a.genesis.excludedUntrustedHistoricalArtifacts[0].sha256,'a'.repeat(64));assert.deepEqual(fs.readFileSync(f.root+'/sealed.json'),before);assert(!fs.existsSync(f.args.destination+'/unsealed.json'));});
test('unsealed source cannot become genesis and no historical fallback occurs',t=>{const f=fixture(t);f.put('sealed.json',f.s);assert.throws(()=>buildProductionGenesis(f.args),/SEALED_SOURCE_REQUIRED/);assert(!fs.existsSync(f.args.destination));});
test('snapshot-only required state without its independent source fails',t=>{const f=fixture(t);f.s.states.x={target:{id:'x',service:'candidate-0'},reference:{path:'missing.json',hash:'b'.repeat(64)}};f.save();assert.throws(()=>buildProductionGenesis({...f.args,expected:{...f.args.expected,retainedTargets:1}}));assert(!fs.existsSync(f.args.destination));});
test('isolated restore validates without source and missing dependency never falls back',t=>{const f=fixture(t);buildProductionGenesis(f.args);const restore=f.base+'/restore';fs.cpSync(f.args.destination,restore,{recursive:true,errorOnExist:true});fs.renameSync(f.root,f.base+'/unavailable');assert.equal(validateGenesisExport(restore).genesis.cohort.length,188);fs.renameSync(restore+'/bindings.json',restore+'/bindings-hidden.json');assert.throws(()=>validateGenesisExport(restore));});
test('tampered genesis and dependency are rejected',t=>{const f=fixture(t),r=buildProductionGenesis(f.args),p=f.args.destination+'/'+r.manifest.genesis;const g=JSON.parse(fs.readFileSync(p));g.accounting.parentRequests++;fs.writeFileSync(p,JSON.stringify(g));assert.throws(()=>validateGenesisExport(f.args.destination),/EXPORT_HASH/);fs.writeFileSync(p,JSON.stringify(r.genesis));fs.writeFileSync(f.args.destination+'/bindings.json','{}');assert.throws(()=>validateGenesisExport(f.args.destination),/EXPORT_HASH/);});
test('baseline cannot enter genesis',t=>{const f=fixture(t);f.s.cohort[0]='existing-0';f.save();assert.throws(()=>buildProductionGenesis(f.args),/SCOPE/);});
test('unknown required reference prevents genesis publication',t=>{const f=fixture(t);f.put('unknown.json',{unknownPath:'missing.json'});f.s.inputHashes['unknown.json']=sha(fs.readFileSync(f.root+'/unknown.json'));f.save();assert.throws(()=>buildProductionGenesis(f.args),/CLOSURE/);assert(!fs.existsSync(f.args.destination));});
test('genesis closure follows only declared sealed roots and keeps untrusted audit locator non-executable',t=>{const f=fixture(t),g=buildProductionGenesis(f.args);const c=closure(f.args.destination,[{path:g.manifest.genesis,format:'JSON',classification:'PERMANENT_CANONICAL'}]);assert(c.complete,JSON.stringify(c.errors));assert(!c.entries.some(e=>e.path==='unsealed.json'));});
test('ordinary lifecycle enters a new execution namespace with imported state, not old ownership',t=>{const f=fixture(t),g=buildProductionGenesis(f.args),v=validateGenesisExport(f.args.destination),before=fs.readFileSync(f.root+'/sealed.json'),old=process.cwd();try{process.chdir(f.args.destination);const h=inspectLifecycleInput(g.manifest.productionInput);const s=snapshotLifecycle({handoff:h,researchMarkets:{},runsRoot:h.config.runsRoot,baselineIds:h.baselineIds,codeHash:'fixture',genesis:v});assert.equal(s.productionGenesisHash,g.genesis.genesisHash);assert.deepEqual(s.parents,[]);assert.equal(s.cohort.length,188);assert(!s.cohort.includes('existing-0'));assert.equal(prepareGenesisActions(v).executionStarted,false);}finally{process.chdir(old);}assert.deepEqual(fs.readFileSync(f.root+'/sealed.json'),before);});
