import {closure} from './references.mjs';
import {snapshotLifecycle} from '../inventory/lifecycle-continuation.mjs';
import {inspectLifecycleInput} from '../inventory/reviewed-cohort-handoff.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {buildProductionGenesis,validateProductionGenesis,validateGenesisExport,prepareGenesisActions} from './production-genesis.mjs';import {sha} from './core.mjs';
function fixture(t){const base=fs.mkdtempSync(path.join(os.tmpdir(),'production-genesis-')),root=base+'/source';fs.mkdirSync(root);t.after(()=>fs.rmSync(base,{recursive:true,force:true}));const put=(p,v)=>{fs.mkdirSync(path.dirname(root+'/'+p),{recursive:true});fs.writeFileSync(root+'/'+p,JSON.stringify(v));};const ids=Array.from({length:188},(_,i)=>'candidate-'+i),baseline=Array.from({length:275},(_,i)=>({slug:'existing-'+i}));put('manifest.json',{expectedServices:188,serviceIds:ids});put('universe.json',{existing:baseline,new_include:ids.map(slug=>({slug,name:slug,disposition:'NEW_INCLUDE',markets:[]})),research:[]});put('bindings.json',{schemaVersion:1,scope:'SHADOW_RESEARCH_ONLY',bindings:[]});const hash=p=>sha(fs.readFileSync(root+'/'+p));put('input.json',{version:1,cohortManifest:'manifest.json',universe:'universe.json',reviewedBindings:'bindings.json',runsRoot:'.savlivo/research-v2/old-runs',frozenHashes:{'manifest.json':hash('manifest.json'),'universe.json':hash('universe.json')}});const s={version:1,key:'fixture',cohort:ids,parents:[],states:{},sources:{},quarantine:[],historicalRequests:0,parentRequests:0,inputHashes:Object.fromEntries(['manifest.json','universe.json','bindings.json','input.json'].map(p=>[p,hash(p)]))};const save=()=>put('sealed.json',{...s,snapshotHash:sha(JSON.stringify(s))});save();const args={root,destination:base+'/export',snapshotPath:'sealed.json',lifecycleInput:'input.json',expected:{cohort:188,baseline:275,reviewed:0,retainedTargets:0,historicalRequests:0,parentRequests:0},excluded:[{path:'unsealed.json',sha256:'a'.repeat(64),reason:'UNSEALED_HISTORICAL_CONTROL_SNAPSHOT_NOT_USED_AS_GENESIS_INPUT'}],createdAt:'2026-09-22T00:00:00Z',creationIdentity:'TEST',versions:{engine:'fixture',policy:'PRODUCTION_GENESIS_V1'}};return {base,root,put,s,save,args};}
test('independent genesis has new lineage, exact exclusions, frozen scope and deterministic hash',t=>{const f=fixture(t),before=fs.readFileSync(f.root+'/sealed.json'),a=buildProductionGenesis(f.args),b=buildProductionGenesis({...f.args,destination:f.base+'/second'});assert.equal(a.genesis.genesisHash,b.genesis.genesisHash);assert.equal(a.genesis.lineage.continuesHistoricalSnapshot,false);assert.equal(a.genesis.cohort.length,188);assert.equal(a.genesis.baselineExcluded.length,275);assert.equal(a.genesis.excludedUntrustedHistoricalArtifacts[0].sha256,'a'.repeat(64));assert.deepEqual(fs.readFileSync(f.root+'/sealed.json'),before);assert(!fs.existsSync(f.args.destination+'/unsealed.json'));});
test('unsealed source cannot become genesis and no historical fallback occurs',t=>{const f=fixture(t);f.put('sealed.json',f.s);assert.throws(()=>buildProductionGenesis(f.args),/SEALED_SOURCE_REQUIRED/);assert(!fs.existsSync(f.args.destination));});
test('snapshot-only required state without its independent source fails',t=>{const f=fixture(t);f.s.states.x={target:{id:'x',service:'candidate-0'},reference:{path:'missing.json',hash:'b'.repeat(64)}};f.save();assert.throws(()=>buildProductionGenesis({...f.args,expected:{...f.args.expected,retainedTargets:1}}));assert(!fs.existsSync(f.args.destination));});
test('isolated restore validates without source and missing dependency never falls back',t=>{const f=fixture(t);buildProductionGenesis(f.args);const restore=f.base+'/restore';fs.cpSync(f.args.destination,restore,{recursive:true,errorOnExist:true});fs.renameSync(f.root,f.base+'/unavailable');assert.equal(validateGenesisExport(restore).genesis.cohort.length,188);fs.renameSync(restore+'/bindings.json',restore+'/bindings-hidden.json');assert.throws(()=>validateGenesisExport(restore));});
test('tampered genesis and dependency are rejected',t=>{const f=fixture(t),r=buildProductionGenesis(f.args),p=f.args.destination+'/'+r.manifest.genesis;const g=JSON.parse(fs.readFileSync(p));g.accounting.parentRequests++;fs.writeFileSync(p,JSON.stringify(g));assert.throws(()=>validateGenesisExport(f.args.destination),/EXPORT_HASH/);fs.writeFileSync(p,JSON.stringify(r.genesis));fs.writeFileSync(f.args.destination+'/bindings.json','{}');assert.throws(()=>validateGenesisExport(f.args.destination),/EXPORT_HASH/);});
test('baseline cannot enter genesis',t=>{const f=fixture(t);f.s.cohort[0]='existing-0';f.save();assert.throws(()=>buildProductionGenesis(f.args),/SCOPE/);});
test('unknown required reference prevents genesis publication',t=>{const f=fixture(t);f.put('unknown.json',{unknownPath:'missing.json'});f.s.inputHashes['unknown.json']=sha(fs.readFileSync(f.root+'/unknown.json'));f.save();assert.throws(()=>buildProductionGenesis(f.args),/CLOSURE/);assert(!fs.existsSync(f.args.destination));});
test('genesis closure follows only declared sealed roots and keeps untrusted audit locator non-executable',t=>{const f=fixture(t),g=buildProductionGenesis(f.args);const c=closure(f.args.destination,[{path:g.manifest.genesis,format:'JSON',classification:'PERMANENT_CANONICAL'}]);assert(c.complete,JSON.stringify(c.errors));assert(!c.entries.some(e=>e.path==='unsealed.json'));});
test('ordinary lifecycle enters a new execution namespace with imported state, not old ownership',t=>{const f=fixture(t);f.s.sources['candidate-0']=[{directory:'.savlivo/old',page:{url:'https://example.test/',outcome:'EMPTY'}}];f.save();const g=buildProductionGenesis(f.args),v=validateGenesisExport(f.args.destination),before=fs.readFileSync(f.root+'/sealed.json'),old=process.cwd(),sourceBefore=JSON.stringify(v.source);try{process.chdir(f.args.destination);const h=inspectLifecycleInput(g.manifest.productionInput);const s=snapshotLifecycle({handoff:h,researchMarkets:{},runsRoot:h.config.runsRoot,baselineIds:h.baselineIds,codeHash:'fixture',genesis:v});assert.equal(JSON.stringify(v.source),sourceBefore);assert.notEqual(s.sources['candidate-0'],v.source.sources['candidate-0']);assert.equal(s.sources['candidate-0'][0],v.source.sources['candidate-0'][0]);assert.equal(s.productionGenesisHash,g.genesis.genesisHash);assert.deepEqual(s.parents,[]);assert.equal(s.cohort.length,188);assert(!s.cohort.includes('existing-0'));assert.equal(prepareGenesisActions(v).executionStarted,false);}finally{process.chdir(old);}assert.deepEqual(fs.readFileSync(f.root+'/sealed.json'),before);});

test('Genesis timing diagnostics preserve all validation and do not expose paths',t=>{
 const f=fixture(t),built=buildProductionGenesis(f.args),timings=[];
 const checked=validateProductionGenesis(f.args.destination,built.manifest.genesis,{onTiming:e=>timings.push(e)});
 assert.equal(checked.genesis.genesisHash,built.genesis.genesisHash);
 assert.deepEqual(timings.map(e=>e.stage),['genesis-seal','protected-file-hashes','reference-closure','source-scope-accounting','capabilities-budgets']);
 assert(timings.every(e=>Number.isFinite(e.durationMs)&&e.durationMs>=0&&Object.keys(e).length===2));
 fs.writeFileSync(f.args.destination+'/bindings.json','{}');
 assert.throws(()=>validateProductionGenesis(f.args.destination,built.manifest.genesis,{onTiming:()=>{}}),/DEPENDENCY_HASH/);
});

test('shared target provenance is parsed once per validation and every target remains compared',t=>{
 const f=fixture(t),targets=Object.fromEntries(Array.from({length:20},(_,i)=>['t'+i,{id:'t'+i,service:'candidate-'+i,status:'UNRESOLVED'}]));
 f.put('state.json',{targets});const hash=sha(fs.readFileSync(f.root+'/state.json'));
 f.s.states=Object.fromEntries(Object.entries(targets).map(([id,target])=>[id,{target,reference:{path:'state.json',hash}}]));f.s.inputHashes['state.json']=hash;f.save();
 const built=buildProductionGenesis({...f.args,expected:{...f.args.expected,retainedTargets:20}});
 const original=fs.readFileSync;let reads=0;t.mock.method(fs,'readFileSync',(...args)=>{if(args[0]===f.args.destination+'/state.json')reads++;return original(...args);});
 const checked=validateProductionGenesis(f.args.destination,built.manifest.genesis,{full:false});assert.equal(Object.keys(checked.source.states).length,20);assert.equal(reads,1);
 // A different expected target cannot acquire provenance merely by sharing the file.
 f.s.states.t19.target={...targets.t19,status:'VERIFIED'};f.save();
 assert.throws(()=>buildProductionGenesis({...f.args,destination:f.base+'/invalid',expected:{...f.args.expected,retainedTargets:20}}),/STATE_PROVENANCE/);
});
