import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {sha,digest,canonical,safe,immutable,read,files} from './core.mjs';
import {closure,publishReceipt,validateReceipt} from './references.mjs';
import {putEvidence,resolveEvidence,readObservation} from './evidence.mjs';
import {publishHistory,historyIndex,accounting} from './history.mjs';
import {inventory,validatePlan} from './inventory.mjs';
import {buildBootstrap,validateBootstrap} from './bootstrap.mjs';
import {diskStatus,requireSpace,storageView} from './runtime.mjs';
import {finalizeRun,receiptPath} from './finalize.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'v2-storage-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const put=(p,v)=>{fs.mkdirSync(path.dirname(safe(root,p)),{recursive:true});fs.writeFileSync(safe(root,p),typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v));};return {root,put};}
const ref=(p,format='JSON',classification='PERMANENT_CANONICAL')=>({path:p,format,classification,reason:'FIXTURE_ROOT'});
const versions={engine:'test',policy:'mature',schema:1};
function receipt(f,{destination='receipt.json',roots=[ref('state.json')],cohort=['candidate'],baseline=['netflix'],capabilities=null,createdAt='2026-01-01T00:00:00Z',runId='run'}={}){return publishReceipt(f.root,{destination,roots,runId,versions,cohort,baseline,capabilities,createdAt});}
test('recognized references and exact hashes form a protected closure',t=>{const f=fixture(t);f.put('body.txt','provider');f.put('state.json',{reference:{path:'body.txt',sha256:sha('provider')}});const c=closure(f.root,[ref('state.json')]);assert(c.complete);assert.equal(c.entries.length,2);assert.equal(receipt(f).entries.length,2);});
for(const [name,data]of [['missing',{path:'absent.txt'}],['unknown schema',{schema:'FUTURE_UNKNOWN'}],['unknown reference',{newUnknownPath:'.savlivo/elsewhere.txt'}],['escape',{path:'../outside'}]])test(name+' fails closed',t=>{const f=fixture(t);f.put('state.json',data);assert.equal(closure(f.root,[ref('state.json')]).complete,false);assert.throws(()=>receipt(f));});
test('opaque structured evidence cannot bypass reference traversal',t=>{const f=fixture(t);f.put('state.json',{path:'missing.txt'});assert.equal(closure(f.root,[ref('state.json','BYTES')]).complete,false);});
test('legacy continuation fingerprint files are protected',t=>{const f=fixture(t);f.put('body.txt','old');const p={version:1,inputHashes:{'body.txt':sha('old')}};f.put('snapshot.json',{...p,snapshotHash:sha(JSON.stringify(p))});const c=closure(f.root,[ref('snapshot.json','SNAPSHOT')]);assert(c.complete);assert(c.entries.some(e=>e.path==='body.txt'));f.put('body.txt','changed');assert(!closure(f.root,[ref('snapshot.json','SNAPSHOT')]).complete);});
test('immutable receipt validates every object and cannot be overwritten',t=>{const f=fixture(t);f.put('state.json',{});const r=receipt(f);assert.equal(receipt(f).contentHash,r.contentHash);f.put('state.json',{changed:true});assert.throws(()=>validateReceipt(f.root,r),/HASH/);assert.throws(()=>receipt(f),/IMMUTABLE/);});
test('identical bytes share one blob while retrieval observations remain distinct',t=>{const f=fixture(t),bytes=Buffer.from('å price <b>5.79</b>\r\n');const a=putEvidence(f.root,{bytes,observationId:'first',observation:{url:'https://provider.example',retrievedAt:'one'}}),b=putEvidence(f.root,{bytes,observationId:'second',observation:{url:'https://provider.example',retrievedAt:'two'}});assert.equal(a.blob.path,b.blob.path);assert.notEqual(a.contentHash,b.contentHash);assert.deepEqual(resolveEvidence(f.root,a.blob),bytes);assert.equal(readObservation(f.root,'second').observation.retrievedAt,'two');assert.equal(files(f.root,'blobs').filter(p=>!p.includes('.publishing-')).length,1);const start=bytes.indexOf(Buffer.from('5.79'));assert.equal(resolveEvidence(f.root,a.blob).subarray(start,start+4).toString(),'5.79');});
test('content hash mismatch and symlinks fail closed',t=>{const f=fixture(t);assert.throws(()=>putEvidence(f.root,{bytes:'a',expectedHash:sha('b'),observationId:'x',observation:{}}),/HASH/);f.put('body','a');fs.symlinkSync('body',safe(f.root,'link'));assert.throws(()=>resolveEvidence(f.root,{schema:'V2_LEGACY_BYTES_V1',path:'link',sha256:sha('a')}),/SYMLINK/);});
test('legacy byte paths continue resolving without mutation',t=>{const f=fixture(t);f.put('old.body',Buffer.from([0,255,10]));assert.deepEqual(resolveEvidence(f.root,{schema:'V2_LEGACY_BYTES_V1',path:'old.body',sha256:sha(Buffer.from([0,255,10]))}),Buffer.from([0,255,10]));});
function historyFixture(t){const f=fixture(t);f.put('run/lineage.json',{capabilities:{direct:false,groq:true},cohort:['candidate'],additionalRequestCeiling:10});f.put('run/summary.json',{executionComplete:true,researchComplete:false});f.put('run/final-dispositions.json',{executionComplete:true,services:[{service_id:'candidate',finalStatus:'PARTIAL',login:{status:'ESTABLISHED'},pricing:[{market:'US',status:'PARTIAL',observations:[{amount:5,currency:'USD'}]}],priceChanges:[{before:4,after:5}]}]});return f;}
test('compact history publication is idempotent and unknown remains null',t=>{const f=historyFixture(t);const a=publishHistory(f.root,{directory:'run'}),b=publishHistory(f.root,{directory:'run'});assert.equal(a.contentHash,b.contentHash);assert.equal(a.accounting.requests,null);assert.equal(a.finishedAt,null);assert.equal(historyIndex(f.root).rows.length,1);const row=JSON.parse(fs.readFileSync(safe(f.root,a.observations.path),'utf8'));assert.equal(row.evidenceAdded,null);assert.deepEqual(row.priceChanges,[{before:4,after:5}]);assert.equal(row.login,'ESTABLISHED');});
test('allowed and actually used stay separate, Groq is never Direct',t=>{const f=historyFixture(t);f.put('run/network.jsonl',JSON.stringify({service:'candidate',kind:'GROQ'})+'\n');const a=publishHistory(f.root,{directory:'run'});assert.equal(a.capabilities.direct,false);assert.equal(a.accounting.byRoute.GROQ,1);assert.equal(a.accounting.byRoute.DIRECT,0);assert.equal(accounting(null).byRoute.DIRECT,null);});
test('uncertain capability intents remain charged in history',()=>{const a=accounting([],[{type:'INTENT',kind:'groq',key:'a'}]);assert.equal(a.groqCalls,1);assert.equal(a.uncertainReservations,1);});
test('incomplete research execution cannot finalize',t=>{const f=historyFixture(t);f.put('run/summary.json',{executionComplete:false});assert.throws(()=>publishHistory(f.root,{directory:'run'}),/NOT_FINAL/);});
test('finalization race detects modified input instead of replacing published history',t=>{const f=historyFixture(t);publishHistory(f.root,{directory:'run'});f.put('run/final-dispositions.json',{executionComplete:true,services:[]});assert.throws(()=>publishHistory(f.root,{directory:'run'}),/IMMUTABLE/);});
function planFixture(t){const f=fixture(t);f.put('state.json',{});return {...f,spec:{schema:'V2_STORAGE_ROOTS_V1',roots:[ref('state.json')],scan:['state.json'],runs:[],coordination:[]}};}
test('dry-run is deterministic, non-destructive and protects references',t=>{const f=planFixture(t),opts={now:'2026-09-22T00:00:00Z'};const a=inventory(f.root,f.spec,opts),b=inventory(f.root,f.spec,opts);assert.deepEqual(a,b);assert(a.safeToGc);assert.equal(a.filesReclaimable,0);assert.equal(a.referencedArtifactsSelectedForDeletion,0);assert(fs.existsSync(safe(f.root,'state.json')));});
test('unknown artifacts protected; no unsafe reclaimable estimate',t=>{const f=planFixture(t);f.put('unknown.txt','x');f.spec.scan.push('unknown.txt');const p=inventory(f.root,f.spec);assert(!p.safeToGc);assert.equal(p.filesProtected,2);assert.equal(p.reclaimableBytes,0);});
test('changed root invalidates prior GC plan',t=>{const f=planFixture(t),p=inventory(f.root,f.spec);f.put('state.json',{changed:true});assert.throws(()=>validatePlan(f.root,f.spec,p),/STALE/);});
for(const status of ['QUEUED','RUNNING','INTERRUPTED','STOPPED'])test(status+' Operations state survives worker/PID restart',t=>{const f=planFixture(t);f.put('ops.json',{jobs:[{status,pid:999999}]});f.spec.coordination=['ops.json'];f.spec.scan.push('ops.json');const p=inventory(f.root,f.spec);assert(p.rows.find(r=>r.path==='ops.json').protected);assert.equal(p.filesReclaimable,0);});
test('checkpoint publication race fails closed',t=>{const f=planFixture(t);f.spec.coordination=['state.json'];const p=inventory(f.root,f.spec,{beforeRecheck:()=>f.put('state.json',{pending:true})});assert(!p.safeToGc);assert(p.errors.includes('STORAGE_COORDINATION_CHANGED'));});
test('unknown reference schema in roots fails closed',t=>{const f=planFixture(t);f.spec.roots[0].format='FUTURE';assert(!inventory(f.root,f.spec).safeToGc);});
test('latest four plus 60 days protect full runs; only declared expired diagnostics reclaimable',t=>{const f=fixture(t),spec={schema:'V2_STORAGE_ROOTS_V1',roots:[],scan:[],runs:[],candidates:[]};for(let i=0;i<6;i++){const d='run'+i;f.put(d+'/summary.json',{executionComplete:true});f.put(d+'/proof.txt','proof'+i);f.put(d+'/debug.log','debug'+i);const createdAt=i===5?'2026-09-20T00:00:00Z':`2026-01-0${i+1}T00:00:00Z`;receipt(f,{destination:d+'/finalized-references.json',roots:[ref(d+'/summary.json'),ref(d+'/proof.txt','BYTES')],runId:d,createdAt});spec.runs.push({path:d});spec.scan.push(d+'/summary.json',d+'/proof.txt',d+'/debug.log',d+'/finalized-references.json');spec.candidates.push({schema:'V2_DISPOSABLE_ARTIFACT_V1',path:d+'/debug.log',sha256:sha('debug'+i),classification:'SHORT_TERM_DIAGNOSTIC',producer:'fixture-v1',reason:'diagnostic only',createdAt,run:d});}const p=inventory(f.root,spec,{now:'2026-09-22T00:00:00Z'});assert(p.safeToGc,p.errors.join(','));assert.deepEqual(p.rows.filter(r=>r.reclaimable).map(r=>r.path),['run0/debug.log','run1/debug.log']);assert(p.rows.filter(r=>r.path.endsWith('proof.txt')).every(r=>r.protected));});
function bootstrapFixture(t){const f=fixture(t),cohort=Array.from({length:188},(_,i)=>'new-'+i),baseline=Array.from({length:275},(_,i)=>'old-'+i),capabilities={direct:true,tavily:false,decodo:false,browser:false,groq:false};f.put('manifest.json',{serviceIds:cohort,expectedServices:188});f.put('universe.json',{existing:baseline.map(service=>({service})),new_include:cohort.map(slug=>({slug,name:slug,disposition:'NEW_INCLUDE'})),research:[]});f.put('bindings.json',{schemaVersion:1,scope:'SHADOW_RESEARCH_ONLY',bindings:[]});f.put('input.json',{version:1,cohortManifest:'manifest.json',universe:'universe.json',reviewedBindings:'bindings.json',runsRoot:'.savlivo/research-v2/runs',capabilities,frozenHashes:{'manifest.json':sha(fs.readFileSync(safe(f.root,'manifest.json'))),'universe.json':sha(fs.readFileSync(safe(f.root,'universe.json')))}});f.put('proof.body','immutable');f.put('state.json',{path:'proof.body',hash:sha('immutable')});receipt(f,{roots:[ref('input.json'),ref('state.json')],cohort,baseline,capabilities});return {...f,spec:{schema:'V2_BOOTSTRAP_INPUT_V1',receipt:'receipt.json',lifecycleInput:'input.json'},cohort};}
test('bootstrap closure restores with 188 frozen, 275 excluded and capabilities preserved',t=>{const f=bootstrapFixture(t),dest=path.join(f.root,'export');const m=buildBootstrap({root:f.root,destination:dest,spec:f.spec,createdAt:'2026-09-22',sourceIdentity:'fixture'});assert.equal(m.validation.brokenReferences,0);const restored=path.join(f.root,'restore');fs.cpSync(dest,restored,{recursive:true});const v=validateBootstrap(restored);assert.equal(v.cohort,188);assert.equal(v.baselineExcluded,275);assert.equal(v.capabilities.tavily,false);assert.equal(fs.readFileSync(safe(f.root,'proof.body'),'utf8'),'immutable');});
test('bootstrap hash corruption fails restore validation',t=>{const f=bootstrapFixture(t),dest=path.join(f.root,'export');buildBootstrap({root:f.root,destination:dest,spec:f.spec,createdAt:'2026-09-22',sourceIdentity:'fixture'});fs.writeFileSync(path.join(dest,'proof.body'),'tampered');assert.throws(()=>validateBootstrap(dest),/HASH/);});
test('bootstrap refuses Mac-only dependencies and source escapes',t=>{const f=bootstrapFixture(t);assert.throws(()=>safe(f.root,'../escape'),/ESCAPE/);f.put('mac.json',{path:safe(f.root,'proof.body')});receipt(f,{destination:'mac-receipt.json',roots:[ref('input.json'),ref('mac.json')],cohort:f.cohort,baseline:Array.from({length:275},(_,i)=>'old-'+i),capabilities:read(safe(f.root,'input.json')).capabilities});assert.throws(()=>buildBootstrap({root:f.root,destination:path.join(f.root,'export'),spec:{...f.spec,receipt:'mac-receipt.json'},createdAt:'now',sourceIdentity:'fixture'}),/NONPORTABLE/);});
test('disk unavailable blocks admission without deleting active state',t=>{const f=fixture(t);f.put('active.json',{pending:true});assert.throws(()=>requireSpace(f.root,{statfs:()=>{throw Error();}}),/UNAVAILABLE/);assert.equal(read(safe(f.root,'active.json')).pending,true);});
test('low disk blocks new admission; reserve never triggers deletion',t=>{const f=fixture(t);const statfs=()=>({blocks:10,bfree:1,bavail:1,bsize:1024**3});assert.equal(diskStatus(f.root,{statfs}).admissionAllowed,false);assert.throws(()=>requireSpace(f.root,{statfs}),/LOW_SPACE/);assert.equal(diskStatus(f.root,{statfs:()=>({blocks:50,bfree:20,bavail:20,bsize:1024**3})}).admissionAllowed,true);});
test('storage view unavailable metrics remain unknown',t=>{const f=fixture(t),v=storageView(f.root);assert.equal(v.inventory,null);assert.equal(v.growthRate,null);assert.equal(v.destructiveGcEnabled,false);});
test('historical runs are not rewritten by automatic finalization',t=>{const f=historyFixture(t),before=fs.readFileSync(safe(f.root,'run/lineage.json'));assert.equal(finalizeRun(f.root,{directory:'run'}).status,'LEGACY_PROTECTED');assert.deepEqual(fs.readFileSync(safe(f.root,'run/lineage.json')),before);});

import {snapshotLifecycle,validateLifecycleSnapshot} from '../inventory/lifecycle-continuation.mjs';
test('new complete run publishes receipt/history and subsequent continuation uses protected boundary',t=>{const f=historyFixture(t),lineage=read(safe(f.root,'run/lineage.json'));f.put('run/lineage.json',{...lineage,storageBoundaryVersion:1,fingerprint:'fixture'});f.put('run/summary.json',{executionComplete:true,researchComplete:false,additionalRequests:0});f.put('run/debug.log','not a future execution input');const r=finalizeRun(f.root,{directory:'run',baseline:['netflix'],engine:'fixture',createdAt:'2026-09-22T00:00:00Z'});assert.equal(r.status,'FINALIZED');assert.equal(historyIndex(f.root).rows.length,1);const old=process.cwd();try{process.chdir(f.root);const handoff={cohort:{manifest:{serviceIds:['candidate']}},document:{},inputHashes:{},summary:{historicalRequests:3838}};const s=snapshotLifecycle({handoff,researchMarkets:{},runsRoot:'.',baselineIds:['netflix'],codeHash:'new'});assert.equal(s.inputHashes['run/debug.log'],undefined);assert(s.inputHashes[receiptPath('run')]);f.put('run/debug.log','diagnostic changed');validateLifecycleSnapshot(s);assert.equal(s.historicalRequests,3838);}finally{process.chdir(old);}});
test('receipt completeness is checked beyond its list of claimed entries',t=>{const f=fixture(t);f.put('body.txt','proof');f.put('state.json',{path:'body.txt'});const r=receipt(f),{contentHash,...payload}=r;payload.entries=payload.entries.filter(e=>e.path!=='body.txt');assert.throws(()=>validateReceipt(f.root,{...payload,contentHash:digest(payload)}),/INCOMPLETE/);});
test('API storage is read-only and rejects destructive routes',async t=>{const f=fixture(t);const {Operations}=await import('../../v2-operations/control.mjs'),{operationsRequest}=await import('../../v2-operations/http.mjs');const ops=new Operations({repo:f.root,root:path.join(f.root,'ops'),read:true});const result=await operationsRequest({method:'GET',url:new URL('http://local/v1/admin/v2-operations/storage'),actor:'test'},ops);assert.equal(result.destructiveGcEnabled,false);await assert.rejects(operationsRequest({method:'POST',url:new URL('http://local/v1/admin/v2-operations/storage/delete'),actor:'test'},ops),/NOT_FOUND/);assert(!fs.existsSync(path.join(f.root,'ops')));});
test('control enqueue blocks low disk before writing a job',async t=>{const f=fixture(t);const {Operations}=await import('../../v2-operations/control.mjs');const ops=new Operations({repo:f.root,root:path.join(f.root,'ops')});const stub=t.mock.method(fs,'statfsSync',()=>({blocks:10,bfree:1,bavail:1,bsize:1024**3}));try{assert.throws(()=>ops.enqueue({jobs:[]},{},'test','ADMIN','id'),/LOW_SPACE/);assert(!fs.existsSync(path.join(f.root,'ops')));}finally{stub.mock.restore();}});

test('new file publication during inventory invalidates the plan',t=>{const f=fixture(t);f.put('scope/state.json',{});const p=inventory(f.root,{schema:'V2_STORAGE_ROOTS_V1',roots:[ref('scope/state.json')],scan:['scope']},{beforeRecheck:()=>f.put('scope/new-checkpoint.json',{})});assert(!p.safeToGc);assert(p.errors.includes('STORAGE_DIRECTORY_PUBLICATION_RACE'));});
test('CLI dry-run metrics are compact, readable, and have no destructive command',async t=>{const f=planFixture(t);f.put('spec.json',f.spec);const {main}=await import('./cli.mjs');const log=t.mock.method(console,'log',()=>{});try{main(['gc-dry-run','--root',f.root,'--spec',safe(f.root,'spec.json'),'--publish-index','true']);const view=storageView(f.root);assert(view.inventory);assert.equal(view.inventory.filesScanned,1);assert.equal(view.inventory.rows,undefined);assert.throws(()=>main(['delete']),/Usage/);}finally{log.mock.restore();}});
test('active reserve check stops measured low space but not unknown metrics',async t=>{const {checkpointReserveLow}=await import('./runtime.mjs');const f=fixture(t);const stub=t.mock.method(fs,'statfsSync',()=>({blocks:50,bfree:1,bavail:1,bsize:1024**3}));try{assert(checkpointReserveLow(f.root));stub.mock.mockImplementation(()=>{throw Error();});assert.equal(checkpointReserveLow(f.root),false);}finally{stub.mock.restore();}});

test('before/after price observations are derived from immutable parent history',t=>{const f=historyFixture(t);publishHistory(f.root,{directory:'run'});f.put('next/lineage.json',{cohort:['candidate'],lifecycle:{parents:[{directory:'run'}]}});f.put('next/summary.json',{executionComplete:true});f.put('next/final-dispositions.json',{executionComplete:true,services:[{service_id:'candidate',finalStatus:'PARTIAL',pricing:[{market:'US',status:'PARTIAL',observations:[{amount:6,currency:'USD'}]}]}]});const h=publishHistory(f.root,{directory:'next'}),row=JSON.parse(fs.readFileSync(safe(f.root,h.observations.path)));assert.equal(row.before.login,'ESTABLISHED');assert.equal(row.priceChanges[0].before[0].observations[0].amount,5);assert.equal(row.priceChanges[0].after[0].observations[0].amount,6);});
test('unknown schema in a blob observation is rejected by explicit resolver',t=>{const f=fixture(t);assert.throws(()=>resolveEvidence(f.root,{schema:'V3_UNREVIEWED',path:'body',sha256:'a'}),/UNKNOWN/);});
test('failed unfinished runs remain protected regardless of age',t=>{const f=fixture(t);f.put('run/summary.json',{executionComplete:false,finishedAt:'2000-01-01'});f.put('run/checkpoint.json',{pending:{service:'candidate'}});const p=inventory(f.root,{schema:'V2_STORAGE_ROOTS_V1',roots:[],scan:['run'],runs:[{path:'run'}]});assert.equal(p.filesReclaimable,0);assert(p.rows.every(r=>r.protected));assert(p.rows.some(r=>r.classification==='RESUME_CRITICAL'));});

test('bootstrap includes permanent Analytics automatically and restored index is readable',t=>{const f=bootstrapFixture(t),d='.savlivo/runs/example';f.put(d+'/lineage.json',{cohort:f.cohort});f.put(d+'/summary.json',{executionComplete:true});f.put(d+'/final-dispositions.json',{executionComplete:true,services:[]});publishHistory(f.root,{directory:d});const dest=path.join(f.root,'export');buildBootstrap({root:f.root,destination:dest,spec:f.spec,createdAt:'2026-09-22',sourceIdentity:'fixture'});assert.equal(historyIndex(dest).rows.length,1);assert.equal(validateBootstrap(dest).brokenReferences,0);});

test('root-aware mature input validation produces portable new fingerprint keys',async t=>{const f=bootstrapFixture(t),{inspectLifecycleInput}=await import('../inventory/reviewed-cohort-handoff.mjs');const h=inspectLifecycleInput(safe(f.root,'input.json'),f.root);assert(h.inputHashes['input.json']);assert(Object.keys(h.inputHashes).every(p=>!path.isAbsolute(p)));assert.equal(h.cohort.manifest.serviceIds.length,188);assert.equal(h.baselineIds.length,275);});
