import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {resolveCapabilities,requireCapability,capabilityPreflight,capabilityNames} from './config.mjs';
import {capabilityLedger} from './ledger.mjs';
import {pricingGap,enrichProvider} from './enrichment.mjs';
import {validateSemanticOutput} from '../../research-v1/semantic-price.mjs';
const none={direct:false,tavily:false,decodo:false,browser:false,groq:false};
for(const name of capabilityNames)test(name+' independent permission and hard guard',()=>{const c=resolveCapabilities({...none,[name]:true});assert(c[name]);for(const other of capabilityNames)if(other!==name)assert.throws(()=>requireCapability(c,other),/CAPABILITY_DISABLED/);requireCapability(c,name);assert(Object.isFrozen(c));});
test('wildcards, omissions and non-booleans fail closed',()=>{for(const c of [{ALL:true},{...none,all:true},{...none,direct:'true'},[]])assert.throws(()=>resolveCapabilities(c));});
test('LOGIN_MANAGE rejects unsupported capabilities',()=>{for(const k of ['browser','groq','decodo'])assert.throws(()=>resolveCapabilities({...none,[k]:true},'LOGIN_MANAGE'));});
test('disabled credentials and browser runtime are never prerequisites',()=>{assert(capabilityPreflight(none,{}, {probeBrowser:()=>assert.fail('disabled browser initialized')}).ready);});
for(const k of ['tavily','decodo','groq'])test(k+' selected requires conditional credentials',()=>assert.equal(capabilityPreflight({...none,[k]:true},{}).ready,false));
test('missing browser runtime fails closed without launch',()=>{const p=capabilityPreflight({...none,browser:true},{},{probeBrowser:()=>({available:false,reason:'DOCKER_UNAVAILABLE'})});assert.equal(p.ready,false);assert.equal(p.availability.browser.reason,'DOCKER_UNAVAILABLE');});
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'v2-capabilities-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
test('durable result reuse, budget exhaustion and resume do not replenish',async t=>{const dir=temp(t),c={...none,browser:true},limits={browserPerService:1,browserPerRun:2};let calls=0;const run=()=>capabilityLedger(dir,c,{limits}),a={service:'one',url:'https://example.com',sourceHash:'a',trigger:'rendering'};assert.equal((await run().attempt('browser',a,async()=>{calls++;return {status:'OK'};})).status,'OK');await run().attempt('browser',a,()=>assert.fail('repeated'));assert.equal(calls,1);assert.equal((await run().attempt('browser',{...a,sourceHash:'b'},()=>assert.fail())).reason,'CAPABILITY_BUDGET_EXHAUSTED');await run().attempt('browser',{...a,service:'two'},async()=>({status:'FAILED'}));assert.equal((await run().attempt('browser',{...a,service:'three'},()=>assert.fail())).reason,'CAPABILITY_BUDGET_EXHAUSTED');assert.throws(()=>capabilityLedger(dir,{...c,direct:true},{limits}),/CHECKPOINT_CHANGED/);});
test('uncertain dispatch remains review required',async t=>{const dir=temp(t),c={...none,groq:true};const l=capabilityLedger(dir,c,{model:'test'}),a={service:'one',url:'https://example.com',sourceHash:'x',trigger:'gap'};await l.attempt('groq',a,async()=>({status:'OK'}));const file=dir+'/capability-ledger.jsonl',rows=fs.readFileSync(file,'utf8').trim().split('\n');fs.writeFileSync(file,rows.slice(0,2).join('\n')+'\n');assert.equal((await capabilityLedger(dir,c,{model:'test'}).attempt('groq',a,()=>assert.fail())).reason,'UNCERTAIN_CAPABILITY_DISPATCH');});
test('disabled enrichment does not initialize runtimes',async()=>{const result={sufficient:false};assert.equal(await enrichProvider({capabilities:none,target:{},page:{},result,createRuntime:()=>assert.fail(),createSemantic:()=>assert.fail()}),result);});
test('sufficient deterministic evidence and catalog objective never trigger interpretation',()=>{const p={outcome:'OK',authority:{status:'CONFIGURED_REVIEWED'}};assert.equal(pricingGap({researchObjective:'CATALOG_ONLY'},p,{}),false);assert.equal(pricingGap({},p,{sufficient:true}),false);assert.equal(pricingGap({},p,{verified:[{}]}),false);assert.equal(pricingGap({}, {...p,authority:{}},{}),false);});
test('semantic hallucination and concatenated amounts fail grounding',()=>{assert.throws(()=>validateSemanticOutput({offers:[{amount:{value:'5798.33',quote:'5.79 8.33',start:0,end:9}}]},{text:'5.79 8.33'}));});
import {createHash} from 'node:crypto';
import {acquisitionEscalation} from '../live/provider-access-gap.mjs';
import {executableAction} from '../live/execution-capabilities.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
function source(t,body){const dir=temp(t);fs.mkdirSync(dir+'/bodies');const h=hash(body);fs.writeFileSync(dir+'/bodies/'+h+'.txt',body);return {directory:dir,target:{service:'example',serviceName:'Example',market:'FR',researchObjective:'SERVICE_COVERAGE',authorities:[{hostname:'example.com',provider:'Example',sourceType:'OFFICIAL_PROVIDER'}]},page:{url:'https://example.com/',outcome:'OK',httpStatus:200,contentType:'text/html',bodyHash:h,bodyFile:'bodies/'+h+'.txt',sourceIntegrity:{sha256:h},authority:{status:'CONFIGURED_REVIEWED',provider:'Example',hostname:'example.com'},accessDecisions:[{decision:'ALLOWED'}]}};}
test('foreign-language unresolved source reaches bounded Groq, no acquisition or authority grant',async t=>{const args=source(t,'<section>Abonnement individuel 9.99 EUR par mois</section>'),caps={...none,groq:true};let calls=0,charges=0,verified=0;const ledger=capabilityLedger(args.directory,caps,{model:'test'});const invoke=()=>enrichProvider({...args,capabilities:caps,ledger,result:{verified:[]},charge:()=>charges++,createSemantic:async()=>({policy:{modelRevision:'test'},interpret:async()=>{calls++;return {offers:[]};}}),verify:async()=>{verified++;return {verified:[],sufficient:false};}});assert.equal((await invoke()).semanticInterpretation.status,'ABSTAINED');await invoke();assert.equal(calls,1);assert.equal(charges,1);assert.equal(verified,1);});
test('untrusted or damaged source cannot reach Groq',async t=>{const args=source(t,'<section>9.99 EUR par mois</section>');args.page.bodyHash='bad';await assert.rejects(enrichProvider({...args,capabilities:{...none,groq:true},result:{},ledger:{attempt:()=>assert.fail('must not dispatch')}}),/HASH_MISMATCH/);});
test('browser cannot implicitly authorize either transport',async t=>{const args=source(t,'<script src="/app.js"></script><p>Enable JavaScript</p>'),caps={...none,browser:true};const r=await enrichProvider({...args,capabilities:caps,ledger:capabilityLedger(args.directory,caps),result:{},createRuntime:()=>assert.fail('no transport'),readResource:()=>assert.fail('no Direct')});assert.equal(r.browser.reason,'CAPABILITY_FAILED_CLOSED');});
test('normal source never initializes browser',async t=>{const args=source(t,'<p>No rendering gap</p>');await enrichProvider({...args,capabilities:{...none,browser:true},result:{},createRuntime:()=>assert.fail('unnecessary browser'),ledger:{attempt:()=>assert.fail()}});});
test('robots and semantic gaps cannot authorize Decodo',()=>{for(const page of [{outcome:'ACCESS_CONTROL_STOP',failure:{code:'ROBOTS_DISALLOWED'}},{outcome:'OK',failure:{code:'RENDERING_REQUIRED'}},{outcome:'UNRESOLVED',failure:{code:'NO_PRICE'}}])assert.equal(acquisitionEscalation({page}).eligible,false);assert.equal(acquisitionEscalation({page:{outcome:'UNRESOLVED',failure:{code:'TIMEOUT'},accessDecisions:[{decision:'ALLOWED'}]}}).eligible,true);});
test('execution capability space independently blocks disabled acquisition',()=>{for(const [route,k]of [['DIRECT','direct'],['DISCOVERY','tavily'],['CONDITIONAL_DECODO','decodo']])assert.equal(executableAction({capabilities:none},{route,url:'https://example.com/',escalation:{eligible:true}}).executable,false);});
import {captureRenderedPage} from './page-runtime-screenshot.mjs';
test('screenshot pixel ceiling prevents PNG allocation',async t=>{let capture=0;const result=await captureRenderedPage({directory:temp(t),sessionId:'one',browser:{send:async method=>{if(method==='Page.getLayoutMetrics')return {cssContentSize:{width:10000,height:10000},cssLayoutViewport:{clientWidth:1,clientHeight:1}};if(method==='Page.captureScreenshot')capture++;return {};}}});assert.equal(capture,0);assert.equal(result.outcome,'FAILED');});
test('retained inline rendering works without Direct; external resources remain prohibited',async t=>{const args=source(t,'<script>var app = true;</script><p>Enable JavaScript</p>'),caps={...none,browser:true};let runs=0;const result=await enrichProvider({...args,capabilities:caps,ledger:capabilityLedger(args.directory,caps),result:{},readResource:()=>assert.fail('no external Direct'),createRuntime:async()=>({execute:async({readResource})=>{runs++;await assert.rejects(readResource({url:'https://example.com/app.js'}),/NO_POLICY_AUTHORIZED_RESOURCE_TRANSPORT/);await assert.rejects(readResource({url:'https://evil.example/app.js'}),/AUTHORITY_REQUIRED/);return {outcome:'UNRESOLVED',reason:'RUNTIME_PAGE_STABLE',resources:[]};}})});assert.equal(runs,1);assert.equal(result.browser.status,'UNRESOLVED');});
test('browser never runs on robots-denied parent',async t=>{const args=source(t,'<script>var app=true;</script>Enable JavaScript');args.page.accessDecisions=[{decision:'DISALLOWED'}];await assert.rejects(enrichProvider({...args,capabilities:{...none,browser:true},result:{},ledger:{attempt:()=>assert.fail()},createRuntime:()=>assert.fail()}),/POLICY_UNPROVEN/);});
test('Groq service and run limits survive failed calls',async t=>{const dir=temp(t),c={...none,groq:true},limits={groqPerService:1,groqPerRun:1},a={service:'one',url:'https://example.com',sourceHash:'a',trigger:'gap'};const l=capabilityLedger(dir,c,{limits});await l.attempt('groq',a,async()=>{throw Error('timeout');});assert.equal((await capabilityLedger(dir,c,{limits}).attempt('groq',{...a,service:'two'},()=>assert.fail())).reason,'CAPABILITY_BUDGET_EXHAUSTED');});

test('Groq readiness distinguishes key and model without API calls or changing admission',()=>{
 for(const [env,reason,key,model]of [
  [{},'GROQ_KEY_AND_MODEL_REQUIRED',false,false],
  [{GROQ_API_KEY:'fixture'},'GROQ_MODEL_REQUIRED',true,false],
  [{SAVLIVO_PRICE_SEMANTIC_MODEL:'fixture/model'},'GROQ_KEY_REQUIRED',false,true],
  [{GROQ_API_KEY:'fixture',SAVLIVO_PRICE_SEMANTIC_MODEL:'invalid model'},'GROQ_MODEL_INVALID',true,false],
  [{GROQ_API_KEY:'fixture',SAVLIVO_PRICE_SEMANTIC_MODEL:'fixture/model'},'CONFIGURED',true,true]
 ]){
  const check=capabilityPreflight({...none,groq:true},env),g=check.availability.groq;
  assert.equal(g.reason,reason);assert.equal(g.keyConfigured,key);assert.equal(g.modelConfigured,model);assert.equal(check.ready,key&&model);
  assert.equal(capabilityPreflight(none,env).ready,true);
  assert(!JSON.stringify(check).includes('fixture'));
 }
});
