// Cadence eligibility is separate from recurrence and commercial role.
// No amount conversion and no inference from currency, market or provider.
export const cadencePolicy={version:1,family:'MONTHLY_FAMILY',calendarMonths:[1],days:[28,30],weeks:[4],hours:{min:720,max:744}};
export function isMonthlyFamily(value,unit){return unit==='MONTH'?value===1:unit==='DAY'?[28,30].includes(value):unit==='WEEK'?value===4:unit==='HOUR'?Number.isInteger(value)&&value>=720&&value<=744:false;}
const units={months:'MONTH',month:'MONTH',monate:'MONTH',monaten:'MONTH',monat:'MONTH',mois:'MONTH',meses:'MONTH',mese:'MONTH',mesi:'MONTH',maanden:'MONTH',maand:'MONTH',månader:'MONTH',månad:'MONTH',måneder:'MONTH',måned:'MONTH',years:'YEAR',year:'YEAR',jahre:'YEAR',jahr:'YEAR',år:'YEAR',days:'DAY',day:'DAY',jours:'DAY',jour:'DAY',dagen:'DAY',dag:'DAY',tage:'DAY',tagen:'DAY',tag:'DAY',dni:'DAY',días:'DAY',dias:'DAY',giorni:'DAY',weeks:'WEEK',week:'WEEK',semaines:'WEEK',semaine:'WEEK',weken:'WEEK',wochen:'WEEK',tygodnie:'WEEK',tygodni:'WEEK',semanas:'WEEK',settimane:'WEEK',hours:'HOUR',hour:'HOUR',heures:'HOUR',heure:'HOUR',uur:'HOUR',uren:'HOUR',stunden:'HOUR',godzin:'HOUR',horas:'HOUR',ore:'HOUR'};
const interval=new RegExp('(?<![\\d.,])([0-9]+)\\s*[-–]?\\s*('+Object.keys(units).sort((a,b)=>b.length-a.length).join('|')+')(?!\\p{L})','giu');
export function scanBillingIntervals(text,{path=null,bodyHash=null}={}){const raw=String(text??''),out=[];for(const m of raw.matchAll(interval)){const value=Number(m[1]),unit=units[m[2].toLowerCase()],prefix=raw.slice(Math.max(0,m.index-45),m.index);out.push({value,unit,normalized:`P${unit==='HOUR'?'T':''}${value}${unit[0]}`,originalWording:m[0],recurringPresentation:/(?:\/|\bper|\bevery|\beach|\btous les|\btoutes les|\balle|\bieder(?:e)?|\belke|\bco|\bcada|\bogni)\s*$/iu.test(prefix),cadenceFamily:isMonthlyFamily(value,unit)?'MONTHLY_FAMILY':null,path,bodyHash,span:[m.index,m.index+m[0].length]});}return out;}
export function billingCadence(text,fields={},context={}){const intervals=scanBillingIntervals(text,context);const v=String(fields.billingPeriod??fields.billingInterval??fields.billingDuration??fields.unitText??'');const iso=v.match(/^P(T)?(\d+)([DWHMY])$/i);if(iso){const unit={D:'DAY',W:'WEEK',H:'HOUR',M:'MONTH',Y:'YEAR'}[iso[3].toUpperCase()],value=Number(iso[2]);if((unit==='HOUR')===!!iso[1]&&!(iso[1]&&unit==='MONTH'))intervals.push({value,unit,normalized:v.toUpperCase(),originalWording:v,recurringPresentation:true,cadenceFamily:isMonthlyFamily(value,unit)?'MONTHLY_FAMILY':null,...context,structuredField:true});}
 const recurring=intervals.filter(i=>i.recurringPresentation),keys=new Set(recurring.map(i=>i.normalized));return {intervals,interval:keys.size===1?recurring[0]:null,ambiguous:keys.size>1};}
