import test from 'node:test';
import assert from 'node:assert/strict';
import {extract,hash} from './extract.mjs';
import {proseBounds} from './named-price-prose.mjs';
import {deriveEvidence,verifyCandidate,verifyIdentity} from '../verification/gate.mjs';
import {selectMonthlyPlans} from './commercial.mjs';
const renewal='Plan Basic for 3 months total 5 €; Plan Plus for 3 months total 8 €. After the first 3 months the membership renews monthly at 11.99 EUR/month (Plan Basic) or 21.99 EUR/month (Plan Plus) unless cancelled.';
const intro='Plan Basic for 3 months total 5 €, then 11.99 €/month; Plan Plus for 3 months total 8 €, then 21.99 €/month';
const extra='Plan Plus is included with Membership Other at 0 €/month; Membership Other sold separately at 39 €/month';
const legal=text=>({fields:{content:{fields:{legalText:[{fields:{variations:[{fields:{text}}]}}]}}}});
const script=value=>'<script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(value)+'</script>';
function body({visible=false,market=false}={}){return script({props:{pageProps:{...(market?{basePageProps:{country:'DE',market:'de'},metadata:{country:'DE',market:'de',locale:'de-DE'}}:{}),...legal(renewal),repeat:legal(renewal),intro:legal(intro),officialDisclaimer:extra,noise:{text:renewal,value:renewal,description:'Contact our support team.'},raw:[{amount:0},{amount:11.99}],ambiguous:legal('11.99 €/month (Plan Basic or Plan Plus)')}},...(market?{query:{market:'de'}}:{})})+(visible?[renewal,intro,extra].map(t=>'<p>'+t+'</p>').join(''):'');}
const paid=c=>['11.99','21.99'].includes(c.amountNormalized);
function analyze(html,{authority=true,geo=true}={}){const bodyHash=hash(html),derived=deriveEvidence(html,{bodyHash,service:'fixture',market:'DE',authority,sourceOccurrences:[{id:'s',url:'https://provider.example/plans'}],geoEvidence:geo?[{classification:'G1',targetCountry:'DE',geoCountry:'DE',bodyHash}]:[]});const decisions=new Map(derived.rows.map(c=>[c.candidateId,verifyCandidate(c,derived,{intact:true,bodyHash,service:'fixture',serviceEstablished:authority,bindingEstablished:true})]));return {rows:derived.rows,plans:selectMonthlyPlans(derived.rows),decisions};}
test('typed content-model legal text admits bounded source-bound coordinated relationships',()=>{const html=body(),cs=extract(html).candidates.filter(c=>paid(c)&&c.prosePriceRelationship);assert.equal(cs.length,6);for(const c of cs){assert.equal(c.prosePriceRelationship.bodyHash,hash(html));assert.equal(c.product,c.amountNormalized==='11.99'?'Plan Basic':'Plan Plus');assert.equal(c.currency,'EUR');assert.equal(c.billingPeriod,'MONTH');assert.equal(c.prosePriceRelationship.relationship.phase,'RENEWAL');assert.equal(c.ownershipAmbiguous,false);assert(!c.qualifier.includes('EMBEDDED_OFFER_ACTIVATION_UNRESOLVED'));}assert(cs.some(c=>c.structuredPath.endsWith('/legalText/0/fields/variations/0/fields/text')));});
test('JSON text does not borrow page market even with authority and geo',()=>{const r=analyze(body());assert(r.rows.some(paid));assert(r.plans.every(p=>!p.strongRecurringMonthly));assert([...r.decisions.values()].every(d=>d.status==='V2_VERIFICATION_BLOCKED'));});
test('presentation plus independent evidence verifies separate paid identities despite weak duplicates/raw values',()=>{const r=analyze(body({visible:true}));for(const p of r.plans){assert.equal(p.strongRecurringMonthly,true);assert.equal(verifyIdentity(p,r.decisions).status,'V2_VERIFIED');}assert.deepEqual(r.plans.map(p=>p.amounts),[[['39','EUR']],[['11.99','EUR']],[['21.99','EUR']]]);assert.equal(new Set(r.plans.map(p=>p.monthlyPlanId)).size,3);assert(r.rows.filter(c=>c.prosePriceRelationship?.relationship.phase==='INTRO').every(c=>c.commercial.type==='INTRO_PROMOTION'&&c.billingPeriod===null));assert(r.rows.filter(c=>c.amountNormalized==='0').every(c=>r.decisions.get(c.candidateId).status==='V2_VERIFICATION_BLOCKED'));assert(r.rows.filter(c=>c.sourceType==='HTML'&&paid(c)).every(c=>!c.blockingReasons.length));assert.deepEqual(analyze(body({visible:true})).plans.map(p=>p.monthlyPlanId),r.plans.map(p=>p.monthlyPlanId));});
for(const missing of ['authority','geo'])test('visible relationship still requires independent '+missing,()=>{const r=analyze(body({visible:true}),{[missing]:false});assert([...r.decisions.values()].every(d=>d.status==='V2_VERIFICATION_BLOCKED'));});
test('officialDisclaimer is supported; arbitrary text/value/dictionary leaves remain excluded',()=>{for(const v of [{text:renewal},{value:renewal},{translations:{membership_terms:renewal}},{fields:{text:renewal}},{fields:{legalText:[{fields:{value:renewal}}]}}])assert.equal(extract(script(v)).candidates.length,0);assert.equal(extract(script({officialDisclaimer:renewal})).candidates.length,4);assert.equal(extract('<script type="application/json">'+JSON.stringify(legal(renewal))+'</script>').candidates.length,0);});
test('content-model strings retain field, character, depth and price bounds',()=>{assert.equal(extract(script(legal('x'.repeat(proseBounds.text+1)+renewal))).candidates.length,0);assert.equal(extract(script(Array.from({length:100},()=>legal(renewal)))).candidates.length,proseBounds.jsonFields*4);assert.equal(extract(script(legal(Array.from({length:17},()=> '10 €/month (Plan A)').join(' and ')))).candidates.length,0);let v=legal(renewal);for(let i=0;i<40;i++)v={x:v};assert.equal(extract(script(v)).candidates.length,0);});
