import test from 'node:test';import assert from 'node:assert/strict';
import {hash} from './extract.mjs';import {deriveEvidence,verifyCandidate,verifyIdentity} from '../verification/gate.mjs';import {selectMonthlyPlans} from './commercial.mjs';
const offer=(country='DE',currency='EUR',price=10)=>({name:'Plan Basic',price,priceCurrency:currency,billingPeriod:'MONTH',recurring:true,...(country?{country}:{})});
function run(offers,{authority=true}={}){const body=JSON.stringify({offers}),bodyHash=hash(body),context={bodyHash,service:'fixture',market:'DE',authority,sourceOccurrences:[{id:'s',url:'https://provider.example/plans'}],geoEvidence:[]},d=deriveEvidence(body,context),receipt={intact:true,bodyHash,service:'fixture',serviceEstablished:authority,bindingEstablished:true},decisions=new Map(d.rows.map(c=>[c.candidateId,verifyCandidate(c,d,receipt)])),plans=selectMonthlyPlans(d.rows);return {d,decisions,plans,verified:plans.map(p=>verifyIdentity(p,decisions))};}
for(const [country,currency]of [['AU','EUR'],['CA','CAD'],['AU','AUD'],['AT','EUR']])test('explicit '+country+' offer remains retained without conflicting with DE identity',()=>{const r=run([offer(),offer(country,currency,20)]);assert.equal(r.d.rows.length,2);assert.equal(r.plans.length,1);assert.deepEqual(r.plans[0].amounts,[['10','EUR']]);assert.equal(r.verified[0].status,'V2_VERIFIED');assert.equal([...r.decisions.values()].find(x=>x.amount==='20').fields.market.status,'BLOCKED');});
for(const country of ['DE',null,['DE','AU']])test('overlapping or unknown scope remains conflicting '+country,()=>{const r=run([offer(),offer(country,'EUR',20)]);assert(r.verified.every(x=>x.status==='V2_VERIFICATION_BLOCKED'));});
test('foreign-only availability produces no DE monthly identity',()=>{const r=run([offer('AU')]);assert.equal(r.plans.length,0);assert.equal(r.d.rows.length,1);});
test('foreign identity-only data does not affect DE price',()=>{assert.equal(run([offer(),{name:'Plan Basic',country:'AU'}]).verified[0].status,'V2_VERIFIED');});
test('global foreign fallback is retained but not a DE plan',()=>{const r=run([offer(),{fallback:offer('AU','AUD',30)}]);assert.equal(r.d.rows.length,2);assert.equal(r.verified[0].status,'V2_VERIFIED');});
test('authority is still required',()=>{assert(run([offer(),offer('AU','EUR',20)],{authority:false}).verified.every(v=>v.status==='V2_VERIFICATION_BLOCKED'));});
test('zero cannot become eligible through market isolation',()=>{assert(run([offer('DE','EUR',0),offer('AU','EUR',20)]).verified.every(v=>v.status==='V2_VERIFICATION_BLOCKED'));});
test('source integrity remains mandatory',()=>assert.throws(()=>deriveEvidence('{}',{bodyHash:'bad',market:'DE',authority:true}),/PROVENANCE_INTEGRITY_FAILURE/));
