import {assertOffline} from '../offline-replay/offline-guard.mjs';
import fs from 'node:fs';import assert from 'node:assert/strict';
import {readOccurrence,statuses} from '../offline-replay/corpus.mjs';
import {hash,monetary} from './extract.mjs';import {boundedOwnership} from './component-ownership.mjs';import {scopeOfferRole,repairOfferConflicts,regradeScoped} from './offer-roles.mjs';import {csv} from './run.mjs';
import {prepareCommercialSource,classifyCommercial,commercialIdentity,selectMonthlyPlans,commercialTypes} from './commercial.mjs';
const tally=(rows,key)=>Object.fromEntries([...new Set(rows.map(key))].sort().map(k=>[k,rows.filter(r=>key(r)===k).length]));
// Re-read a deduplicated price using its smallest intact monetary phrase, not
// only the leaf containing digits. Never climb outside the proven price owner.
export function occurrenceContext(candidate,source,path){
 const n=source?.nodes.get(path),owner=source?.nodes.get(candidate.qualifierPreservation?.ownerPath);
 if(!n)return {text:'',path};
 const p=n.parent,ms=p?monetary(p.text):[];
 if(owner&&p&&p.start>=owner.start&&p.end<=owner.end&&p.text.length<=250&&ms.length===1&&ms[0].amount===candidate.amountNormalized&&ms[0].currencyRaw===candidate.currencyRaw){
  const parentPath=[...source.nodes].find(([,v])=>v===p)?.[0];return {text:p.text,path:parentPath,pricePath:path,bodyHash:source.bodyHash};
 }
 return {text:n.text,path,pricePath:path,bodyHash:source.bodyHash};
}
export function runMonthly({inputDirectory,corpusDirectory,outputDirectory,offerRoleRepair=false,componentOwnershipRepair=false}){assert(!fs.existsSync(outputDirectory),'NEW_OUTPUT_DIRECTORY_REQUIRED');const names=fs.readdirSync(inputDirectory).filter(n=>n.endsWith('.json')||n.endsWith('.csv')).sort(),hashes=Object.fromEntries(names.map(n=>[n,hash(fs.readFileSync(inputDirectory+'/'+n,'utf8'))]));const read=n=>JSON.parse(fs.readFileSync(inputDirectory+'/'+n+'.json'));const ss=JSON.parse(fs.readFileSync(corpusDirectory+'/sources.json')),sourceHash=hash(fs.readFileSync(corpusDirectory+'/sources.json','utf8'));const sources=new Map(ss.sources.map(s=>[s.sha256,s])),cs=read('candidates'),fsx=read('facts'),cache=new Map(),sourceResults=[];
 if(offerRoleRepair||componentOwnershipRepair){
  const roleBaseline=new Map();
  for(const c of cs.filter(c=>c.factId)){
   if(!cache.has(c.bodyHash)){const s=sources.get(c.bodyHash),o=s?.occurrences.find(o=>c.sourceOccurrenceIds.includes(o.id));try{const r=readOccurrence(o,process.cwd());assert.equal(r.status,statuses.intact);assert.equal(r.hash,c.bodyHash);cache.set(c.bodyHash,prepareCommercialSource(r.body,r.hash));sourceResults.push({bodyHash:c.bodyHash,sourceOccurrenceId:o.id,record:o.record,status:'HASH_VERIFIED_ANALYZED'});}catch(e){cache.set(c.bodyHash,null);sourceResults.push({bodyHash:c.bodyHash,status:'UNAVAILABLE',reason:e.message});}}
   if(componentOwnershipRepair)boundedOwnership(c,cache.get(c.bodyHash));
   roleBaseline.set(c.candidateId,structuredClone(c));
   if(offerRoleRepair)scopeOfferRole(c,cache.get(c.bodyHash));
  }
  if(offerRoleRepair){repairOfferConflicts(cs);for(const c of cs.filter(c=>c.factId))regradeScoped(c,roleBaseline.get(c.candidateId));}
 }
 for(const c of cs){if(!c.factId){c.commercial={type:'UNRESOLVED',strongRecurringMonthly:false,reasons:['NO_MONETARY_EXPRESSION']};continue;}if(!cache.has(c.bodyHash)){const s=sources.get(c.bodyHash),o=s?.occurrences.find(o=>c.sourceOccurrenceIds.includes(o.id));try{const r=readOccurrence(o,process.cwd());assert.equal(r.status,statuses.intact);assert.equal(r.hash,c.bodyHash);cache.set(c.bodyHash,prepareCommercialSource(r.body,r.hash));sourceResults.push({bodyHash:c.bodyHash,sourceOccurrenceId:o.id,record:o.record,status:'HASH_VERIFIED_ANALYZED'});}catch(e){cache.set(c.bodyHash,null);sourceResults.push({bodyHash:c.bodyHash,status:'UNAVAILABLE',reason:e.message});}}
 const source=cache.get(c.bodyHash);c.commercial=classifyCommercial(c,source);
 if(!source){c.commercial.type='UNRESOLVED';c.commercial.strongRecurringMonthly=false;c.commercial.reasons.push('BODY_UNAVAILABLE');}
 // Retain and inspect every deduplicated raw occurrence. Do not assume that equal
 // text/amount means equal billing semantics in another enclosing structure.
 const occurrenceTypes=[];for(const occurrence of c.discoveryOccurrences??[]){const n=source?.nodes.get(occurrence.structuredPath);if(!n||occurrence.structuredPath===c.structuredPath)continue;let owner=n;while(owner.parent&&!(owner.headings?.length===1&&owner.headings[0].text.trim().toLowerCase()===String(c.product).trim().toLowerCase()))owner=owner.parent;const boundPath=c.componentOwnership?.occurrences.find(p=>p.priceRef.path===occurrence.structuredPath)?.componentPath;const ownerPath=boundPath??(owner.headings?.length===1&&owner.headings[0].text.trim().toLowerCase()===String(c.product).trim().toLowerCase()?[...source.nodes].find(([,x])=>x===owner)?.[0]:null);const phrase=occurrenceContext(c,source,occurrence.structuredPath);const alternate=classifyCommercial({...c,structuredPath:occurrence.structuredPath,normalizedEvidenceSnippet:phrase.text,qualifierPreservation:{...c.qualifierPreservation,ownerPath}},source);occurrenceTypes.push({path:occurrence.structuredPath,type:alternate.type,context:phrase,evidence:alternate.evidence});}
 c.commercial.additionalOccurrences=occurrenceTypes;
 if(occurrenceTypes.some(o=>o.type!==c.commercial.type)){c.commercial.type='UNRESOLVED';c.commercial.strongRecurringMonthly=false;c.commercial.reasons.push('CONFLICTING_OR_UNRESOLVED_OCCURRENCE_BILLING');c.commercial.monthlyBlockers.push('CONFLICTING_OR_UNRESOLVED_OCCURRENCE_BILLING');}
 c.commercialOfferId='commercial-offer:'+commercialIdentity(c);
 }
 const cm=new Map(cs.map(c=>[c.candidateId,c]));for(const f of fsx){const rows=f.candidateIds.map(id=>cm.get(id)),types=[...new Set(rows.map(c=>c.commercial.type))];const established=types.filter(t=>t!=='UNRESOLVED');if(offerRoleRepair||componentOwnershipRepair){f.verificationLevel=Math.max(...rows.map(c=>c.verificationLevel));if(['CONFLICTING','UNRESOLVED','TASK_ONLY'].includes(f.marketEvidenceType))f.verificationLevel=Math.min(2,f.verificationLevel);}if(componentOwnershipRepair)f.ownershipInterpretations=rows.filter(c=>c.componentOwnership).map(c=>({candidateId:c.candidateId,product:c.product,providerProductId:c.componentOwnership.providerProductId,evidence:c.componentOwnership}));f.commercial={type:established.length===1?established[0]:'UNRESOLVED',supportTypes:types.sort(),strongRecurringMonthly:established.length===1&&established[0]==='RECURRING_MONTHLY'&&rows.some(c=>c.commercial.strongRecurringMonthly),commercialOfferIds:[...new Set(rows.map(c=>c.commercialOfferId))].sort(),ambiguity:established.length>1?'CONFLICTING_COMMERCIAL_REPRESENTATIONS':null};}
 const monthly=selectMonthlyPlans(cs.filter(c=>c.factId)),controls={};for(const name of ['historical-49','positive-controls','concern-controls'])controls[name]=read(name).map(r=>{const matches=r.exactMatches.length?r.exactMatches:r.ownershipMatches;const rows=matches.map(id=>cm.get(id)),types=[...new Set(rows.map(c=>c.commercial.type))];return {...r,...((offerRoleRepair||componentOwnershipRepair)?{highestLevel:Math.max(0,...r.exactMatches.map(id=>cm.get(id).verificationLevel))}:{}),monetaryMatchCommercialTypes:[...new Set(r.monetaryMatches.map(id=>cm.get(id).commercial.type))].sort(),commercialTypes:types,commercialType:types.length===1?types[0]:'UNRESOLVED',commercialMatchBasis:r.exactMatches.length?'EXACT_MATCH':r.ownershipMatches.length?'OWNERSHIP_MATCH':'NO_OWNED_MATCH',strongRecurringMonthly:r.exactMatches.some(id=>cm.get(id).commercial.strongRecurringMonthly),monthlyPlanIds:monthly.filter(p=>p.candidateIds.some(id=>matches.includes(id))).map(p=>p.monthlyPlanId)};});
 const services=[...new Set(fsx.map(f=>f.service))].sort();const byService=services.map(service=>{const a=fsx.filter(f=>f.service===service),plans=monthly.filter(p=>p.service===service);return {service,totalFacts:a.length,types:tally(a,f=>f.commercial.type),strongRecurringMonthlyFacts:a.filter(f=>f.commercial.strongRecurringMonthly).length,monthlyPlanIdentities:plans.length,strongMonthlyPlanIdentities:plans.filter(p=>p.strongRecurringMonthly).length,plans:plans.map(p=>({market:p.market,plan:p.plan,providerPlanId:p.providerPlanId,status:p.status}))};});
 const unresolved=cs.filter(c=>c.factId&&(!c.commercial.strongRecurringMonthly)&&(c.commercial.type==='RECURRING_MONTHLY'||c.commercial.type==='UNRESOLVED')).map(c=>({candidateId:c.candidateId,factId:c.factId,service:c.service,market:c.market,plan:c.product,amount:c.amountNormalized,currency:c.currency,commercialType:c.commercial.type,reasons:c.commercial.monthlyBlockers}));
 const summary={version:'EXPERIMENTAL_MONTHLY_DOMAIN_V1',productionVerified:false,totalFacts:fsx.length,types:tally(fsx,f=>f.commercial.type),strongRecurringMonthlyFacts:fsx.filter(f=>f.commercial.strongRecurringMonthly).length,monthlyPlanIdentities:monthly.length,strongMonthlyPlanIdentities:monthly.filter(p=>p.strongRecurringMonthly).length,canonicalConflicts:monthly.filter(p=>p.status.startsWith('CONFLICTING_MONTHLY')).length,byService,controls:Object.fromEntries(Object.entries(controls).map(([k,rs])=>[k,{total:rs.length,monetaryMatches:rs.filter(r=>r.monetaryMatches.length).length,statuses:tally(rs,r=>r.status),types:tally(rs,r=>r.commercialType),strongRecurringMonthly:rs.filter(r=>r.strongRecurringMonthly).length,falseStrongMonthly:rs.filter(r=>r.concern&&r.strongRecurringMonthly).length}])),sourceBodies:sourceResults.length,sourceFailures:sourceResults.filter(s=>s.status!=='HASH_VERIFIED_ANALYZED'),unresolvedByService:tally(unresolved,r=>r.service),unresolvedReasons:tally(unresolved.flatMap(r=>r.reasons.map(reason=>({reason}))),r=>r.reason),offline:assertOffline()};
 const baseline=read('candidates');for(const old of baseline){const current=cm.get(old.candidateId);for(const k of Object.keys(old)){if((offerRoleRepair||componentOwnershipRepair)&&['verificationLevel','blockingReasons','decisionReason','qualifierEvidence','qualifierPreservation','qualifierAmbiguous'].includes(k))continue;if(componentOwnershipRepair&&['product','plan','ownershipAmbiguous','crossCardRisk','productOwnerEvidence','qualifier','billingPeriod','promotionOrTrial'].includes(k))continue;if(componentOwnershipRepair&&k==='attribution'){const {productOwnershipEstablished:p,productOwnerEvidence:q,...rest}=current[k],{productOwnershipEstablished:a,productOwnerEvidence:b,...prior}=old[k];assert.deepEqual(rest,prior);continue;}assert.deepEqual(current[k],old[k],k);}}assert(cs.filter(c=>c.blockingReasons.includes('STRUCTURED_VISIBLE_CURRENCY_CONTEXT_CONFLICT')).every(c=>c.verificationLevel<3&&!c.commercial.strongRecurringMonthly));assert(controls['concern-controls'].every(c=>!c.strongRecurringMonthly));
 const manifest={version:summary.version,inputDirectory,corpusDirectory,inputHashes:hashes,sourceIndexHash:sourceHash,productionVerified:false,baselineEvidenceAndGradesUnchanged:!offerRoleRepair&&!componentOwnershipRepair,offerRoleRepair,componentOwnershipRepair,historicalLocatorsRequired:false,commercialTypes,method:'READ_ALL_PERSISTED_CANDIDATES_AND_HASH_VERIFIED_OWNING_SOURCE_STRUCTURE_NO_REEXTRACTION',offline:assertOffline()};const outputs={'manifest.json':manifest,'candidates.json':cs,'facts.json':fsx,'bindings.json':read('bindings'),'observations.json':read('observations'),'sources-analyzed.json':sourceResults,'monthly-plan-inventory.json':monthly,'unresolved-monthly.json':unresolved,'canonical-conflicts.json':monthly.filter(p=>p.status.startsWith('CONFLICTING_MONTHLY')),'summary.json':summary,...Object.fromEntries(Object.entries(controls).map(([k,v])=>[k+'.json',v]))};fs.mkdirSync(outputDirectory,{recursive:true});for(const[n,v]of Object.entries(outputs))fs.writeFileSync(outputDirectory+'/'+n,JSON.stringify(v,null,2)+'\n');fs.writeFileSync(outputDirectory+'/candidates.csv',csv(cs));fs.writeFileSync(outputDirectory+'/monthly-plan-inventory.csv',csv(monthly));for(const[n,h]of Object.entries(hashes))assert.equal(hash(fs.readFileSync(inputDirectory+'/'+n,'utf8')),h);assert.equal(hash(fs.readFileSync(corpusDirectory+'/sources.json','utf8')),sourceHash);return summary;}
