import test from 'node:test';import assert from 'node:assert/strict';
import {hash} from './extract.mjs';import {deriveEvidence} from '../verification/gate.mjs';import {reconstructOfferIntelligence} from '../intelligence/offer-intelligence.mjs';
function run(text){const body='<article data-plan="Basic"><h2>Basic</h2><p>'+text+'</p></article>',bodyHash=hash(body),context={bodyHash,service:'fixture',market:'FI',authority:true,sourceOccurrences:[{id:'s',url:'https://provider.example/plans'}]},receipt={intact:true,bodyHash,service:'fixture',serviceEstablished:true,bindingEstablished:true};return {rows:deriveEvidence(body,context).rows,offers:reconstructOfferIntelligence({body,context,receipt,sourceUrl:'https://provider.example/plans'}).offers};}
for(const text of ['value ca 169 € / 12 months','värde ca 169 €/12 månader'])test('benefit interval and contextual role survive: '+text,()=>{const r=run(text);assert.equal(r.rows[0].commercial.billingInterval?.normalized,'P12M');assert.equal(r.rows[0].commercial.nonPrincipalRole,'CONTEXTUAL_VALUE');assert(r.offers.every(o=>o.confidence==='LOW'));});
for(const text of ['Membership 133 € / 12 months','Membership 133 €/12 månader'])test('twelve calendar months never become one: '+text,()=>{const r=run(text);assert.equal(r.rows[0].commercial.billingInterval?.normalized,'P12M');assert.notEqual(r.rows[0].commercial.type,'RECURRING_MONTHLY');});
for(const text of ['Annual membership EUR 120, works out as EUR 10/month','EUR 10/month installment payment','EUR 10/month credit','Monthly allowance worth EUR 10/month','Financial revenue EUR 10/month'])test('non-principal amount cannot become a recurring charge: '+text,()=>{assert(run(text).offers.every(o=>o.confidence==='LOW'));});
test('owned genuine monthly renewal remains legitimate',()=>{const r=run('12.99 €/month, renews every month');assert.equal(r.rows[0].commercial.billingInterval.normalized,'P1M');assert(r.offers.some(o=>o.confidence==='HIGH'));});
test('monthly and annual alternatives preserve separate cadence after replay serialization',()=>{const body='<article data-plan="Basic"><h2>Basic</h2><p>EUR 12/month, renews monthly</p></article><article data-plan="Plus"><h2>Plus</h2><p>EUR 133 / 12 months</p></article>',context={bodyHash:hash(body),service:'fixture',market:'FI',authority:true};const first=deriveEvidence(body,context),replayed=deriveEvidence(body,JSON.parse(JSON.stringify(context)));assert.deepEqual(replayed,first);const monthly=first.rows.find(c=>c.amountNormalized==='12'),annual=first.rows.find(c=>c.amountNormalized==='133');assert.equal(monthly.commercial.type,'RECURRING_MONTHLY');assert.equal(monthly.commercial.billingInterval.normalized,'P1M');assert.equal(annual.commercial.type,'ANNUAL_RECURRING');assert.equal(annual.commercial.billingInterval.normalized,'P12M');assert.equal(annual.commercial.cadenceFamily,null);});
test('non-billing duration is not a monthly billing token',()=>{const r=run('värde ca 169 € over 12 månader');assert.notEqual(r.rows[0].commercial.type,'RECURRING_MONTHLY');assert.equal(r.rows[0].commercial.billingInterval.normalized,'P12M');});
import {adjudicateProviderPrice} from '../intelligence/provider-price-adjudication.mjs';import {prepareCommercialSource} from './commercial.mjs';
test('re-derived contextual veto defeats legacy monthly labels during retained adjudication',()=>{const body='<article data-plan="Basic"><h2>Basic</h2><p>value ca EUR 169 / 12 months</p></article>',bodyHash=hash(body),derived=deriveEvidence(body,{bodyHash,service:'fixture',market:'FI',authority:true}),old=structuredClone(derived.rows[0]);Object.assign(old.commercial,{type:'RECURRING_MONTHLY',ordinaryMonthly:true,nonPrincipalRole:null,reasons:[],billingInterval:{unit:'MONTH',value:1,normalized:'P1M',recurringPresentation:true}});const o=adjudicateProviderPrice(old,derived,{intact:true,bodyHash,service:'fixture',serviceEstablished:true,bindingEstablished:true},{body,sourceUrl:'https://provider.example/plans',source:prepareCommercialSource(body,bodyHash)});assert.equal(o.trustworthy,false);assert(o.blockers.includes('CONTEXTUAL_MONETARY_VALUE_NOT_CHARGE'));});
