import test from 'node:test';import assert from 'node:assert/strict';
import {hash} from './extract.mjs';
import {deriveEvidence,verifyCandidate,verifyIdentity,gateVersion} from '../verification/gate.mjs';
import {selectMonthlyPlans} from './commercial.mjs';
import {reconstructOfferIntelligence} from '../intelligence/offer-intelligence.mjs';
import {retainedPricingSummary} from '../intelligence/recurring-price-eligibility.mjs';
const renewal='Plan Basic for 3 months total 5 €. After the first 3 months the membership renews monthly at 11.99 EUR/month (Plan Basic) or 21.99 EUR/month (Plan Plus) unless cancelled.';
function embedded(text,{market,raw=false}={}){const value=raw?{amount:11.99}:{text};return '<script id="__NEXT_DATA__" type="application/json">'+JSON.stringify({props:{pageProps:{fields:{legalText:[{fields:{variations:[{fields:{...value,...(market?{country:market}:{})}}]}}]}}}})+'</script>';}
function run(body,{authority=true}={}){const bodyHash=hash(body),sourceUrl='https://provider.example/de/plans',context={bodyHash,service:'fixture',market:'DE',authority,sourceOccurrences:[{id:'s',url:sourceUrl}],geoEvidence:[]},receipt={intact:true,bodyHash,service:'fixture',serviceEstablished:authority,bindingEstablished:true};const d=deriveEvidence(body,context),decisions=d.rows.map(c=>verifyCandidate(c,d,receipt));return {d,decisions,offers:reconstructOfferIntelligence({body,context,receipt,sourceUrl}).offers};}
const paid=r=>r.decisions.filter(d=>['11.99','21.99'].includes(d.amount));
test('contractual content-only relationship is sufficient with explicit offer market; presentation is corroboration',()=>{const r=run(embedded(renewal,{market:'DE'}));assert.equal(paid(r).length,2);assert(paid(r).every(d=>d.status==='V2_VERIFIED'&&Object.values(d.proof).every(x=>x==='ESTABLISHED')));assert(r.offers.filter(o=>['11.99','21.99'].includes(o.amount)).every(o=>o.confidence==='HIGH'&&o.market==='DE'));assert.equal(r.decisions.find(d=>d.amount==='5').status,'V2_VERIFICATION_BLOCKED');});
test('missing market is only a market proof failure, not identity, promotion or contradiction',()=>{const r=run(embedded(renewal));for(const d of paid(r)){assert.deepEqual(d.blockers,['MARKET_NOT_INDEPENDENTLY_VERIFIED']);assert.deepEqual(Object.entries(d.proof).filter(([,v])=>v!=='ESTABLISHED').map(([k])=>k),['MARKET_SCOPE']);}assert(r.offers.filter(o=>['11.99','21.99'].includes(o.amount)).every(o=>o.market===null&&!o.exposure.marketTargeting));});
test('wrong explicit market never becomes a DE claim',()=>{const r=run(embedded(renewal,{market:'FR'}));assert(paid(r).every(d=>d.fields.market.status==='BLOCKED'&&d.fields.conflicts.status==='BLOCKED'));assert(r.offers.every(o=>o.market!=='DE'&&!o.exposure.marketTargeting));});
test('missing authority remains blocking even with valid source text and market',()=>{assert.throws(()=>run(embedded(renewal,{market:'DE'}),{authority:false}),/ADMITTED_PROVIDER_RECEIPT_REQUIRED/);});
test('arbitrary numeric JSON does not gain textual ownership',()=>{const r=run(embedded('',{market:'DE',raw:true}));assert(r.decisions.length);assert(r.decisions.every(d=>d.status==='V2_VERIFICATION_BLOCKED'));assert(r.offers.every(o=>o.confidence==='LOW'));});
for(const text of ['0 €/month (Plan Basic)','Plan Basic is included with Membership Other at 0 €/month','Plan Basic at 10 €/month credit','Plan Basic at 10 €/month discount','Plan Basic at 10 €/month tax','from 10 €/month (Plan Basic)','10 €/month (Plan Basic or Plan Plus)'])test('non-price/ambiguous evidence cannot become trustworthy recurring price: '+text,()=>{const r=run(embedded(text,{market:'DE'}));assert(r.offers.every(o=>o.confidence==='LOW'));assert(r.decisions.every(d=>d.status==='V2_VERIFICATION_BLOCKED'));});
test('zero and separate membership cannot poison a paid textual assertion',()=>{const r=run(embedded('Plan Basic renews at 11.99 €/month; Plan Basic is included with Membership Other at 0 €/month; Membership Other sold separately at 39 €/month',{market:'DE'}));assert.deepEqual(r.decisions.filter(d=>d.status==='V2_VERIFIED').map(d=>[d.plan,d.amount]),[['Plan Basic','11.99'],['Membership Other','39']]);assert.equal(r.decisions.find(d=>d.amount==='0').status,'V2_VERIFICATION_BLOCKED');});
test('conflicting same-offer prices remain unresolved',()=>{const r=run(embedded('10 €/month (Plan Basic) and 20 €/month (Plan Basic)',{market:'DE'}));assert(r.decisions.every(d=>d.status==='V2_VERIFICATION_BLOCKED'));assert(r.offers.every(o=>o.confidence==='LOW'));});
test('new evidence does not revive quarantined or stale retained summaries',()=>{const r=run(embedded(renewal,{market:'DE'})),o=r.offers.find(o=>o.amount==='11.99'),t={service:'fixture',market:'DE'};assert(retainedPricingSummary(t,[o],{}));assert.equal(retainedPricingSummary({...t,quarantinedVerified:[o]},[o],{}),null);assert.equal(retainedPricingSummary(t,[{...o,stale:true}],{}),null);});
test('prior semantics cannot be substituted for current verification',()=>{const r=run(embedded(renewal,{market:'DE'})),p=selectMonthlyPlans(r.d.rows).find(p=>p.plan==='Plan Basic'),old=new Map(r.decisions.map(d=>[d.candidateId,{...d,version:'V2_FIELD_VERIFICATION_V3'}]));assert.equal(gateVersion,'V2_FIELD_VERIFICATION_V4');assert.equal(verifyIdentity(p,old).status,'V2_VERIFICATION_BLOCKED');});
test('a raw recurring amount with all other facts but no owner fails only identity proof',()=>{const r=run(JSON.stringify({price:10,priceCurrency:'EUR',billingPeriod:'MONTH',recurring:true,country:'DE'}));assert.equal(r.decisions.length,1);assert.deepEqual(Object.entries(r.decisions[0].proof).filter(([,v])=>v==='UNRESOLVED').map(([k])=>k),['IDENTITY']);assert(r.offers.every(o=>o.confidence==='LOW'));});
test('intro total cannot establish a recurring role or cadence',()=>{const r=run(JSON.stringify({name:'Basic',price:10,priceCurrency:'EUR',description:'first 3 months total EUR 10',country:'DE'}));assert(r.decisions.every(d=>d.proof.COMMERCIAL_MEANING==='UNRESOLVED'&&d.status==='V2_VERIFICATION_BLOCKED'));assert(r.offers.every(o=>o.confidence==='LOW'));});
test('tax-inclusive charge remains a price, unlike a tax component',()=>{const r=run(embedded('10 €/month (Plan Basic) including tax',{market:'DE'}));assert(r.decisions.some(d=>d.status==='V2_VERIFIED'));});
