import {assertOffline} from '../offline-replay/offline-guard.mjs';
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';
import {readOccurrence,statuses} from '../offline-replay/corpus.mjs';
import {resolveGeoOccurrence} from './geo-evidence.mjs';
import {attribute,combineMarketEvidenceTypes} from './attribution.mjs';
import {inspectProviderMarket,providerEvidenceFor} from './provider-market.mjs';
import {extract,grade,hash,normalizeText,amount} from './extract.mjs';
export const version='RESEARCH_V2_OFFLINE_RECOVERY_EXPERIMENT_MARKET_ATTRIBUTION_V3';
const cmp=(a,b)=>a<b?-1:a>b?1:0;
const unique=x=>[...new Set(x)].sort(cmp);
const counts=(rows,key)=>Object.fromEntries(unique(rows.map(key)).map(k=>[k,rows.filter(r=>key(r)===k).length]));
const label=x=>normalizeText(x).toLowerCase();
const factKey=c=>[c.service,c.market,label(c.product),c.amountNormalized,c.currency,c.billingPeriod,c.promotionOrTrial,c.qualifier,...(c.attribution?.blockingReasons.includes('PRODUCT_FROM_COUNTRY_LABEL')?[{unresolvedCountryOwner:c.attribution.marketOwnerEvidence.map(e=>e.code).sort()}]:[])];
const isExact=l=>['EXACT_RAW_QUOTE','EXACT_RETAINED_FRAGMENT'].includes(l?.status);
export function csv(rows){const keys=unique(rows.flatMap(r=>Object.keys(r)));const cell=x=>{let s=x===undefined||x===null?'':typeof x==='object'?JSON.stringify(x):String(x);if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';};return '\ufeff'+[keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n')+'\r\n';}
export function run({corpusDirectory,outputDirectory,root=process.cwd(),progress=()=>{},geoEvidenceFile=null,providerDeclaredEnabled=false}){
 const geoIndex=geoEvidenceFile?new Map(JSON.parse(fs.readFileSync(geoEvidenceFile)).map(r=>[r.occurrenceId,r])):null,geoCache=new Map(),geoIndexHash=geoEvidenceFile?hash(fs.readFileSync(geoEvidenceFile)):null;
 const inputNames=['manifest','sources','rejections','positive','recovery','rawLocators'];const inputs={},inputHashes={};for(const k of inputNames){const raw=fs.readFileSync(path.join(corpusDirectory,k+'.json'));inputHashes[k]=hash(raw.toString());inputs[k]=JSON.parse(raw);}
 assert.equal(inputs.manifest.generation.truthEvaluation,'NONE');assert.equal(inputs.rejections.rows.length,622);assert.equal(inputs.positive.rows.length,114);assert.equal(inputs.recovery.rows.length,49);
 const loss=new Set(inputs.rawLocators.rows.map(r=>r.observationId));assert.equal(loss.size,147);
 const populations=[...inputs.rejections.rows.map(r=>({...r,kind:r.original.observation.value===null?'NULL_REJECTED':'CONCRETE_REJECTED',value:r.original.observation.value,links:r.evidence.sources})),...inputs.positive.rows.map(r=>({...r,kind:'POSITIVE_CONTROL',links:r.occurrences.flatMap(o=>o.evidence.flatMap(e=>e.sources.map(l=>({...l,evidenceId:e.evidenceId}))))})),...inputs.recovery.rows.map(r=>({...r,kind:'HISTORICAL_49',value:r.expectedShape,links:r.evidence}))];
 const populationById=new Map(populations.map(r=>[r.id,r]));const sourceMap=new Map(inputs.sources.sources.map(s=>[s.key,s]));const occurrenceMap=new Map(inputs.sources.sources.flatMap(s=>s.occurrences.map(o=>[o.id,{...o,sourceKey:s.key}])));
 const relevant=new Map();for(const r of populations)for(const l of r.links){const key=JSON.stringify([l.sourceKey,r.service,r.market]);if(!relevant.has(key))relevant.set(key,{sourceKey:l.sourceKey,service:r.service,market:r.market,links:[]});const bucket=relevant.get(key);if(!bucket.links.some(x=>x.row.id===r.id&&x.link.occurrenceId===l.occurrenceId))bucket.links.push({row:r,link:l});}
 const bodyCache=new Map(),sourceAnalysis=[],candidates=[],bindings=[];let n=0;
 for(const [key,b]of [...relevant].sort(([a],[b])=>cmp(a,b))){const source=sourceMap.get(b.sourceKey);let checked=bodyCache.get(b.sourceKey);if(!checked){const o=occurrenceMap.get(b.links[0].link.occurrenceId);try{checked=readOccurrence(o,root);if(checked.status===statuses.intact){assert.equal(checked.hash,source.sha256);checked.analysis=extract(checked.body);}}catch(e){checked={status:'ANALYSIS_FAILURE',reason:e.message};}bodyCache.set(b.sourceKey,checked);}
  const sourceId=hash(key),occurrences=unique(b.links.map(x=>x.link.occurrenceId));const contexts=occurrences.map(id=>occurrenceMap.get(id));const validContexts=contexts.filter(o=>o?.authority?.status==='CONFIGURED_REVIEWED'&&!o.priceEvidenceExcluded);const marketBound=validContexts.some(o=>o.transportProof?.level==='BRACKET_VERIFIED'&&o.transportProof.before===b.market&&o.transportProof.after===b.market&&o.transportProof.requestedCountry===b.market);
  const sharedMarkets=unique([...relevant.values()].filter(x=>x.sourceKey===b.sourceKey&&x.service===b.service).map(x=>x.market));
  const geoEvidence=geoIndex&&checked.status===statuses.intact?validContexts.map(o=>{if(!geoCache.has(o.id))geoCache.set(o.id,resolveGeoOccurrence(o,source.sha256,geoIndex,root));return geoCache.get(o.id);}):[];
  const providerMarket=providerDeclaredEnabled&&checked.status===statuses.intact?inspectProviderMarket(checked.body,{bodyHash:source.sha256,sourceOccurrences:validContexts}):{records:[],diagnostics:['BODY_UNAVAILABLE']};
  const context={...(providerDeclaredEnabled?{providerPolicy:true,bodyHash:source?.sha256,sourceOccurrenceIds:occurrences}:{}),...(geoIndex?{geoPolicy:true,geoEvidence}:{}),market:b.market,sharedMarkets,authority:validContexts.length>0,marketBound,excluded:contexts.every(o=>o?.priceEvidenceExcluded),malformed:checked.analysis?.diagnostics.malformedHtml};
  const evaluate=item=>{const attributed=attribute(item,providerDeclaredEnabled?{...context,providerEvidence:providerEvidenceFor(item,providerMarket)}:context);return grade(attributed,(geoIndex||providerDeclaredEnabled)?{...context,marketBound:attributed.attribution.marketApplicabilityEstablished}:context);};
  const raw=checked.analysis?.candidates??[];const buckets=new Map();for(const c of raw){const k=JSON.stringify([c.product,c.amountNormalized,c.currency,c.billingPeriod,c.qualifier,c.promotionOrTrial,c.structuralContainer,c.sourceType]);if(!buckets.has(k))buckets.set(k,[]);buckets.get(k).push(c);}
  if(!buckets.size)buckets.set('NO_FACT',[{product:null,plan:null,amountRaw:null,amountNormalized:null,currency:null,billingPeriod:null,qualifier:[],promotionOrTrial:null,sourceType:contexts[0]?.contentType??null,ownershipAmbiguous:true,rawEvidenceSnippet:null,normalizedEvidenceSnippet:null}]);
  const monetary=raw.length>0;const out=[];const visibleCurrencies=new Set(raw.filter(c=>c.sourceType==='HTML'&&c.currency).map(c=>c.currency));
  for(const [k,items]of buckets){let c=items[0];const cid='candidate:'+hash([sourceId,k]);const historical=b.links.map(x=>x.row);const noFact=k==='NO_FACT';const g=noFact?{...c,verificationLevel:0,blockingReasons:[checked.status===statuses.intact?'NO_MONETARY_EXPRESSION':checked.reason??'BODY_UNAVAILABLE'],decisionReason:checked.status===statuses.intact?'NO_MONETARY_EXPRESSION':checked.reason??'BODY_UNAVAILABLE'}:evaluate(c);
   if(!noFact){const gs=items.map(x=>evaluate(x));g.verificationLevel=Math.min(...gs.map(x=>x.verificationLevel));g.blockingReasons=unique(gs.flatMap(x=>x.blockingReasons));g.qualifierEvidence=items.flatMap(x=>x.qualifierEvidence??[]);g.qualifierPreservation={...g.qualifierPreservation,unresolved:unique(gs.flatMap(x=>x.qualifierPreservation?.unresolved??[]))};}
   const differentOwners=raw.filter(x=>x.amountNormalized===c.amountNormalized&&x.currency===c.currency&&x.normalizedEvidenceSnippet===c.normalizedEvidenceSnippet&&x.product!==c.product);
   if(c.sourceType==='JSON'&&visibleCurrencies.size&&(visibleCurrencies.size>1||!visibleCurrencies.has(c.currency))){g.verificationLevel=Math.min(2,g.verificationLevel);g.blockingReasons.push('STRUCTURED_VISIBLE_CURRENCY_CONTEXT_CONFLICT');}
   if(differentOwners.length){g.verificationLevel=Math.min(2,g.verificationLevel);g.ownershipAmbiguous=true;g.blockingReasons.push('REPEATED_TEXT_DIFFERENT_OWNERS');}
   const conflicts=raw.filter(x=>x.product&&x.product===c.product&&x.currency===c.currency&&x.billingPeriod===c.billingPeriod&&x.promotionOrTrial===c.promotionOrTrial&&JSON.stringify(x.qualifier)===JSON.stringify(c.qualifier)&&x.amountNormalized!==c.amountNormalized);
   if(conflicts.length){g.verificationLevel=Math.min(2,g.verificationLevel);g.blockingReasons.push('MULTIPLE_CONFLICTING_FACTS');}
   g.decisionReason=g.blockingReasons.join('|')||g.decisionReason;
   const candidate={candidateId:cid,factId:noFact?null:'fact:'+hash(factKey({...g,...b})),observationId:historical[0].id,observationIds:unique(historical.map(x=>x.id)),service:b.service,market:b.market,...g,sourceOccurrenceId:occurrences[0],sourceOccurrenceIds:occurrences,bodyHash:source?.sha256??null,bodyAvailable:checked.status===statuses.intact,sourceUrl:contexts[0]?.url??null,occurrenceCount:items.length,discoveryOccurrences:items.map(x=>({structuredPath:x.structuredPath,coordinates:x.discoveryCoordinates})),exactHistoricalOccurrenceKnown:null,exactHistoricalLocatorAvailable:b.links.some(x=>isExact(x.link.locator)),quoteOccurrenceAmbiguous:b.links.some(x=>x.link.locator?.status==='AMBIGUOUS_QUOTE'),sourceMappingAmbiguous:false,currencyAmbiguous:!c.currency,exactOccurrenceKnown:true,historicalLocatorNeededForGrade:false,historicalConcreteRejected:historical.some(x=>x.kind==='CONCRETE_REJECTED'),historicalNullRejected:historical.some(x=>x.kind==='NULL_REJECTED'),historicalPositiveControl:historical.some(x=>x.kind==='POSITIVE_CONTROL'),historicalRecovery49:false,historicalConcernCase:historical.some(x=>x.concern),nullIntactHtmlLocatorLossCase:historical.some(x=>loss.has(x.id)),historicalPopulation:unique(historical.map(x=>x.kind)),bindingMeaning:'SOURCE_FIRST_DISCOVERY; NOT_AN_ASSERTION_THAT_V1_OBSERVED_THIS_CANDIDATE',authorityEstablished:context.authority,marketAttributionEstablished:g.attribution?.marketApplicabilityEstablished??false};
   candidates.push(candidate);out.push(cid);
   for(const {row,link}of b.links)bindings.push({bindingId:'binding:'+hash([cid,row.id,link.occurrenceId]),candidateId:cid,factId:candidate.factId,observationId:row.id,service:row.service,market:row.market,population:row.kind,historicalObservationValue:row.value,taskId:row.taskId??null,attemptId:row.original?.attemptId??null,sourceOccurrenceId:link.occurrenceId,bodyHash:source.sha256,evidenceId:link.evidenceId??null,historicalLocator:link.locator??null,exactHistoricalLocatorAvailable:isExact(link.locator),quoteOccurrenceAmbiguous:link.locator?.status==='AMBIGUOUS_QUOTE',nullIntactHtmlLocatorLossCase:loss.has(row.id)});
  }
  sourceAnalysis.push({...(providerDeclaredEnabled?{providerMarket}:{}),id:sourceId,sourceKey:b.sourceKey,service:b.service,market:b.market,occurrences,status:checked.status,reason:checked.reason??null,bytes:checked.bytes??null,analysisDiagnostics:checked.analysis?.diagnostics??null,monetaryEvidence:monetary,candidateIds:out});if(++n%25===0)progress({sources:n,total:relevant.size});
 }
 const byCandidate=new Map(candidates.map(c=>[c.candidateId,c]));const byObservation=new Map(populations.map(r=>[r.id,[]]));for(const b of bindings){const list=byObservation.get(b.observationId);if(!list.includes(b.candidateId))list.push(b.candidateId);}
 function control(row){let expected=row.value??{};const historicalExpected=expected;
  // Decode the *comparison* formats retained by the forensic manifest. These
  // values never enter source extraction, source selection or candidate grading.
  if(expected.historicalPriceLine){const matches=extract('<li>'+expected.historicalPriceLine.split('(')[0]+'</li>').candidates;if(matches.length===1){const c=matches[0];expected={amount:c.amountNormalized,currency:c.currency,plan:c.product,cadence:c.billingPeriod};}}
  if(expected.historicalStructuredOffer){const o=expected.historicalStructuredOffer;expected={amount:o.offers.price,currency:o.offers.priceCurrency,plan:o.name,cadence:'UNKNOWN'};}
  const cs=(byObservation.get(row.id)??[]).map(id=>byCandidate.get(id)).filter(c=>c.verificationLevel>0);const monetary=cs.filter(c=>c.amountNormalized===amount(expected.amount)&&c.currency===expected.currency);const owned=monetary.filter(c=>label(c.product)===label(expected.plan));const cadence=owned.filter(c=>!expected.cadence||['UNKNOWN','OTHER'].includes(expected.cadence)||c.billingPeriod===expected.cadence);const offer=expected.offerType;const qualifierMatches=c=>offer==='TRIAL'||offer==='PROMOTIONAL'?c.promotionOrTrial==='PROMOTION_OR_TRIAL'&&(!expected.cadenceDescription||expected.cadenceDescription==='Unknown cadence'||c.qualifier.some(q=>label(q).includes(label(expected.cadenceDescription).replace(/^for /,'')))):!c.promotionOrTrial&&!c.qualifier.includes('EXTRA_MEMBER_ADD_ON');
  const exact=cadence.filter(qualifierMatches);return {id:row.id,service:row.service,market:row.market,historicalExpected,expected,concern:row.concern??null,candidateCount:cs.length,monetaryMatches:monetary.map(c=>c.candidateId),ownershipMatches:owned.map(c=>c.candidateId),cadenceMatches:cadence.map(c=>c.candidateId),exactMatches:exact.map(c=>c.candidateId),highestLevel:Math.max(0,...exact.map(c=>c.verificationLevel)),monetaryLevel:Math.max(0,...monetary.map(c=>c.verificationLevel)),status:exact.length?'EXACT_NORMALIZED_MATCH':owned.length?'CADENCE_OR_QUALIFIER_MISMATCH':monetary.length?'OWNERSHIP_MISMATCH':'MISSING_MONETARY_MATCH',falseStrongPromotion:!!row.concern&&exact.some(c=>c.verificationLevel>=3),note:'Matches are post-extraction controls. Source sharing alone is not target recovery. UNKNOWN historical cadence is a comparison wildcard, not inferred cadence.'};}
 const positive=populations.filter(r=>r.kind==='POSITIVE_CONTROL').map(control),historical49=populations.filter(r=>r.kind==='HISTORICAL_49').map(control),concerns=positive.filter(x=>x.concern);
 const targetCandidateIds=new Set(historical49.flatMap(x=>x.exactMatches));for(const id of targetCandidateIds)byCandidate.get(id).historicalRecovery49=true;
 const factsMap=new Map();for(const c of candidates.filter(c=>c.factId)){if(!factsMap.has(c.factId))factsMap.set(c.factId,{factId:c.factId,service:c.service,market:c.market,product:c.product,plan:c.plan,amountNormalized:c.amountNormalized,currency:c.currency,billingPeriod:c.billingPeriod,qualifier:c.qualifier,promotionOrTrial:c.promotionOrTrial,verificationLevel:c.verificationLevel,candidateIds:[],bodyHashes:[],qualifierEvidence:[],attributionEvidence:[],historicalRecovery49:false,productionVerified:false});const f=factsMap.get(c.factId);f.candidateIds.push(c.candidateId);f.bodyHashes.push(c.bodyHash);f.attributionEvidence.push({candidateId:c.candidateId,bodyHash:c.bodyHash,verificationLevel:c.verificationLevel,...c.attribution});f.qualifierEvidence.push(...(c.qualifierEvidence??[]).map(e=>({...e,bodyHash:c.bodyHash,candidateId:c.candidateId})));f.verificationLevel=Math.max(f.verificationLevel,c.verificationLevel);f.historicalRecovery49 ||= c.historicalRecovery49;}
 if(providerDeclaredEnabled)for(const f of factsMap.values()){f.marketEvidenceType=combineMarketEvidenceTypes(f.attributionEvidence.map(e=>e.marketEvidenceType));if(['CONFLICTING','UNRESOLVED','TASK_ONLY'].includes(f.marketEvidenceType))f.verificationLevel=Math.min(2,f.verificationLevel);}
 const facts=[...factsMap.values()].map(f=>({...f,candidateIds:unique(f.candidateIds),bodyHashes:unique(f.bodyHashes)})).sort((a,b)=>cmp(a.factId,b.factId));
 if(providerDeclaredEnabled){for(const row of [...positive,...historical49]){const ids=row.exactMatches.length?row.exactMatches:row.monetaryMatches;row.marketEvidenceType=combineMarketEvidenceTypes(ids.map(id=>byCandidate.get(id)?.attribution?.marketEvidenceType));row.marketEvidenceMatchBasis=row.exactMatches.length?'EXACT_MATCH':row.monetaryMatches.length?'MONETARY_ONLY':'NO_MONETARY_MATCH';}}
 const observationResults=populations.map(r=>{const cs=(byObservation.get(r.id)??[]).map(id=>byCandidate.get(id));return {id:r.id,kind:r.kind,service:r.service,market:r.market,nullIntactHtmlLocatorLossCase:loss.has(r.id),bodyAnalyzed:cs.some(c=>c.bodyAvailable),monetaryEvidence:cs.some(c=>c.verificationLevel>0),highestLevel:Math.max(0,...cs.map(c=>c.verificationLevel)),candidateIds:cs.map(c=>c.candidateId),priorBlocker:r.original?.claimDecision?.reason??null};});
 function subset(test){const rs=observationResults.filter(test),ids=new Set(rs.flatMap(r=>r.candidateIds));const cs=candidates.filter(c=>ids.has(c.candidateId)&&c.verificationLevel>0),fsx=facts.filter(f=>f.candidateIds.some(id=>ids.has(id)));return {observations:rs.length,withBodies:rs.filter(r=>r.bodyAnalyzed).length,withMonetaryEvidence:rs.filter(r=>r.monetaryEvidence).length,withStrongCandidates:rs.filter(r=>r.highestLevel>=3).length,candidates:cs.length,distinctFacts:fsx.length,factsByLevel:counts(fsx,f=>f.verificationLevel),historicalProvenanceWasOnlyCause:'UNKNOWN; historical aggregate claim decisions are not counterfactual experiments'};}
 const summary={version:providerDeclaredEnabled?'RESEARCH_V2_OFFLINE_RECOVERY_COMBINED_MARKET_V5':geoIndex?'RESEARCH_V2_OFFLINE_RECOVERY_GEO_OBSERVED_V4':version,totalCandidateRows:candidates.length,monetaryCandidates:candidates.filter(c=>c.verificationLevel>0).length,distinctCandidateFacts:facts.length,levels:counts(candidates,c=>c.verificationLevel),factLevels:counts(facts,f=>f.verificationLevel),evidenceBindings:bindings.length,uniqueBodiesAnalyzed:[...bodyCache.values()].filter(c=>c.status===statuses.intact&&c.analysis).length,sourceContexts:sourceAnalysis.length,sourceOccurrences:unique(sourceAnalysis.flatMap(s=>s.occurrences)).length,sourceFailures:sourceAnalysis.filter(s=>s.status!==statuses.intact),concrete152:subset(r=>r.kind==='CONCRETE_REJECTED'),null470:subset(r=>r.kind==='NULL_REJECTED'),nullIntact147:subset(r=>r.nullIntactHtmlLocatorLossCase),historical49:{total:49,statuses:counts(historical49,r=>r.status),exactMatchLevels:counts(historical49,r=>r.highestLevel),withMonetaryMatch:historical49.filter(r=>r.monetaryMatches.length).length},positive114:{total:114,statuses:counts(positive,r=>r.status),exactMatchLevels:counts(positive,r=>r.highestLevel),withMonetaryMatch:positive.filter(r=>r.monetaryMatches.length).length},concerns9:{total:concerns.length,falseStrongPromotions:concerns.filter(c=>c.falseStrongPromotion).length},additionalBeyondMatched49:{L2: facts.filter(f=>f.verificationLevel===2&&!f.historicalRecovery49).length,L3:facts.filter(f=>f.verificationLevel===3&&!f.historicalRecovery49).length,L4:facts.filter(f=>f.verificationLevel===4&&!f.historicalRecovery49).length,qualification:'Candidate identities unmatched to historical controls, not proven new canonical prices; names/qualifiers may differ.'},blockers:counts(candidates.flatMap(c=>c.blockingReasons.map(reason=>({reason}))),x=>x.reason),historicalLocatorAbsentStrongCandidates:candidates.filter(c=>c.verificationLevel>=3&&!c.exactHistoricalLocatorAvailable).length,locatorLossSubsetStrongCandidates:candidates.filter(c=>c.verificationLevel>=3&&c.nullIntactHtmlLocatorLossCase).length,provenanceOnlyBlocked:0,offline:assertOffline()};
 candidates.sort((a,b)=>cmp(JSON.stringify([a.service,a.market,a.product??'',-a.verificationLevel,a.amountNormalized??'',a.candidateId]),JSON.stringify([b.service,b.market,b.product??'',-b.verificationLevel,b.amountNormalized??'',b.candidateId])));
 const manifest={version:providerDeclaredEnabled?'RESEARCH_V2_OFFLINE_RECOVERY_COMBINED_MARKET_V5':geoIndex?'RESEARCH_V2_OFFLINE_RECOVERY_GEO_OBSERVED_V4':version,...(geoIndex?{geoEvidenceFile,geoEvidenceIndexHash:geoIndexHash,geoEvidenceValidatedFromOriginalRecords:true}:{}),...(providerDeclaredEnabled?{providerDeclaredEnabled:true,providerMarketEvidenceFromIntactBodies:true}:{}),inputDirectory:corpusDirectory,inputHashes,truthEvaluation:'EXPERIMENTAL_SOURCE_FIRST_CANDIDATES_ONLY',productionVerified:false,phase1GateUnchanged:inputs.manifest.successGate,populations:inputs.manifest.observed,offline:assertOffline(),limits:{sourceBytes:4000000,structuredNodes:300000,candidatesPerBody:20000},method:'LEXICAL_HTML_TREE_AND_JSON_NO_CODE_EXECUTION',currencyPolicy:'ISO codes and unambiguous symbols; ambiguous $/kr/yen only resolved by explicit local ISO code, never geography',historicalLocatorsAreGate:false,controlExpectationsFedToExtractor:false,deterministic:true};
 const artifacts={'manifest.json':manifest,'candidates.json':candidates,'facts.json':facts,'bindings.json':bindings,'positive-controls.json':positive,'concern-controls.json':concerns,'historical-49.json':historical49,'summary.json':summary,'sources-analyzed.json':sourceAnalysis,'observations.json':observationResults};
 const out=path.resolve(outputDirectory),input=path.resolve(corpusDirectory);assert(out!==input&&!out.startsWith(input+path.sep));fs.mkdirSync(out,{recursive:true});for(const [name,obj]of Object.entries(artifacts))fs.writeFileSync(path.join(out,name),JSON.stringify(obj,null,2)+'\n');fs.writeFileSync(path.join(out,'candidates.csv'),csv(candidates));if(geoEvidenceFile)assert.equal(hash(fs.readFileSync(geoEvidenceFile)),geoIndexHash);for(const k of inputNames)assert.equal(hash(fs.readFileSync(path.join(corpusDirectory,k+'.json'),'utf8')),inputHashes[k]);return summary;
}
if(process.argv[1]===new URL(import.meta.url).pathname){const corpusDirectory=process.argv[2],outputDirectory=process.argv[3];assert(corpusDirectory&&outputDirectory,'Usage: node run.mjs CORPUS OUTPUT');console.log(JSON.stringify(run({corpusDirectory,outputDirectory,geoEvidenceFile:process.argv[4]??null,providerDeclaredEnabled:process.argv[5]==='--provider-declared',progress:x=>console.error(JSON.stringify(x))}),null,2));}
