import test from 'node:test';import assert from 'node:assert/strict';import {hash} from './extract.mjs';import {deriveEvidence,verifyCandidate} from '../verification/gate.mjs';
function run(body,{authority=true,market=true}={}){const bodyHash=hash(body),context={bodyHash,service:'fixture',market:'GB',authority,sourceOccurrences:[{id:'source',url:'https://provider.example/plans'}],geoEvidence:market?[{classification:'G1',targetCountry:'GB',geoCountry:'GB',bodyHash}]:[]};const derived=deriveEvidence(body,context),receipt={intact:true,bodyHash,service:'fixture',serviceEstablished:authority,bindingEstablished:true};return {body,context,derived,decisions:derived.rows.map(c=>verifyCandidate(c,derived,receipt))};}
const card=(name,price)=>`<div><h2>${name}</h2><div><span>${price}</span></div><ul><li>Consumer access</li></ul><button>Select</button></div>`;
const form='<div><h3>Digital Monthly</h3><form method="post" action="#"><button type="submit"><span>GBP 10</span><span>/month</span></button></form></div>';
const alternatives='<div><h3>Standard</h3><h4>GBP 9.99/month or GBP 95.88/year</h4><div><button>Add Monthly Plan to Cart</button><button>Add Yearly Plan to Cart</button></div></div>';
for(const [name,body]of [['card',card('Standard','GBP 12/month')],['form',form],['alternative price heading',alternatives]])test('one sufficient provider '+name+' establishes ownership',()=>{const r=run(body);assert(r.decisions.length);assert(r.decisions.every(d=>d.fields.plan.status==='VERIFIED'&&d.fields.ownership.status==='VERIFIED'),JSON.stringify(r.decisions.map(d=>d.blockers)));});
import {reconstructOfferIntelligence} from '../intelligence/offer-intelligence.mjs';
function offers(body){const r=run(body);return reconstructOfferIntelligence({body,context:r.context,receipt:{intact:true,bodyHash:hash(body),service:'fixture',serviceEstablished:true,bindingEstablished:true},sourceUrl:'https://provider.example/plans'}).offers;}
test('explicit named price sentence needs no selection or extra source',()=>{const r=run('<p>Plan Basic at GBP 12.99/month.</p>');assert(r.decisions.some(d=>d.fields.plan.status==='VERIFIED'&&d.fields.ownership.status==='VERIFIED'));});
test('named renewal relationship remains sufficient',()=>{const r=run('<p>Plan Basic renews at GBP 12.99/month.</p>');assert(r.decisions.some(d=>d.fields.plan.status==='VERIFIED'&&d.fields.ownership.status==='VERIFIED'));});
test('monthly and annual branches retain their exact common owner and distinct intervals',()=>{const body='<div><h2>Standard</h2><p>GBP 9.99/month</p><p>GBP 95.88/year</p><button>Choose</button></div>',r=run(body);assert(r.decisions.every(d=>d.fields.plan.status==='VERIFIED'&&d.fields.ownership.status==='VERIFIED'));const os=offers(body);assert.equal(os.find(o=>o.amount==='9.99').billingInterval.normalized,'P1M');assert.equal(os.find(o=>o.amount==='95.88').billingInterval.normalized,'P1Y');});
test('retained source and typed relationship rederive identically after serialization',()=>{const r=run(form),saved=JSON.parse(JSON.stringify(r));assert.deepEqual(deriveEvidence(saved.body,saved.context),r.derived);});
test('two plans never cross-bind',()=>{const r=run(card('Standard','GBP 9.99/month')+card('Plus','GBP 19.99/month'));assert.deepEqual(r.decisions.map(d=>[d.plan,d.amount]),[['Standard','9.99'],['Plus','19.99']]);assert(r.decisions.every(d=>d.fields.ownership.status==='VERIFIED'));});
for(const [label,text,amount]of [['benefit','Benefit value ca GBP 169 / 12 months','169'],['saving','Savings worth GBP 20/month','20'],['equivalent','GBP 10 per month billed yearly','10'],['add-on','GBP 5/month optional add-on','5'],['device','Device purchase GBP 199 one-time payment','199'],['financial','Financial revenue GBP 800/month','800']])test('bound '+label+' does not become principal subscription charge',()=>{const body=card('Standard','GBP 12/month')+card('Other',text);assert(offers(body).filter(o=>o.amount===amount).every(o=>o.confidence==='LOW'));});
for(const [label,body]of [
 ['bare heading adjacency','<div><h2>Some context</h2><p>GBP 12/month</p></div>'],
 ['ambiguous plans','<div><h2>Standard</h2><h2>Premium</h2><p>GBP 12/month</p><button>Select</button></div>'],
 ['unrelated informational action','<div><h2>Report</h2><p>GBP 12/month</p><button>Read more</button></div>'],
 ['outer action cannot bind inner unrelated content','<div><h2>Standard</h2><section><p>GBP 12/month</p></section><button>Select</button></div>'],
 ['navigation','<nav>'+card('Standard','GBP 12/month')+'</nav>'],
 ['footer','<footer>'+card('Standard','GBP 12/month')+'</footer>'],
 ['hidden','<div hidden>'+card('Standard','GBP 12/month')+'</div>'],
 ['disabled selection',card('Standard','GBP 12/month').replace('<button>','<button disabled>')]
])test(label+' remains unresolved',()=>{const r=run(body);assert(r.decisions.every(d=>d.fields.ownership.status==='BLOCKED'));});
test('identity never invents target market',()=>{const r=run(form,{market:false});assert(r.decisions.every(d=>d.fields.ownership.status==='VERIFIED'&&d.fields.market.status==='BLOCKED'&&d.status!=='V2_VERIFIED'));});
test('identity never substitutes for provider authority',()=>{const r=run(form,{authority:false});assert(r.decisions.every(d=>d.fields.ownership.status==='VERIFIED'&&d.fields.service.status==='BLOCKED'&&d.status!=='V2_VERIFIED'));});
for(const verb of ['Choisir','Auswählen','Seleccionar','Välj'])test('selection semantics are not one provider/language: '+verb,()=>{assert(run(card('Standard','GBP 12/month').replace('Select',verb)).decisions.every(d=>d.fields.ownership.status==='VERIFIED'));});

test('legacy generic-label rejection cannot cross-bind Premium to Standard',()=>{const r=run(card('Standard','GBP 9.99/month')+card('Premium','GBP 19.99/month'));const second=r.decisions.find(d=>d.amount==='19.99');assert.equal(second.fields.ownership.status,'BLOCKED');assert.notEqual(second.status,'V2_VERIFIED');});
test('unsupported costs sentence remains unresolved, separate from structural recovery',()=>{const r=run('<p>Plan Basic costs GBP 12.99/month.</p>');assert(r.decisions.every(d=>d.fields.ownership.status==='BLOCKED'));});
test('original clear article needs no new selection requirement',()=>{const r=run('<article><h2>Standard</h2><p>GBP 12/month</p></article>');assert(r.decisions.every(d=>d.fields.ownership.status==='VERIFIED'));});
test('existing explicit table row remains sufficient without extra evidence',()=>{const r=run('<table><tr><th>Standard</th><td>GBP 12/month</td></tr></table>');assert(r.decisions.some(d=>d.fields.ownership.status==='VERIFIED'));});
test('benefit under the same owner remains contextual',()=>{const body='<div><h2>Standard</h2><p>GBP 12/month</p><p>Benefit value ca GBP 169 / 12 months</p><button>Select</button></div>';const o=offers(body).find(o=>o.amount==='169');assert(o);assert.equal(o.confidence,'LOW');assert.equal(o.offerObject.monetaryRole.role,'CONTEXTUAL_VALUE');assert.equal(o.billingInterval.normalized,'P12M');});
test('same-owner savings cannot become the charge',()=>{const body='<div><h2>Standard</h2><p>GBP 12/month</p><p>Savings worth GBP 20/month</p><button>Select</button></div>';const o=offers(body).find(o=>o.amount==='20');assert(o);assert.equal(o.confidence,'LOW');});
