import test from 'node:test';import assert from 'node:assert/strict';
import {hash} from '../offline-recovery/extract.mjs';import {deriveEvidence,verifyCandidate} from './gate.mjs';
export function compoundFixture({restriction='',country=null,change=null,authority=true,age=0,sourceUrl='https://provider.example/de-DE/plans',canonical=sourceUrl,text=null}={}){
 text??='Plan Basic and Plan Plus can be purchased through provider.example/de-DE. After the first 3 months the membership renews monthly at 11.99 EUR/month (Plan Basic) or 21.99 EUR/month (Plan Plus) unless cancelled.';
 const leaf={text:text+(restriction?' '+restriction:''),...(country?{country}:{})},content={fields:{name:'Membership Ecomm Page',legalText:[{fields:{variations:[{fields:leaf}]}}]}},pp={preview:false,locale:'de-DE',page:{sys:{locale:'de-DE',contentType:{sys:{id:'page'}}},fields:{slug:'plans',content}}};change?.(pp);
 const body='<html><head><link rel="canonical" href="'+canonical+'"></head><body><script id="__NEXT_DATA__" type="application/json">'+JSON.stringify({props:{pageProps:pp}})+'</script></body></html>',bodyHash=hash(body),occurrence={id:'s',url:sourceUrl},receipt={intact:true,bodyHash,sourceUrl,service:'fixture',serviceEstablished:authority,bindingEstablished:true,serviceEvidence:{targetServiceName:'Fixture'}},context={bodyHash,service:'fixture',market:'DE',authority,sourceOccurrences:[occurrence],geoEvidence:[],marketProofResources:[{body,receipt,occurrence,capturedAt:new Date(Date.now()-age).toISOString()}]},d=deriveEvidence(body,context),decisions=d.rows.filter(c=>['11.99','21.99'].includes(c.amountNormalized)&&c.commercial.type==='RECURRING_MONTHLY').map(c=>verifyCandidate(c,d,receipt));return {body,context,d,decisions};
}
test('compound active commercial page binds both exact owned offers',()=>{const r=compoundFixture();assert.equal(r.decisions.length,2);assert(r.decisions.every(d=>d.status==='V2_VERIFIED'));});
for(const restriction of ['Plan Basic US only.','Plan Basic is available only to residents of the United States.','Plan Basic requires a United States billing address.','Plan Basic is not available in Germany.','This offer is not available in Germany.'])test('full conjunction loses to restriction: '+restriction,()=>{const r=compoundFixture({restriction});assert.equal(r.decisions.find(d=>d.plan==='Plan Basic').fields.market.status,'BLOCKED');assert(r.d.rows.find(c=>c.product==='Plan Basic').attribution.marketProof.evidence.some(e=>e.negative));});
for(const [name,options]of [
 ['foreign explicit scope',{country:'AU'}],['unreviewed',{authority:false}],['stale',{age:31*86400000}],['global final URL',{sourceUrl:'https://provider.example/plans'}],['global canonical',{canonical:'https://provider.example/plans'}],
 ['locale conflict',{change:p=>p.page.sys.locale='en-AU'}],['preview',{change:p=>p.preview=true}],['unknown page',{change:p=>delete p.page.sys.contentType}],['informational',{change:p=>p.page.fields.content.fields.name='Information'}],['unknown ownership',{change:p=>{p.fallback=p.page.fields.content;delete p.page.fields.content;}}],
 ['dictionary only',{change:p=>{p.fallback={microCopy:{country:'Deutschland',description:p.page.fields.content.fields.legalText[0].fields.variations[0].fields.text}};delete p.page.fields.content;}}],
 ['no purchase signal',{text:'After the first 3 months the membership renews monthly at 11.99 EUR/month (Plan Basic) or 21.99 EUR/month (Plan Plus) unless cancelled.'}],
 ['purchase belongs to another offer',{text:'Other Plan can be purchased through provider.example/de-DE. After the first 3 months the membership renews monthly at 11.99 EUR/month (Plan Basic) or 21.99 EUR/month (Plan Plus) unless cancelled.'}]
])test('compound requires every dimension: '+name,()=>{const r=compoundFixture(options);assert(r.decisions.every(d=>d.fields.market.status==='BLOCKED'));});
for(const restriction of ['Plan Basic is available in Germany except selected regions.','Plan Basic is eligible for selected accounts.','Plan Basic requires a Martian billing address.'])test('unsupported qualification stays review-only: '+restriction,()=>{const r=compoundFixture({restriction});assert.equal(r.decisions.find(d=>d.plan==='Plan Basic').fields.market.status,'BLOCKED');});
test('unrelated sibling restrictions, locale picker and microcopy cannot scope owned offers',()=>{const r=compoundFixture({change:p=>{p.fallback={microCopy:{country:'Deutschland'},prices:{'en-AU':{name:'Other Plan',country:'AU',price:19,priceCurrency:'AUD',recurring:true,billingPeriod:'MONTH',description:'Other Plan US only.'}},picker:{countries:['DE','AU','US']}};}});assert(r.decisions.every(d=>d.status==='V2_VERIFIED'));assert(r.d.rows.filter(c=>c.product==='Other Plan').every(c=>!c.attribution.marketApplicabilityEstablished));});
test('another exact plan restriction cannot contaminate Basic',()=>{const r=compoundFixture({restriction:'Plan Plus US only.'});assert.equal(r.decisions.find(d=>d.plan==='Plan Basic').status,'V2_VERIFIED');assert.equal(r.decisions.find(d=>d.plan==='Plan Plus').fields.market.status,'BLOCKED');});
test('retained body mismatch is still rejected',()=>{const r=compoundFixture();assert.throws(()=>deriveEvidence(r.body+'changed',r.context),/PROVENANCE_INTEGRITY_FAILURE/);});
test('production grammar in the owned commercial path',()=>{const r=compoundFixture({text:'Das Angebot gilt nur für neue Plan Basic oder Plan Plus Mitglieder. Plan Basic für 3 Monate zum Gesamtpreis von 12,99 € oder Plan Plus für 3 Monate zum Gesamtpreis von 28,99 € kann ausschließlich über provider.example/de-DE, den Apple App Store oder den Google Play Store erworben werden. Nach Ablauf der ersten 3 Monate verlängert sich die Mitgliedschaft automatisch um jeweils 1 Monat zu 12,99 €/Monat (Plan Basic) bzw. 28,99 €/Monat (Plan Plus), sofern sie nicht zuvor gekündigt wurde.'});const paid=r.d.rows.filter(c=>['12.99','28.99'].includes(c.amountNormalized)&&c.commercial.type==='RECURRING_MONTHLY');assert.equal(paid.length,2);for(const c of paid){assert.equal(c.attribution.marketApplicabilityEstablished,true);assert.equal(c.commercial.type,'RECURRING_MONTHLY');}});
test('a changed prose span cannot borrow a verified relationship',()=>{const r=compoundFixture();const paid=r.d.rows.find(c=>c.commercial.type==='RECURRING_MONTHLY');assert(paid);const receipt={intact:true,bodyHash:r.context.bodyHash,service:'fixture',serviceEstablished:true,bindingEstablished:true};assert.equal(verifyCandidate(paid,r.d,receipt).status,'V2_VERIFIED');const changed=structuredClone(paid);changed.prosePriceRelationship.relationship.amountSpan[0]++;assert.equal(verifyCandidate(changed,r.d,receipt).status,'V2_VERIFICATION_BLOCKED');});
test('source occurrence mismatch cannot establish compound market',()=>{const r=compoundFixture(),context=structuredClone(r.context);context.sourceOccurrences[0].url='https://other.example/de-DE/plans';assert(deriveEvidence(r.body,context).rows.every(c=>!c.attribution.marketApplicabilityEstablished));});
test('unsupported exact-plan residency restriction defeats positive source context',()=>{const r=compoundFixture({restriction:'Plan Basic requires permanent overseas residency.'});assert.equal(r.decisions.find(d=>d.plan==='Plan Basic').fields.market.status,'BLOCKED');});
test('unrecognized explicit scope is review-only, not erased by locale',()=>{const r=compoundFixture({country:'Selected territories'});assert(r.decisions.every(d=>d.fields.market.status==='BLOCKED'));});
