import test from 'node:test';import assert from 'node:assert/strict';
import {hash} from '../offline-recovery/extract.mjs';import {deriveEvidence,verifyCandidate} from './gate.mjs';
function run(statement,{wrap}={}){const text='After the first 3 months the membership renews monthly at 11.99 EUR/month (Plan Basic) unless cancelled.',body='<script id="__NEXT_DATA__" type="application/json">'+JSON.stringify({props:{pageProps:{preview:false,locale:'de-DE',page:{sys:{locale:'de-DE',contentType:{sys:{id:'page'}}},fields:{slug:'plans',content:{fields:{name:'Membership Ecomm Page',legalText:[{fields:{variations:[{fields:{text}}]}}]}}}}}}})+'</script>'+(wrap?wrap(statement):'<p>'+statement+'</p>'),bodyHash=hash(body),url='https://provider.example/de-DE/plans',occurrence={id:'s',url},receipt={intact:true,bodyHash,sourceUrl:url,service:'fixture',serviceEstablished:true,bindingEstablished:true,serviceEvidence:{targetServiceName:'Fixture'}},context={bodyHash,service:'fixture',market:'DE',authority:true,sourceOccurrences:[occurrence],geoEvidence:[],marketProofResources:[{body,receipt,occurrence,capturedAt:new Date().toISOString()}]},d=deriveEvidence(body,context),c=d.rows.find(c=>c.amountNormalized==='11.99');return {candidate:c,decision:verifyCandidate(c,d,receipt)};}
for(const statement of ['Plan Basic is available only to residents of the United States.','Plan Basic requires a United States billing address.'])test('source-bound foreign qualification: '+statement,()=>{const r=run(statement);assert.equal(r.candidate.attribution.marketProof?.status,'MARKET_CONTRADICTED');assert.equal(r.decision.fields.market.status,'BLOCKED');assert(r.candidate.attribution.marketProof.evidence[0].qualificationType);});
for(const suffix of ['is available in Germany','is available to customers in Germany','is available to residents of Germany','is available with a German billing address','is available in DE and AT','Germany and Austria only'])test('positive scope '+suffix,()=>{const r=run('Plan Basic '+suffix+'.');assert.equal(r.decision.status,'V2_VERIFIED');assert(r.candidate.attribution.marketProof.evidence.find(e=>e.countries).countries.includes('DE'));});
for(const suffix of ['is not available in Germany','is unavailable in Germany','Germany excluded','is not offered to German residents','German billing addresses are not supported','US only','is available only in the United States','is only available to US residents','customers must have a US billing address','is eligible only in the US','offer limited to customers in the United States'])test('incompatible scope '+suffix,()=>{const r=run('Plan Basic '+suffix+'.');assert.equal(r.candidate.attribution.marketProof.status,'MARKET_CONTRADICTED');assert.equal(r.decision.fields.market.status,'BLOCKED');});
for(const statement of ['US support is available for Plan Basic.','Prices shown in US dollars for Plan Basic.','United States','Plan Other US only.','US customers receive phone support.','Plan Basic US customers receive phone support.','Plan Basic is unavailable in United States.'])test('unrelated or non-target statement cannot establish market: '+statement,()=>{const r=run(statement);assert.equal(r.candidate.attribution.marketProof.status,'MARKET_NOT_VERIFIED');assert(r.candidate.attribution.marketProof.evidence.every(e=>e.establishesMarket===false));assert.equal(r.decision.fields.market.status,'BLOCKED');});
test('exception retains review rather than unconditional acceptance',()=>{const r=run('Plan Basic is available in Germany except selected areas.');assert.equal(r.candidate.attribution.marketProof.reviewRequired,true);assert.equal(r.candidate.attribution.marketProof.evidence.find(e=>e.qualification).qualification,'except selected areas');assert.equal(r.decision.fields.market.status,'BLOCKED');});
test('multiple countries preserved',()=>{const r=run('Plan Basic Germany and Austria only.');assert.deepEqual(r.candidate.attribution.marketProof.evidence.find(e=>e.countries).countries,['DE','AT']);});

test('exact plan heading binds a short country restriction',()=>{const r=run('US only.',{wrap:s=>'<section><h2>Plan Basic</h2><p>'+s+'</p></section>'});assert.equal(r.candidate.attribution.marketProof.status,'MARKET_CONTRADICTED');});
test('unrelated heading does not bind a short restriction',()=>{const r=run('US only.',{wrap:s=>'<section><h2>Plan Other</h2><p>'+s+'</p></section>'});assert.equal(r.candidate.attribution.marketProof.status,'MARKET_NOT_VERIFIED');assert(r.candidate.attribution.marketProof.evidence.every(e=>e.establishesMarket===false));});
