import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Operations,atomic} from './control.mjs';import {operationsRequest} from './http.mjs';import {nextRun,validateFrequency} from './scheduling.mjs';import {safePath,metrics} from './artifacts.mjs';
function fixture(){const repo=fs.mkdtempSync(path.join(os.tmpdir(),'v2-ops-')),root=path.join(repo,'control'),dir=path.join(repo,'.savlivo/research-v2/universe-expansion/catalog-live');fs.mkdirSync(dir,{recursive:true});const catalog=[{service:'complete',name:'Complete',catalogEligible:true,loginManageEvidenceState:'LOGIN_MANAGE_ESTABLISHED',priceConfidence:'NONE',priceStrategy:'MANUAL_ONLY'},{service:'missing',name:'Missing',catalogEligible:true,loginManageEvidenceState:'LOGIN_ONLY_ESTABLISHED',priceConfidence:'HIGH',priceStrategy:'USER_PRICE_PREFERRED'}];const target={id:'catalog-missing',service:'missing',serviceName:'Missing',market:'NO',authorities:[{hostname:'example.com',provider:'Missing',sourceType:'OFFICIAL_PROVIDER',sourceUrl:'https://example.com/',checkedAt:'2026-09-20'}],researchObjective:'CATALOG_ONLY',smartResearch:{version:2,navigationDepth:3},gaps:['WEB_MANAGEMENT'],urls:['https://example.com/help/billing'],leads:[{url:'https://example.com/help/billing',label:'billing help'}],catalogCapabilityProofs:[]};atomic(path.join(dir,'manifest.json'),{version:1,objective:'LOGIN_WEB_MANAGEMENT_ONLY',createdAt:'2026-09-20T00:00:00Z',catalog,targets:[target],conditionalFollowupTargets:[],limits:{reads:2,searches:1,acquisitions:0,retainedReviews:0,turns:4},safety:{requestsPerService:25,totalRequests:25}});atomic(path.join(dir,'after-catalog.json'),catalog);atomic(path.join(dir,'before-catalog.json'),catalog);atomic(path.join(dir,'scheduler.json'),{complete:true});const ops=new Operations({repo,root,read:true,control:true,scheduling:true,timezone:'Europe/Oslo'});return {ops,repo,dir,root};}
const config={objective:'LOGIN_MANAGE',scope:'UNRESOLVED_ONLY',services:[],reads:2,discovery:true,totalRequests:50},schedule={config,enabled:true,frequency:'WEEKLY',time:'03:00',timezone:'Europe/Oslo',weekday:1};
test('terminal run and coverage discovered without catalog exclusion for missing price',()=>{const {ops}=fixture();assert.equal(ops.index()[0].origin,'CLI');assert.equal(ops.summary().metrics.complete,1);assert.equal(ops.summary().metrics.catalog,2);assert.equal(ops.summary().metrics.active,2);assert.equal(ops.summary().metrics.noPrice,1);});
test('malformed historical artifact isolated',()=>{const {ops,dir}=fixture();fs.writeFileSync(path.join(dir,'summary.json'),'{broken');assert.equal(ops.index().length,1);assert.equal(ops.summary().metrics.catalog,2);});
for(const scope of ['FULL_CATALOG','UNRESOLVED_ONLY','SELECTED_SERVICES'])test('preflight '+scope,()=>{const {ops}=fixture();const p=ops.preflight({...config,scope,services:scope==='SELECTED_SERVICES'?['missing']:[]},'admin');assert.equal(p.servicesExpectedNetwork,1);assert.equal(p.decodo,false);assert.equal(p.browser,false);});
for(const patch of [{objective:'PRICE_REFRESH'},{scope:'DUE_ONLY'},{reads:99},{totalRequests:999999},{services:['../bad'],scope:'SELECTED_SERVICES'},{command:'rm'},{urls:['https://evil.invalid']}])test('unsafe config rejected '+JSON.stringify(patch),()=>{assert.throws(()=>fixture().ops.preflight({...config,...patch},'admin'));});
test('unauthorized HTTP request rejected before start',async()=>{await assert.rejects(operationsRequest({method:'POST',url:new URL('https://admin.invalid/v1/admin/v2-operations/start'),actor:null,body:{}},fixture().ops),e=>e.status===401);});
test('durable idempotent start creates admin history and manifest',()=>{const {ops,root}=fixture(),p=ops.preflight(config,'admin'),a=ops.start(p.token,'admin',true),b=ops.start(p.token,'admin',true);assert.equal(a.id,b.id);assert.equal(a.status,'QUEUED');assert(fs.existsSync(path.join(root,'runs',a.id,'manifest.json')));assert(ops.index(true).some(r=>r.origin==='ADMIN'));assert.throws(()=>ops.start(p.token,'other',true));});
test('active CLI prevents start without being modified',()=>{const {ops,dir}=fixture();fs.writeFileSync(path.join(dir,'runner.lock'),String(process.pid));const p=ops.preflight(config,'admin');assert(p.conflicts.length);const j=ops.start(p.token,'admin',true);assert.equal(j.status,'SKIPPED_CONFLICT');assert.equal(fs.readFileSync(path.join(dir,'runner.lock'),'utf8'),String(process.pid));});
test('stop and resume preserve manifest/checkpoint lineage',()=>{const {ops,root}=fixture(),p=ops.preflight(config,'admin'),j=ops.start(p.token,'admin',true),file=path.join(root,'runs',j.id,'manifest.json'),bytes=fs.readFileSync(file,'utf8');assert.equal(ops.control(j.id,'stop','admin').status,'STOPPED');assert.equal(ops.control(j.id,'resume','admin').id,j.id);assert.equal(fs.readFileSync(file,'utf8'),bytes);});
test('read-only and scheduling flags independent',()=>{const {ops}=fixture();ops.config.control=false;assert.throws(()=>ops.preflight(config,'a'),/DISABLED/);assert(ops.summary());assert(ops.saveSchedule(schedule,'a'));ops.config.scheduling=false;assert.throws(()=>ops.saveSchedule(schedule,'a'),/DISABLED/);});
for(const frequency of ['DAILY','EVERY_3_DAYS','WEEKLY','EVERY_2_WEEKS','MONTHLY','CUSTOM'])test('frequency '+frequency,()=>{const s={...schedule,frequency,intervalDays:5,monthDay:12,anchor:'2026-09-20'};const next=nextRun(s,new Date('2026-09-20T12:00:00Z'));assert(Date.parse(next)>Date.parse('2026-09-20T12:00:00Z'));});
test('DST gap moves to next valid minute',()=>{assert.equal(nextRun({...schedule,frequency:'DAILY',time:'02:30',anchor:'2026-03-28'},new Date('2026-03-28T12:00:00Z')),'2026-03-29T01:00:00.000Z');});
test('DST duplicate wall time executes once, choosing earliest',()=>{const s={...schedule,frequency:'DAILY',time:'02:30',anchor:'2026-10-24'};assert.equal(nextRun(s,new Date('2026-10-24T12:00:00Z')),'2026-10-25T00:30:00.000Z');assert.equal(nextRun(s,new Date('2026-10-25T00:31:00Z')),'2026-10-26T01:30:00.000Z');});
for(const patch of [{frequency:'* * * * *'},{frequency:'CUSTOM',intervalDays:0},{timezone:'invalid/zone'},{time:'25:00'},{monthDay:31}])test('unsafe schedule rejected '+JSON.stringify(patch),()=>assert.throws(()=>validateFrequency({...schedule,...patch})));
test('schedule persistence enable disable edit no immediate trigger',()=>{const {ops}=fixture(),s=ops.saveSchedule({...schedule,enabled:false},'a');assert.equal(s.nextRunAt,null);assert.equal(ops.tick().length,0);assert(ops.scheduleAction(s.id,'enable','a').nextRunAt);ops.scheduleAction(s.id,'disable','a');const restarted=new Operations(ops.config);assert.equal(restarted.db().schedules[0].enabled,false);ops.saveSchedule({...schedule,frequency:'DAILY'},'b',s.id);assert.equal(ops.db().jobs.length,0);assert.equal(ops.db().schedules[0].updatedBy,'b');});
test('Run now is idempotent and preserves next trigger; shared queue',()=>{const {ops}=fixture(),s=ops.saveSchedule(schedule,'a'),a=ops.scheduleAction(s.id,'run-now','a','stable-request-key-123'),b=ops.scheduleAction(s.id,'run-now','a','stable-request-key-123');assert.equal(a.id,b.id);assert.equal(a.origin,'SCHEDULED');assert.equal(ops.db().schedules[0].nextRunAt,s.nextRunAt);assert(ops.index(true).some(r=>r.origin==='SCHEDULED'));});
test('duplicate scheduler trigger once and conflict recorded',()=>{const {ops}=fixture(),s=ops.saveSchedule(schedule,'a');ops.saveSchedule(schedule,'b');const now=new Date(Date.parse(s.nextRunAt)+1000),jobs=ops.tick(now);assert.equal(jobs.length,2);assert.equal(jobs.filter(j=>j.status==='QUEUED').length,1);assert.equal(jobs.filter(j=>j.status==='SKIPPED_CONFLICT').length,1);assert.equal(ops.tick(now).length,0);});
test('nothing due creates zero-work outcome with established selected scope',()=>{const {ops}=fixture(),s=ops.saveSchedule({...schedule,config:{...config,scope:'SELECTED_SERVICES',services:['complete']}},'a'),j=ops.scheduleAction(s.id,'run-now','a','nothing-due-key-123');assert.equal(j.status,'SKIPPED_NOT_DUE');assert.equal(ops.db().jobs.length,1);});
test('safe service evidence separates management from price and retains plain text',()=>{const {ops,dir}=fixture(),file=path.join(dir,'after-catalog.json'),rows=JSON.parse(fs.readFileSync(file));rows[1].managementEvidence=[{url:'https://example.com/help',providerText:'<script>never executable</script>',sourceHash:'a'.repeat(64),meaning:'PROVIDER_PUBLISHED_CAPABILITY_LINK_NOT_DESTINATION_AUTHORITY'}];atomic(file,rows);const v=ops.services({q:'missing'}).rows[0];assert.equal(v.evidence[0].domain,'MANAGEMENT');assert.equal(v.priceConfidence,'HIGH');assert.equal(v.userPriceAuthoritative,true);assert(v.evidence[0].text.includes('<script>'));});
test('filesystem traversal and symlink rejected',()=>{const {root,repo}=fixture();assert.throws(()=>safePath(root,'../outside'));fs.mkdirSync(root);fs.symlinkSync(repo,path.join(root,'escape'));assert.throws(()=>safePath(root,'escape/file'));});

test('queued preflight reuses newly complete evidence before execution',()=>{const {ops,dir,root}=fixture(),p=ops.preflight(config,'a'),j=ops.start(p.token,'a',true);const rows=JSON.parse(fs.readFileSync(path.join(dir,'after-catalog.json')));rows[1].loginManageEvidenceState='LOGIN_MANAGE_ESTABLISHED';atomic(path.join(dir,'after-catalog.json'),rows);ops.cache=null;ops.catalogCache=null;ops.transaction(db=>assert.equal(ops.prepareQueued(db,db.jobs[0]),false));assert.equal(ops.db().jobs[0].status,'SKIPPED_NOT_DUE');assert.equal(JSON.parse(fs.readFileSync(path.join(root,'runs',j.id,'manifest.json'))).targets.length,0);});
test('resume preflight never resets manifest or consumed checkpoint',()=>{const {ops,root}=fixture(),p=ops.preflight(config,'a'),j=ops.start(p.token,'a',true),dir=path.join(root,'runs',j.id);atomic(path.join(dir,'scheduler.json'),{complete:false,round:2,consumed:7});const before=fs.readFileSync(path.join(dir,'manifest.json'),'utf8');ops.transaction(db=>assert.equal(ops.prepareQueued(db,db.jobs[0]),true));assert.equal(fs.readFileSync(path.join(dir,'manifest.json'),'utf8'),before);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'scheduler.json'))).consumed,7);});
test('schedule validation returns client error',async()=>{const {ops}=fixture();await assert.rejects(operationsRequest({method:'POST',url:new URL('https://admin.invalid/v1/admin/v2-operations/schedules'),body:{...schedule,timezone:'bad/timezone'},actor:'a'},ops),e=>e.status===400);});
test('replay descendants do not become independent historical campaigns',()=>{const {ops,dir}=fixture();atomic(path.join(dir,'replay','after-catalog.json'),[]);assert.equal(ops.index().length,1);});
test('corrupted control store fails closed without overwriting durable history',()=>{const {ops,root}=fixture();fs.mkdirSync(root);const file=path.join(root,'state.json');fs.writeFileSync(file,'{corrupt');assert.throws(()=>ops.db(),/CONTROL_STORE_UNAVAILABLE/);assert.throws(()=>ops.transaction(()=>{}),/CONTROL_STORE_UNAVAILABLE/);assert.equal(fs.readFileSync(file,'utf8'),'{corrupt');});
