import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import cp from 'node:child_process';import {syncBuiltinESMExports} from 'node:module';
import {Operations} from './control.mjs';
test('poller avoids result reconstruction until a queued job needs admission; death and explicit Resume remain separate',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'poller-idle-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 const env={V2_OPERATIONS_REPOSITORY_ROOT:root,V2_OPERATIONS_STATE_ROOT:root,ANALYTICS_V2_OPERATIONS_ENABLED:'true',ANALYTICS_V2_RUN_CONTROL_ENABLED:'true',ANALYTICS_V2_SCHEDULING_ENABLED:'false'},old=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]]));Object.assign(process.env,env);t.after(()=>{for(const [k,v]of Object.entries(old))if(v===undefined)delete process.env[k];else process.env[k]=v;});
 const ops=new Operations({repo:root,root,read:true,control:true,scheduling:false}),id='12345678-1234-1234-1234-123456789abc',dir=path.join(root,'runs',id),life=path.join(root,'lifecycle');fs.mkdirSync(dir,{recursive:true});fs.mkdirSync(path.join(life,'catalog'),{recursive:true});
 const worker=path.join(root,'services/api/src/v2-operations/worker.mjs');fs.mkdirSync(path.dirname(worker),{recursive:true});fs.writeFileSync(worker,"console.log('ready');setInterval(()=>{},1000);");const execution=cp.spawn(process.execPath,[worker,'--execute',id],{stdio:['ignore','pipe','pipe']});t.after(()=>execution.kill());await new Promise((resolve,reject)=>{execution.once('error',reject);execution.stdout.once('data',resolve);});
 const put=(p,v)=>fs.writeFileSync(p,JSON.stringify(v));const job={id,status:'RUNNING',pid:execution.pid,actor:'test',origin:'ADMIN',config:{objective:'MATURE_LIFECYCLE'},sourceRun:null};ops.transaction(db=>db.jobs.push(job));put(dir+'/operation.json',job);put(dir+'/manifest.json',{lifecycle:{output:'lifecycle'}});put(life+'/lineage.json',{cohort:['synthetic'],additionalRequestCeiling:100});
 const checkpoint=JSON.stringify({targets:Object.fromEntries(Array.from({length:104},(_,i)=>['target-'+i,{researchMemory:{observations:[{quote:'e'.repeat(10000+i*10)}]},reads:[]}]))});fs.writeFileSync(life+'/catalog/adaptive-state.json',checkpoint);fs.writeFileSync(life+'/network.jsonl','{"service":"synthetic","kind":"page"}\n');
 const read=fs.readFileSync;let heavyReads=0,spawns=0;t.mock.method(fs,'readFileSync',function(file,...args){if(String(file).endsWith('/adaptive-state.json'))heavyReads++;return read.call(this,file,...args);});
 t.mock.method(cp,'spawn',()=>{spawns++;return execution;});syncBuiltinESMExports();t.after(()=>{t.mock.restoreAll();syncBuiltinESMExports();});
 let tick=(await import('./worker.mjs?poller-idle')).tick;await tick();await tick();assert.equal(heavyReads,0);assert.equal(spawns,0);
 ops.transaction(db=>{db.jobs[0].pid=2147483647;});tick=(await import('./worker.mjs?poller-restarted')).tick;await tick();assert.equal(ops.db().jobs[0].status,'INTERRUPTED');assert.equal(ops.db().jobs[0].error,'WORKER_PROCESS_EXITED_CHECKPOINT_PRESERVED');await tick();assert.equal(heavyReads,0);assert.equal(spawns,0);
 // Existing admission/conflict checks still run when an actual launch is requested.
 t.mock.method(Operations.prototype,'prepareQueued',()=>true);ops.control(id,'resume','test');await tick();assert.equal(spawns,1);assert.equal(ops.db().jobs[0].status,'RUNNING');assert(heavyReads>0);const count=heavyReads;await Promise.all([tick(),tick()]);assert.equal(spawns,1);assert.equal(heavyReads,count);
 assert.equal(read(life+'/catalog/adaptive-state.json','utf8'),checkpoint);assert.equal(read(life+'/network.jsonl','utf8'),'{"service":"synthetic","kind":"page"}\n');
});
