import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import cp from 'node:child_process';import {syncBuiltinESMExports} from 'node:module';
import {Operations} from './control.mjs';import {operationsRequest} from './http.mjs';
test('direct Resume chain preserves explicit recovery after a pre-launch lease conflict',async t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'resume-chain-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const env={V2_OPERATIONS_REPOSITORY_ROOT:root,V2_OPERATIONS_STATE_ROOT:root,ANALYTICS_V2_OPERATIONS_ENABLED:'true',ANALYTICS_V2_RUN_CONTROL_ENABLED:'true',ANALYTICS_V2_SCHEDULING_ENABLED:'false'},old=Object.fromEntries(Object.keys(env).map(k=>[k,process.env[k]]));Object.assign(process.env,env);t.after(()=>{for(const [k,v]of Object.entries(old))if(v===undefined)delete process.env[k];else process.env[k]=v;});
 const worker=path.join(root,'services/api/src/v2-operations/worker.mjs'),other=path.join(root,'other.mjs');fs.mkdirSync(path.dirname(worker),{recursive:true});for(const f of [worker,other])fs.writeFileSync(f,"console.log('ready');setInterval(()=>{},1000);");
 async function child(file,args=[]){const c=cp.spawn(process.execPath,[file,...args],{stdio:['ignore','pipe','pipe']});t.after(()=>c.kill());await new Promise((resolve,reject)=>{c.once('error',reject);c.stdout.once('data',resolve);});return c;}
 const stale=await child(other),blocker=await child(worker,['--execute','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa']);
 const id='12345678-1234-1234-1234-123456789abc',ops=new Operations({repo:root,root,read:true,control:true,scheduling:false}),job={id,status:'INTERRUPTED',pid:stale.pid,startedAt:'2025-01-01T00:00:00Z',stopRequested:false,error:'WORKER_PROCESS_EXITED_CHECKPOINT_PRESERVED',actor:'a',origin:'ADMIN',config:{objective:'MATURE_LIFECYCLE'},sourceRun:null};ops.transaction(db=>db.jobs.push(job));const dir=root+'/runs/'+id;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/operation.json',JSON.stringify(job));fs.writeFileSync(dir+'/manifest.json',JSON.stringify({lifecycle:{output:'lifecycle',admission:{executionGeneration:id}}}));fs.writeFileSync(dir+'/checkpoint.json','{"turn":7}');fs.writeFileSync(dir+'/network.jsonl','{"kind":"page"}\n');
 const resume=()=>operationsRequest({method:'POST',url:new URL('https://offline.invalid/v1/admin/v2-operations/jobs/'+id+'/resume'),actor:'a',body:{}},ops),events=()=>ops.db().events.filter(e=>e.type==='RESUME_REQUESTED');
 t.mock.method(Operations.prototype,'prepareQueued',()=>true);const {tick}=await import('./worker.mjs?resume-chain');assert.equal((await resume()).status,'QUEUED');await assert.rejects(resume(),/RUN_NOT_RESUMABLE/);assert.equal(events().length,1);
 fs.writeFileSync(root+'/execution.lock',String(blocker.pid));await tick();assert.equal(ops.db().jobs[0].status,'SKIPPED_CONFLICT');assert.equal(ops.db().jobs[0].error,'EXECUTION_LEASE_UNAVAILABLE');
 const exited=new Promise(r=>blocker.once('exit',r));blocker.kill();await exited;await tick();assert.equal(ops.db().jobs[0].status,'SKIPPED_CONFLICT');assert.equal(events().length,1);
 const run=ops.index(true).find(r=>r.jobId===id);const detail=await operationsRequest({method:'GET',url:new URL('https://offline.invalid/v1/admin/v2-operations/runs/'+run.id),actor:'a'},ops);assert.equal(detail.run.resumeAllowed,true);
 // This is the historical recovery-chain failure: a proven resumed job must be retryable.
 assert.equal((await resume()).status,'QUEUED');assert.equal(events().length,2);await assert.rejects(resume(),/RUN_NOT_RESUMABLE/);
 const execution=await child(worker,['--execute',id]);let spawns=0;t.mock.method(cp,'spawn',()=>{spawns++;return execution;});syncBuiltinESMExports();t.after(()=>{t.mock.restoreAll();syncBuiltinESMExports();});fs.writeFileSync(root+'/execution.lock',String(stale.pid));await tick();assert.equal(spawns,1);assert.equal(ops.db().jobs[0].status,'RUNNING');assert.equal(ops.db().jobs[0].pid,execution.pid);assert.equal(Number(fs.readFileSync(root+'/execution.lock')),execution.pid);await Promise.all([tick(),tick()]);assert.equal(spawns,1);
 ops.transaction(db=>{db.jobs[0].status='INTERRUPTED';});await assert.rejects(resume(),/RUN_NOT_RESUMABLE/);assert.equal(events().length,2);assert.equal(fs.readFileSync(dir+'/checkpoint.json','utf8'),'{"turn":7}');assert.equal(fs.readFileSync(dir+'/network.jsonl','utf8'),'{"kind":"page"}\n');assert.equal(JSON.parse(fs.readFileSync(dir+'/manifest.json')).lifecycle.admission.executionGeneration,id);
});

import {resumeAllowed} from './resume-policy.mjs';
test('only a recorded resumed execution with a lease failure gains skipped-conflict eligibility',()=>{const job={id:'a',status:'SKIPPED_CONFLICT',error:'EXECUTION_LEASE_UNAVAILABLE',startedAt:'2025-01-01'},events=[{type:'RESUME_REQUESTED',jobId:'a'}];assert(resumeAllowed(job,events));assert(!resumeAllowed(job,[]));assert(!resumeAllowed({...job,startedAt:null},events));assert(!resumeAllowed({...job,error:'OTHER'},events));assert(!resumeAllowed({...job,status:'COMPLETE'},events));assert(!resumeAllowed(job,[{type:'RESUME_REQUESTED',jobId:'b'}]));});
