import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {projectTargeting,selectTargeting} from './targeting.mjs';
import {Operations} from './control.mjs';import {operationsRequest} from './http.mjs';
export function modelFixture(){
 const candidates=[{slug:'film',name:'Film provider',aliases:['Cinema'],categories:['video'],markets:['NO','SE']},{slug:'music',name:'Music provider',categories:['music','video'],markets:['SE','DK']},{slug:'paper',name:'Daily paper',categories:['news'],markets:['DE']},{slug:'unknown',name:'Unknown scope',categories:[]}];
 return projectTargeting({identity:'fixture',handoff:{cohort:{manifest:{serviceIds:candidates.map(c=>c.slug)},candidates},baselineIds:['netflix'],targets:[{service:'film',authorities:[{provider:'Provider AB'}]},{service:'paper'}]},universe:{},scopes:{},states:{'film-catalog':{target:{service:'film'}},'film-price':{target:{service:'film'}}},latest:[{service_id:'paper',researchComplete:true,finalStatus:'ESTABLISHED'}],categories:[{id:'video',name:'Video & TV'},{id:'music',name:'Music'}]});
}
const ids=p=>p.services;
test('discoverable model separates unique services, target count, baseline and unknown state',()=>{const m=modelFixture();assert.deepEqual(m.counts,{eligible:4,baselineExcluded:1,reviewed:2,humanReview:2,retainedServices:1,retainedTargets:2,unscopedServices:1});assert.equal(m.rows[0].researchComplete,null);assert(!m.rows.some(r=>r.service==='netflix'));assert.equal(selectTargeting(m).serviceMarketTargets,5);assert.equal(m.facets.markets.find(f=>f.id==='SE').services,2);});
for(const [preset,want]of [['ALL',['film','music','paper','unknown']],['UNRESOLVED',['film','music','unknown']],['REVIEWED',['film','paper']],['HUMAN_REVIEW',['music','unknown']],['RETAINED',['film']]])test('lifecycle '+preset,()=>assert.deepEqual(ids(selectTargeting(modelFixture(),{preset})),want));
for(const [filters,want]of [[{markets:[]},['film','music','paper','unknown']],[{markets:['NO']},['film']],[{markets:['NO','SE']},['film','music']],[{categories:['video','news']},['film','music','paper']],[{markets:['NO','SE'],categories:['music']},['music']],[{markets:['DE'],preset:'UNRESOLVED'},[]],[{categories:['news'],preset:'REVIEWED'},['paper']],[{markets:['SE','DE'],categories:['video'],preset:'HUMAN_REVIEW'},['music']]])test('AND across facets / OR within '+JSON.stringify(filters),()=>assert.deepEqual(ids(selectTargeting(modelFixture(),filters)),want));
test('market scope targets count pairs once and selects only investigation markets',()=>{const p=selectTargeting(modelFixture(),{markets:['NO','SE']});assert.equal(p.selectedServices,2);assert.equal(p.serviceMarketTargets,3);assert.deepEqual(p.researchMarkets,{film:['NO','SE'],music:['SE']});});
test('manual selection, deselection, empty and human-readable/provider search',()=>{const m=modelFixture();assert.deepEqual(ids(selectTargeting(m,{services:['film','music']})),['film','music']);assert.deepEqual(ids(selectTargeting(m,{services:['music']})),['music']);assert.deepEqual(ids(selectTargeting(m,{services:[]})),[]);for(const q of ['Cinema','Provider AB','film PROVIDER'])assert.deepEqual(ids(selectTargeting(m,{q})),['film']);assert.equal(selectTargeting(m,{q:'absent'}).selectedServices,0);});
test('all matching is dynamic, future values need no frontend additions',()=>{const m=modelFixture();m.rows.push({...m.rows[0],service:'future',markets:['NZ'],categories:['future-category']});m.facets.markets.push({id:'NZ',name:'New Zealand'});m.facets.categories.push({id:'future-category',name:'Future'});assert.equal(selectTargeting(m).selectedServices,5);assert.deepEqual(ids(selectTargeting(m,{markets:['NZ']})),['future']);});
test('baseline injection, unknown facets and wildcard fail closed',()=>{for(const value of [{services:['netflix']},{markets:['ALL']},{categories:['invented']},{preset:'ALL_DATABASE'},{services:['film','film']},{force:true}])assert.throws(()=>selectTargeting(modelFixture(),value));});
function controlFixture(t){const repo=fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(),'targeting-')));t.after(()=>fs.rmSync(repo,{recursive:true,force:true}));fs.writeFileSync(repo+'/input.json',JSON.stringify({cohortManifest:'manifest.json'}));fs.writeFileSync(repo+'/manifest.json',JSON.stringify({serviceIds:modelFixture().rows.map(r=>r.service)}));const ops=new Operations({repo,root:repo+'/ops',lifecycleInput:'input.json',read:true,control:true,scheduling:false});ops.targetingModel=()=>modelFixture();return ops;}
const caps={direct:true,tavily:true,decodo:false,browser:false,groq:false};
test('read-only targeting endpoint works with run-control OFF; no jobs or state written',async t=>{const ops=controlFixture(t);ops.config.control=false;const view=await operationsRequest({method:'GET',url:new URL('http://local/v1/admin/v2-operations/targeting'),actor:'admin'},ops);assert.equal(view.selectedServices,4);assert(!fs.existsSync(ops.config.root));await assert.rejects(operationsRequest({method:'GET',url:new URL('http://local/v1/admin/v2-operations/targeting')},ops),/UNAUTHORIZED/);});
test('control validates exact preview, freezes explicit services/market scope, rejects manipulation',async t=>{const ops=controlFixture(t),m=modelFixture(),p=selectTargeting(m,{markets:['SE'],preset:'UNRESOLVED'});const body={objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:p.services,targeting:p.targeting,targetingRevision:m.revision,capabilities:caps};const c=ops.configInput(body);assert.deepEqual(c.services,['film','music']);assert.deepEqual(c.researchMarkets,['SE']);assert.equal(c.targeting,undefined);assert.deepEqual(ops.configInput(c),c);for(const change of [{services:['netflix']},{services:['film']},{targetingRevision:'old'},{researchMarkets:['NO']},{scope:'FULL_CATALOG',services:[]}])assert.throws(()=>ops.configInput({...body,...change}));for(const researchMarkets of [['NO'],['FAKE']])assert.throws(()=>ops.configInput({...c,services:['paper'],researchMarkets}));assert(!fs.existsSync(ops.config.root));await assert.rejects(operationsRequest({method:'POST',url:new URL('http://local/v1/admin/v2-operations/preflight'),actor:'admin',body:{...body,services:['netflix']}},ops),/INVALID_LIFECYCLE_SELECTION/);assert.throws(()=>ops.start('token','admin',false),/CONFIRMATION_REQUIRED/);assert.throws(()=>ops.saveSchedule({},'admin'),/SCHEDULING_DISABLED/);});
test('selected market scope is passed into native check; normalized queued config is frozen',async t=>{
 const {lifecyclePlan}=await import('./lifecycle.mjs'),child=await import('node:child_process'),{syncBuiltinESMExports}=await import('node:module');const ops=controlFixture(t);
 const model=modelFixture(),preview=selectTargeting(model,{markets:['NO','SE'],services:['film']});const config={objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:['film'],researchMarkets:['NO','SE'],capabilities:caps};let seen;
 const stub=t.mock.method(child.default,'spawnSync',(_cmd,args)=>{const input=JSON.parse(fs.readFileSync(args[args.indexOf('--input')+1]));seen={input,scopes:JSON.parse(fs.readFileSync(path.join(ops.config.repo,input.researchScopes)))};assert.equal(args.at(-1),'--check');return {status:0,stdout:JSON.stringify({output:'output',networkCalls:0,onlineStarted:false,servicesSelected:1,maximumNewRequests:40,liveReady:false})};});syncBuiltinESMExports();
 try{const p=lifecyclePlan(ops.config,config,preview);assert.deepEqual(seen.input.executionServices,['film']);assert.deepEqual(seen.scopes,{researchMarkets:{film:['NO','SE']}});assert.deepEqual(p.config.researchMarkets,['NO','SE']);assert.equal(p.totalSafetyCeiling,40);const before=fs.readFileSync(path.resolve(ops.config.repo,p.manifest.lifecycle.input));lifecyclePlan(ops.config,p.config,preview);assert.deepEqual(fs.readFileSync(path.resolve(ops.config.repo,p.manifest.lifecycle.input)),before);}finally{stub.mock.restore();syncBuiltinESMExports();}
});
test('market/category all and narrowed previews never include baseline; edited API selections cannot add it',async t=>{const ops=controlFixture(t);for(const filters of [{},{markets:['SE']},{categories:['video']},{markets:['SE'],categories:['video'],preset:'UNRESOLVED'}]){const p=ops.targeting(filters);assert(!p.services.includes('netflix'));await assert.rejects(operationsRequest({method:'POST',url:new URL('http://local/v1/admin/v2-operations/preflight'),body:{objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:[...p.services,'netflix'],targeting:p.targeting,targetingRevision:p.revision,capabilities:caps},actor:'admin'},ops),/INVALID_LIFECYCLE_SELECTION/);}assert(!fs.existsSync(ops.config.root));});
test('authenticated Genesis fixture exposes current counts and a real combined filter without research',{skip:!process.env.SAVLIVO_TARGETING_FIXTURE_ROOT},async()=>{
 const {loadTargeting,loadTargetingIsolated}=await import('./targeting.mjs');const repo=fs.realpathSync(process.env.SAVLIVO_TARGETING_FIXTURE_ROOT);
 assert(!repo.startsWith(path.resolve(process.cwd(),'.savlivo')+path.sep),'Use an isolated restored fixture, never source runtime state');
 const lifecycleInput=process.env.SAVLIVO_TARGETING_FIXTURE_INPUT;assert(lifecycleInput);
 const m=loadTargetingIsolated({repo,lifecycleInput});assert.deepEqual(m,loadTargeting({repo,lifecycleInput}));assert.deepEqual(m.counts,{eligible:188,baselineExcluded:275,reviewed:104,humanReview:84,retainedServices:104,retainedTargets:161,unscopedServices:94});
 assert(m.facets.markets.some(m=>m.id==='NO'));assert(m.facets.markets.some(m=>m.id==='SE'));assert(m.facets.categories.some(c=>c.id==='other'));
 const p=selectTargeting(m,{markets:['NO','SE'],categories:['other'],preset:'REVIEWED'});assert.deepEqual(p.services,['actic','klarna-memberships','life360']);assert.equal(p.serviceMarketTargets,4);assert(!p.services.includes('netflix'));
});
test('confirmed Start validates mature plan once and passes that exact frozen plan to enqueue',t=>{
 const ops=controlFixture(t),config={objective:'MATURE_LIFECYCLE',scope:'SELECTED_SERVICES',services:['film'],capabilities:caps},plan={config,catalogHash:'frozen'};let plans=0,enqueued=null;
 ops.transaction=fn=>fn({preflights:[{token:'p',actor:'admin',expiresAt:'2999-01-01',config,catalogHash:'frozen'}]});ops.plan=()=>{plans++;return plan;};ops.enqueue=(...args)=>{enqueued=args;return {status:'QUEUED'};};
 assert.throws(()=>ops.start('p','admin',false),/CONFIRMATION_REQUIRED/);assert.equal(plans,0);assert.equal(ops.start('p','admin',true).status,'QUEUED');assert.equal(plans,1);assert.equal(enqueued.at(-1),plan);
 ops.plan=()=>({...plan,catalogHash:'changed'});assert.throws(()=>ops.start('p','admin',true),/PREFLIGHT_STALE/);
});

test('targeting projection runs in one bounded read-only child and returns only the compact model',async t=>{
 const {loadTargetingIsolated}=await import('./targeting.mjs'),child=await import('node:child_process'),{syncBuiltinESMExports}=await import('node:module');let calls=0;
 const model=modelFixture();const stub=t.mock.method(child.default,'spawnSync',(_cmd,args,options)=>{
  calls++;assert(args.includes('--max-old-space-size=512'));assert(args.includes('--expose-gc'));assert.equal(args.at(-1),'--read-model');assert(!args.includes('--live'));assert(!args.includes('--check'));assert.equal(options.timeout,120000);assert.equal(options.maxBuffer,4*1024*1024);
  assert.deepEqual(JSON.parse(options.input),{repo:'/tmp/isolated',lifecycleInput:'input.json'});return {status:0,stdout:JSON.stringify(model)};
 });syncBuiltinESMExports();try{assert.deepEqual(loadTargetingIsolated({repo:'/tmp/isolated',lifecycleInput:'input.json',unrelated:'not forwarded'}),model);assert.equal(calls,1);}finally{stub.mock.restore();syncBuiltinESMExports();}
});
test('targeting child failure never falls back to an unauthenticated projection',async t=>{
 const {loadTargetingIsolated}=await import('./targeting.mjs'),child=await import('node:child_process'),{syncBuiltinESMExports}=await import('node:module');
 const stub=t.mock.method(child.default,'spawnSync',()=>({status:null,signal:'SIGKILL'}));syncBuiltinESMExports();try{assert.throws(()=>loadTargetingIsolated({repo:'/tmp',lifecycleInput:'input.json'}),/TARGETING_READ_MODEL_FAILED/);}finally{stub.mock.restore();syncBuiltinESMExports();}
});
