import {recordJobPhase,jobTerminalStatuses} from './job-status.mjs';
import {resolveCapabilities,requireCapability} from '../research-v2/capabilities/config.mjs';
import {runPoller,executionSpawnOptions} from './poller-runtime.mjs';
import {claimLeases,transferLeases,releaseLeases} from './leases.mjs';
// Separate, operator-supervised worker. Never launched inside an HTTP request.
import fs from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';import {fileURLToPath,pathToFileURL} from 'node:url';
import {Operations,settings,atomic} from './control.mjs';import {json,alive,lockActive} from './artifacts.mjs';
const config=settings(),ops=new Operations(config),self=fileURLToPath(import.meta.url);
const executionChildren=new Set();
export async function tick(shouldStop=()=>false){
 if(shouldStop()||!config.read)return;
 for(const j of ops.db().jobs)if(j.status==='RUNNING'&&!alive(j.pid))ops.patchJob(j.id,{status:'INTERRUPTED',error:'WORKER_PROCESS_EXITED_CHECKPOINT_PRESERVED'});
 ops.tick();const active=ops.index(true).some(r=>r.status==='RUNNING');if(active)return;
 const queued=ops.db().jobs.find(j=>j.status==='QUEUED'&&(j.origin==='SCHEDULED'?config.scheduling:config.control));if(!queued)return;
 // Global child lease plus control-store lock serialize workers and manual/scheduled jobs.
 ops.transaction(db=>{const j=db.jobs.find(j=>j.id===queued.id);if(j.status!=='QUEUED'||ops.index(true).some(r=>r.status==='RUNNING'))return;recordJobPhase(config,j,'PREPARATION_STARTED');let prepared;try{ops.config.diagnosticContext={purpose:'WORKER_PREPARE',jobId:j.id};prepared=ops.prepareQueued(db,j);recordJobPhase(config,j,'PREPARATION_COMPLETED');}catch(e){recordJobPhase(config,j,'PREPARATION_FAILED');throw e;}finally{delete ops.config.diagnosticContext;}if(!prepared||shouldStop())return;const source=j.sourceRun?ops.run(j.sourceRun):null,leases=[path.join(config.root,'execution.lock'),...(source?[path.join(source._directory,'runner.lock')]:[])];let held=[],child;try{held=claimLeases(leases);const log=fs.openSync(path.join(config.root,'runs',j.id,'worker.log'),'a',0o600);child=spawn(process.execPath,['--import','tsx',self,'--execute',j.id],{cwd:config.repo,stdio:['ignore',log,log],...executionSpawnOptions(),env:process.env});executionChildren.add(child);child.once('exit',(exitCode,signal)=>{executionChildren.delete(child);let status=null;try{const value=ops.db().jobs.find(row=>row.id===j.id)?.status;if(['QUEUED','RUNNING',...jobTerminalStatuses].includes(value))status=value;}catch{}console.error(JSON.stringify({event:'V2_EXECUTION_CHILD_EXIT',jobId:j.id,status,exitCode,signal}));});child.once('error',()=>executionChildren.delete(child));child.on('error',()=>{try{ops.patchJob(j.id,{status:'FAILED',error:'WORKER_SPAWN_FAILED'});}catch{}});fs.closeSync(log);if(!child.pid)throw Error('WORKER_SPAWN_FAILED');transferLeases(held,process.pid,child.pid);recordJobPhase(config,j,'CHILD_SPAWNED');child.unref();j.pid=child.pid;j.status='RUNNING';j.startedAt??=new Date().toISOString();j.updatedAt=new Date().toISOString();atomic(path.join(config.root,'runs',j.id,'operation.json'),j);ops.event(db,'RUN_STARTED',j.actor,{jobId:j.id,scheduleId:j.scheduleId});}catch(e){if(child?.pid){child.kill('SIGTERM');releaseLeases(held,child.pid);}releaseLeases(held,process.pid);j.status='SKIPPED_CONFLICT';j.error='EXECUTION_LEASE_UNAVAILABLE';recordJobPhase(config,j,'CLAIM_FAILED');atomic(path.join(config.root,'runs',j.id,'operation.json'),j);ops.event(db,'RUN_SKIPPED',j.actor,{jobId:j.id,reason:j.error});}});const published=ops.db().jobs.find(j=>j.id===queued.id);if(published?.status==='RUNNING')recordJobPhase(config,published,'RUNNING_PUBLISHED');
}
async function execute(id){let executionStopping=false;const halt=()=>{executionStopping=true;};process.on('SIGTERM',halt);process.on('SIGINT',halt);if(!/^[a-f0-9-]{36}$/.test(id))throw Error('INVALID_JOB');let job;for(let i=0;i<20;i++){job=ops.db().jobs.find(j=>j.id===id);if(job?.status==='RUNNING'&&job.pid===process.pid)break;await new Promise(r=>setTimeout(r,100));}if(!job||job.status!=='RUNNING'||job.pid!==process.pid)throw Error('JOB_OWNERSHIP_DENIED');const dir=path.join(config.root,'runs',id);process.chdir(config.repo);if(executionStopping){ops.patchJob(id,{status:'STOPPED'});releaseLeases([path.join(config.root,'execution.lock'),...(job.sourceRun?[path.join(ops.run(job.sourceRun)._directory,'runner.lock')]:[])],process.pid);return;}
 recordJobPhase(config,job,'EXECUTION_STARTED');
 if(job.config.objective==='MATURE_LIFECYCLE'){
  try{const manifest=json(path.join(dir,'manifest.json'));const {lifecycleMain}=await import(pathToFileURL(path.join(config.repo,'docs/catalog/global-47/research-v2/run-v15-mature-v2.mjs')).href);const result=await lifecycleMain(['--lifecycle','--input',manifest.lifecycle.input,'--live'],{diagnosticContext:{purpose:"EXECUTION",jobId:id},expectedOutput:manifest.lifecycle.output,shouldStop:()=>executionStopping||ops.db().jobs.find(j=>j.id===id)?.stopRequested===true});ops.patchJob(id,{status:result.executionComplete&&!executionStopping&&!ops.db().jobs.find(j=>j.id===id)?.stopRequested?'COMPLETE':'STOPPED',finishedAt:new Date().toISOString()});}
  catch(e){ops.patchJob(id,{status:'INTERRUPTED',error:'MATURE_EXECUTION_INTERRUPTED_CHECKPOINT_PRESERVED',finishedAt:new Date().toISOString()});console.error(e.message);}
  finally{try{recordJobPhase(config,job,'EXECUTION_'+ops.db().jobs.find(j=>j.id===id)?.status);}catch{}releaseLeases([path.join(config.root,'execution.lock')],process.pid);}return;
 }
 // Import frozen engine primitives; never patch or invoke the price runner.
 const load=p=>import(pathToFileURL(path.join(config.repo,'services/api/src/research-v2',p)).href);
 const {schedule,summarize}=await load('inventory/login-manage-full-catalog.mjs'),{createV2RobotsPublicAdapter}=await load('live/robots-policy.mjs'),{createTavilySearch}=await load('live/tavily-search.mjs'),{officialCandidate}=await load('live/online-discovery.mjs'),{loadProviderSourceRegistry}=await load('live/provider-source-registry.mjs');
 const manifest=json(path.join(dir,'manifest.json')),registry=loadProviderSourceRegistry({targets:manifest.targets}),ledger=path.join(dir,'network.jsonl'),events=fs.existsSync(ledger)?fs.readFileSync(ledger,'utf8').split('\n').filter(Boolean).map(JSON.parse):[],counts=new Map();let total=0,stop=false;const clients=new Map();for(const e of events)if(e.type==='REQUEST'){total++;counts.set(e.service,(counts.get(e.service)??0)+1);}const log=(type,data)=>fs.appendFileSync(ledger,JSON.stringify({type,at:new Date().toISOString(),...data})+'\n');const reserve=(service,route,data)=>{if(total>=manifest.safety.totalRequests||(counts.get(service)??0)>=manifest.safety.requestsPerService)throw Error('OPERATIONS_REQUEST_BOUND');total++;counts.set(service,(counts.get(service)??0)+1);log('REQUEST',{service,route,...data});};process.on('SIGTERM',()=>{stop=true;});process.on('SIGINT',()=>{stop=true;});
 try{const state=await schedule({dir,manifest,shouldStop:()=>executionStopping||stop||ops.db().jobs.find(j=>j.id===id)?.stopRequested||ops.index().some(r=>r.origin==='CLI'&&r.status==='RUNNING'),onProgress:e=>{log('PROGRESS',e);console.log(JSON.stringify(e));},createAdapters:async()=>({read:async({url,target})=>{requireCapability(resolveCapabilities(manifest.capabilities,'LOGIN_MANAGE'),'direct');return createV2RobotsPublicAdapter({authorities:target.authorities,retainRaw:true,maxLinks:80,maxReads:1,maxRequests:8,network:{pricingResources:false,timeoutMs:15000,maxBytes:2097152,maxRedirects:2}}).read({url,targetCountry:target.market,maxRedirects:2,consumeNetwork:kind=>reserve(target.service,'DIRECT',{kind,url})});},search:async arg=>{requireCapability(resolveCapabilities(manifest.capabilities,'LOGIN_MANAGE'),'tavily');if(!manifest.limits.searches)return {results:[],failure:{code:'DISCOVERY_DISABLED'}};let search=clients.get(arg.target.service);try{if(!search){search=await createTavilySearch({maxCalls:1});clients.set(arg.target.service,search);}}catch{return {results:[],failure:{code:'DISCOVERY_CREDENTIAL_UNAVAILABLE'}};}reserve(arg.target.service,'DISCOVERY',{query:arg.query});const r=await search(arg);log('SEARCH_RESULT',{service:arg.target.service,results:r.results,failure:r.failure});return r;},classify:async({target,page})=>officialCandidate(target,{url:page.url??page.requestedUrl,label:'consumer account management',method:'PROVIDER_NAVIGATION'},registry.domains)})});summarize(dir);ops.patchJob(id,{status:state.complete?'COMPLETE':'STOPPED',finishedAt:new Date().toISOString()});}catch(e){try{summarize(dir);}catch{}ops.patchJob(id,{status:'INTERRUPTED',error:'EXECUTION_INTERRUPTED_CHECKPOINT_PRESERVED',finishedAt:new Date().toISOString()});console.error(e.code??e.message);}finally{releaseLeases([path.join(config.root,'execution.lock'),path.join(ops.run(job.sourceRun)._directory,'runner.lock')],process.pid);}}
if(process.argv[1]&&path.resolve(process.argv[1])===self){if(process.argv[2]==='--execute')await execute(process.argv[3]);else if(process.argv[2]==='--poll'){await runPoller({tick,children:executionChildren,heartbeat:status=>atomic(path.join(config.root,'worker.json'),{pid:process.pid,at:new Date().toISOString(),status,supervised:typeof process.send==='function',read:config.read,manual:config.control,scheduling:config.scheduling})});}else throw Error('Use --poll for the supervised control-plane worker');}
