import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import cp from 'node:child_process';import {syncBuiltinESMExports} from 'node:module';
import {Operations} from './control.mjs';import {operationsRequest} from './http.mjs';import {executionWorkerActive} from './worker-identity.mjs';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'resume-identity-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const ops=new Operations({repo:root,root,read:true,control:true,scheduling:false});const job={id:'12345678-1234-1234-1234-123456789abc',status:'INTERRUPTED',pid:process.pid,actor:'a',stopRequested:false,error:'WORKER_PROCESS_EXITED_CHECKPOINT_PRESERVED'};ops.transaction(db=>db.jobs.push(job));const dir=root+'/runs/'+job.id;fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/checkpoint.json','{"turn":7}');fs.writeFileSync(dir+'/network.jsonl','{"kind":"page"}\n');return {ops,job,dir};}
function inspect(t,repo,job,mode){const worker=path.join(repo,'services/api/src/v2-operations/worker.mjs'),args=['node','--import','tsx',worker,'--execute',mode==='other-job'?'different':job.id];if(process.platform==='linux'){const read=fs.readFileSync;t.mock.method(fs,'readFileSync',function(file,...rest){if(file===`/proc/${job.pid}/cmdline`){if(mode==='unknown')throw Object.assign(Error('denied'),{code:'EACCES'});return args.join('\0')+'\0';}return read.call(this,file,...rest);});}else{t.mock.method(cp,'spawnSync',()=>mode==='unknown'?{error:Error('denied')}:{status:0,stdout:args.join(' ')+'\n',stderr:''});syncBuiltinESMExports();t.after(()=>{t.mock.restoreAll();syncBuiltinESMExports();});}}
test('reused live numeric PID does not block explicit API Resume; retries cannot enqueue twice',async t=>{const {ops,job,dir}=fixture(t);process.kill(job.pid,0);const request=()=>operationsRequest({method:'POST',url:new URL('https://offline.invalid/v1/admin/v2-operations/jobs/'+job.id+'/resume'),body:{},actor:'a'},ops);assert.equal((await request()).status,'QUEUED');assert.equal(ops.db().events.filter(e=>e.type==='RESUME_REQUESTED').length,1);await assert.rejects(request(),/RUN_NOT_RESUMABLE/);assert.equal(fs.readFileSync(dir+'/checkpoint.json','utf8'),'{"turn":7}');assert.equal(fs.readFileSync(dir+'/network.jsonl','utf8'),'{"kind":"page"}\n');});
for(const mode of ['same-job','other-job','unknown'])test('worker inspection '+mode,async t=>{const {ops,job}=fixture(t);inspect(t,ops.config.repo,job,mode);assert.equal(executionWorkerActive(ops.config.repo,job),mode!=='other-job');if(mode==='other-job')assert.equal(ops.control(job.id,'resume','a').status,'QUEUED');else{assert.throws(()=>ops.control(job.id,'resume','a'),/RUN_NOT_RESUMABLE/);assert.equal(ops.db().jobs[0].status,'INTERRUPTED');assert.equal(ops.db().events.length,0);}});
test('actual live child bound to this job blocks Resume until it exits',async t=>{
 const {ops,job}=fixture(t),worker=path.join(ops.config.repo,'services/api/src/v2-operations/worker.mjs');fs.mkdirSync(path.dirname(worker),{recursive:true});fs.writeFileSync(worker,"console.log('ready');setInterval(()=>{},1000);");
 const child=cp.spawn(process.execPath,[worker,'--execute',job.id],{stdio:['ignore','pipe','pipe']});t.after(()=>child.kill());await new Promise((resolve,reject)=>{child.once('error',reject);child.stdout.once('data',resolve);});ops.transaction(db=>{db.jobs[0].pid=child.pid;});
 assert.throws(()=>ops.control(job.id,'resume','a'),/RUN_NOT_RESUMABLE/);assert.equal(ops.db().events.length,0);const exited=new Promise(resolve=>child.once('exit',resolve));child.kill();await exited;assert.equal(ops.control(job.id,'resume','a').status,'QUEUED');assert.equal(ops.db().events.filter(e=>e.type==='RESUME_REQUESTED').length,1);
});
