// Bounded abstract interpretation of retained syntax; never executes provider code.
import ts from 'typescript';import {createHash} from 'node:crypto';
const sha=s=>createHash('sha256').update(s).digest('hex');
export const bounds=Object.freeze({modules:8,importDepth:3,callDepth:6,scriptBytes:524288,totalBytes:4194304,constants:512,properties:2048,candidates:9,paramCombinations:1,rendererLinks:32,work:200000});
const hard=/RESTRICTION|403|AUTHENTICATION|CAPTCHA|CHALLENGE|SECURITY|PAYWALL|PACING|TRANSPORT|CONTENT_HANDLING|LOCALIZED_EXTRACTION|SOURCE_DISCOVERY|NONCANONICAL_ONLY|CONTRACT_EVIDENCE/;
export function activation(gap){const fields=(gap.fields??[]).filter(f=>['plan','amount','currency','cadence','priceRole','ownership','market'].includes(f));return {active:gap.ordinaryAcquisitionComplete===true&&gap.interpretationComplete===true&&gap.providerCodeRelevant===true&&fields.length>0&&!hard.test(gap.blocker??''),fields,reason:hard.test(gap.blocker??'')?'EXCLUDED_BLOCKER':fields.length?'FIELD_GAP':'NO_REQUIRED_FIELD_GAP'};}
export function traceProviderCode(input){
 const active=activation(input.gap),limits={...bounds,...input.limits},stops=[],modules=[],candidates=[],renderers=[],rejections=[];const counts={work:0,constants:0,properties:0,bytes:0};const cache=new Map(),loading=new Set(),seen=new Set();let exhausted=false;
 if(Object.entries(input.limits??{}).some(([k,v])=>!Object.hasOwn(bounds,k)||!Number.isSafeInteger(v)||v<0||v>bounds[k]))return {activation:active,bounds,counts,modules:[],candidates:[],rendererSemantics:[],rejections:[],stops:[{reason:'INVALID_OR_EXPANDED_BOUNDS'}],complete:false,productionPromotion:false};
 const stop=(reason,detail)=>{stops.push({reason,detail});};
 const tick=k=>{if(++counts[k]>(limits[k]??Infinity)){exhausted=true;throw Error('BOUND_'+k);}};
 const loc=(m,n,kind='SYNTAX')=>({status:'PROVEN',kind,module:m.url,sha256:m.hash,start:n.getStart(m.ast),end:n.end});
 const value=(v,proof=[])=>({v,proof}),unknown=(reason,m,n)=>{rejections.push({status:'UNRESOLVED',reason,...(m&&n?{locator:loc(m,n)}:{})});return null;};
 function module(url,depth=0,parentLink=null){tick('work');if(cache.has(url))return cache.get(url);if(loading.has(url)){stop('CYCLIC_IMPORT',url);return null;}if(depth>limits.importDepth){exhausted=true;stop('IMPORT_DEPTH',url);return null;}if(modules.length>=limits.modules){exhausted=true;stop('MODULE_COUNT',url);return null;}
  const src=input.modules.find(x=>x.url===url);if(!src){stop('MISSING_RETAINED_MODULE',url);return null;}if(!src.providerControlled||sha(src.code)!==src.sha256||!(src.parentEvidence||parentLink)){stop('MODULE_PROVENANCE_UNRESOLVED',url);return null;}
  const bytes=Buffer.byteLength(src.code);if(bytes>limits.scriptBytes||counts.bytes+bytes>limits.totalBytes){exhausted=true;stop('SCRIPT_SIZE',url);return null;}counts.bytes+=bytes;loading.add(url);
  const ast=ts.createSourceFile(url,src.code,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);if(ast.parseDiagnostics.length){loading.delete(url);stop('MALFORMED_MODULE',url);return null;}
  const m={url,hash:src.sha256,ast,bindings:new Map(),exports:new Map(),depth,mutated:new Set()};modules.push({url,sha256:src.sha256,bytes,parentEvidence:src.parentEvidence??parentLink,status:'PROVEN'});
  const scan=n=>{tick('work');if(ts.isBinaryExpression(n)&&n.operatorToken.kind>=ts.SyntaxKind.FirstAssignment&&n.operatorToken.kind<=ts.SyntaxKind.LastAssignment){let l=n.left;while(ts.isPropertyAccessExpression(l)||ts.isElementAccessExpression(l))l=l.expression;if(ts.isIdentifier(l)&&l.text!=='exports'&&l.text!=='module')m.mutated.add(l.text);}if(ts.isPrefixUnaryExpression(n)||ts.isPostfixUnaryExpression(n)){if([ts.SyntaxKind.PlusPlusToken,ts.SyntaxKind.MinusMinusToken].includes(n.operator)&&ts.isIdentifier(n.operand))m.mutated.add(n.operand.text);}ts.forEachChild(n,scan);};scan(ast);
  for(const st of ast.statements){
   if(ts.isImportDeclaration(st)&&ts.isStringLiteral(st.moduleSpecifier)){const dest=new URL(st.moduleSpecifier.text,url).href,other=module(dest,depth+1,loc(m,st,'IMPORT')),cl=st.importClause;if(cl?.name)m.bindings.set(cl.name.text,{import:other,name:'default',node:st});if(cl?.namedBindings){if(ts.isNamespaceImport(cl.namedBindings))m.bindings.set(cl.namedBindings.name.text,{namespace:other,node:st});else for(const el of cl.namedBindings.elements)m.bindings.set(el.name.text,{import:other,name:el.propertyName?.text??el.name.text,node:st});}}
   if(ts.isVariableStatement(st))for(const d of st.declarationList.declarations)if(ts.isIdentifier(d.name)){m.bindings.set(d.name.text,{node:d.initializer,constant:!!(st.declarationList.flags&ts.NodeFlags.Const)});if(st.modifiers?.some(x=>x.kind===ts.SyntaxKind.ExportKeyword))m.exports.set(d.name.text,d.name.text);}
   if(ts.isFunctionDeclaration(st)&&st.name){m.bindings.set(st.name.text,{node:st,constant:true});if(st.modifiers?.some(x=>x.kind===ts.SyntaxKind.ExportKeyword))m.exports.set(st.name.text,st.name.text);}
   if(ts.isExpressionStatement(st)&&ts.isBinaryExpression(st.expression)&&st.expression.operatorToken.kind===ts.SyntaxKind.EqualsToken){const e=st.expression,left=e.left.getText(ast);if(/^exports\.[A-Za-z_$][\w$]*$/.test(left)){const name=left.slice(8);m.bindings.set('#cjs-'+name,{node:e.right,constant:true});m.exports.set(name,'#cjs-'+name);}}
   if(ts.isExportAssignment(st))m.bindings.set('#default',{node:st.expression,constant:true}),m.exports.set('default','#default');
   if(ts.isExportDeclaration(st)){const other=st.moduleSpecifier?module(new URL(st.moduleSpecifier.text,url).href,depth+1,loc(m,st,'REEXPORT')):m;if(st.exportClause&&ts.isNamedExports(st.exportClause))for(const el of st.exportClause.elements)m.exports.set(el.name.text,{other,name:el.propertyName?.text??el.name.text,node:st});else if(other)for(const name of other.exports.keys())m.exports.set(name,{other,name,node:st});}
  }
  loading.delete(url);cache.set(url,m);return m;
 }
 const resolving=new Set(),callStack=[];
 function exported(m,name,depth){if(!m)return null;const e=m.exports.get(name);if(typeof e==='string')return binding(m,e,new Map(),depth);if(e)return exported(e.other,e.name,depth);return null;}
 function binding(m,name,env,depth){tick('constants');if(env.has(name))return env.get(name);if(m.mutated.has(name))return unknown('MUTATED_BINDING',m,m.ast);const b=m.bindings.get(name),key=m.url+'#'+name;if(!b||resolving.has(key))return null;resolving.add(key);let r;
  if(b.import!==undefined)r=exported(b.import,b.name,depth);else if(b.namespace!==undefined)r=value({namespace:b.namespace});else if(b.constant)r=ev(b.node,m,env,depth);resolving.delete(key);return r?value(r.v,[loc(m,b.node??m.ast,'BINDING'),...r.proof]):null;
 }
 function ev(n,m,env=new Map(),depth=0){tick('work');if(!n)return null;if(depth>limits.callDepth){exhausted=true;stop('CALL_DEPTH',m.url);return null;}const proof=[loc(m,n)];
  if(ts.isParenthesizedExpression(n)||ts.isAwaitExpression(n))return ev(n.expression,m,env,depth);
  if(ts.isStringLiteral(n)||ts.isNoSubstitutionTemplateLiteral(n))return value(n.text,proof);if(ts.isNumericLiteral(n))return value(Number(n.text),proof);if(n.kind===ts.SyntaxKind.TrueKeyword)return value(true,proof);if(n.kind===ts.SyntaxKind.FalseKeyword)return value(false,proof);
  if(ts.isIdentifier(n))return binding(m,n.text,env,depth);
  if(ts.isArrowFunction(n)||ts.isFunctionExpression(n)||ts.isFunctionDeclaration(n))return value({fn:n,m,env:new Map(env)},proof);
  if(ts.isObjectLiteralExpression(n)){const obj=Object.create(null);for(const p of n.properties){if(ts.isMethodDeclaration(p)){obj[p.name.getText(m.ast)]=value({fn:p,m,env:new Map(env)},[loc(m,p)]);continue;}if(!ts.isPropertyAssignment(p)&&!ts.isShorthandPropertyAssignment(p))return null;const k=p.name.text;if(!k)return null;const v=ev(ts.isShorthandPropertyAssignment(p)?p.name:p.initializer,m,env,depth);if(!v)return null;obj[k]=v;proof.push(...v.proof);}return value(obj,proof);}
  if(ts.isPropertyAccessExpression(n)||ts.isElementAccessExpression(n)){tick('properties');const o=ev(n.expression,m,env,depth),k=ts.isPropertyAccessExpression(n)?value(n.name.text):ev(n.argumentExpression,m,env,depth);if(!o||!k)return null;if(o.v?.namespace)return exported(o.v.namespace,k.v,depth);return o.v&&Object.hasOwn(o.v,k.v)?o.v[k.v]:null;}
  if(ts.isBinaryExpression(n)&&n.operatorToken.kind===ts.SyntaxKind.PlusToken){const a=ev(n.left,m,env,depth),b=ev(n.right,m,env,depth);if(!a||!b||!['string','number'].includes(typeof a.v)||!['string','number'].includes(typeof b.v))return null;return value(a.v+b.v,[...proof,...a.proof,...b.proof]);}
  if(ts.isTemplateExpression(n)){let str=n.head.text;for(const sp of n.templateSpans){const v=ev(sp.expression,m,env,depth);if(!v||!['string','number'].includes(typeof v.v))return null;str+=v.v+sp.literal.text;proof.push(...v.proof);}return value(str,proof);}
  if(ts.isNewExpression(n)&&ts.isIdentifier(n.expression)&&!m.bindings.has(n.expression.text)&&!m.mutated.has(n.expression.text)&&!env.has(n.expression.text)){
   if(n.expression.text==='URLSearchParams'){const a=ev(n.arguments?.[0],m,env,depth);if(!a||typeof a.v!=='object')return null;const pairs=[];for(const [k,v]of Object.entries(a.v)){if(!['string','number','boolean'].includes(typeof v?.v))return null;pairs.push([k,String(v.v)]);}return value({queryString:new URLSearchParams(pairs).toString()},[...proof,...a.proof]);}
   if(n.expression.text==='URL'){const a=ev(n.arguments?.[0],m,env,depth),b=ev(n.arguments?.[1],m,env,depth);if(typeof a?.v!=='string'||n.arguments.length>1&&typeof b?.v!=='string')return null;try{return value({href:value(new URL(a.v,b?.v).href,[...proof,...a.proof,...(b?.proof??[])])},proof);}catch{return null;}}
  }
  if(ts.isCallExpression(n)){
   if(ts.isPropertyAccessExpression(n.expression)&&n.expression.name.text==='toString'&&!n.arguments.length){const a=ev(n.expression.expression,m,env,depth);if(typeof a?.v?.queryString==='string')return value(a.v.queryString,[...proof,...a.proof]);}

   if(ts.isIdentifier(n.expression)&&n.expression.text==='require'&&!m.bindings.has('require')&&!m.mutated.has('require')){const a=ev(n.arguments[0],m,env,depth);if(typeof a?.v!=='string')return null;return value({namespace:module(new URL(a.v,m.url).href,m.depth+1,loc(m,n,'STATIC_REQUIRE'))},proof);}
   if(ts.isIdentifier(n.expression)&&n.expression.text==='fetch'&&!m.bindings.has('fetch')&&!m.mutated.has('fetch')&&!env.has('fetch')){const u=ev(n.arguments[0],m,env,depth),opt=n.arguments[1]?ev(n.arguments[1],m,env,depth):value({});if(typeof u?.v!=='string'||!opt||Object.keys(opt.v).some(k=>k!=='method')||opt.v.method&&opt.v.method.v!=='GET')return unknown('DYNAMIC_OR_NONPUBLIC_REQUEST',m,n);
    let url;try{url=new URL(u.v,m.url);if(url.protocol!=='https:'||url.username||url.password||[...url.searchParams.keys()].some(k=>/token|secret|password|auth|session|key/i.test(k)))return unknown('SENSITIVE_OR_UNSAFE_REQUEST',m,n);}catch{return null;}
    const authority=(input.authorities??[]).find(a=>a.hostname===url.hostname&&a.validated&&a.reference);const chain=[...callStack.flat(),...proof,...u.proof,...(opt.proof??[])];const key=url.href;const commercial=/plan|pric|offer|package|subscription|billing|product|merch|tariff/i.test(url.pathname+chain.map(p=>input.modules.find(m=>m.url===p.module)?.code.slice(p.start,p.end)??'').join(' '));
    if(!seen.has(key)){if(candidates.length>=limits.candidates){exhausted=true;stop('CANDIDATE_COUNT',url.href);return null;}seen.add(key);candidates.push({url:url.href,method:'GET',status:authority?'PROVEN':'UNRESOLVED',acquisitionEligible:!!authority&&commercial,commercialRelevance:commercial,ownership:authority?'PROVIDER_CONTROLLED':'UNRESOLVED_OR_THIRD_PARTY',authority:authority??null,parameters:[...url.searchParams].map(([name,v])=>({name,value:v,proof:chain})),proofChain:chain,evidenceStatus:'DISCOVERY_ONLY',verificationEligible:false});}return null;
   }
   const fn=ev(n.expression,m,env,depth);if(!fn?.v?.fn)return unknown('OPAQUE_CLIENT_OR_CALL',m,n);const args=n.arguments.map(a=>ev(a,m,env,depth));callStack.push([...proof,...fn.proof]);try{return invoke(fn,args,depth+1,proof);}finally{callStack.pop();}
  }
  return null;
 }
 function invoke(f,args,depth,callProof=[]){const {fn,m,env}=f.v,e=new Map(env);for(let i=0;i<fn.parameters.length;i++){const p=fn.parameters[i];if(!ts.isIdentifier(p.name)||p.dotDotDotToken)return null;e.set(p.name.text,args[i]??(p.initializer?ev(p.initializer,m,e,depth):null));}
  let result;if(!ts.isBlock(fn.body))result=ev(fn.body,m,e,depth);else for(const st of fn.body.statements){if(ts.isVariableStatement(st)){if(!(st.declarationList.flags&ts.NodeFlags.Const))return null;for(const d of st.declarationList.declarations){if(!ts.isIdentifier(d.name))return null;e.set(d.name.text,ev(d.initializer,m,e,depth));}}else if(ts.isReturnStatement(st)){result=ev(st.expression,m,e,depth);break;}else if(ts.isExpressionStatement(st))ev(st.expression,m,e,depth);else return unknown('UNSUPPORTED_CONTROL_FLOW',m,st);}return result?value(result.v,[...callProof,...f.proof,...result.proof]):null;
 }
 if(active.active)try{for(const entry of input.entries){const m=module(entry);if(!m)continue;for(const st of m.ast.statements){if(ts.isExpressionStatement(st))ev(st.expression,m);if(ts.isFunctionDeclaration(st)&&!m.mutated.has(st.name?.text)&&st.modifiers?.some(x=>x.kind===ts.SyntaxKind.ExportKeyword))invoke(value({fn:st,m,env:new Map()}),[],0);}
  // Renderer links are advisory syntax evidence, never automatic commercial approvals.
  const visit=n=>{tick('work');
   if(ts.isConditionalExpression(n)||ts.isBinaryExpression(n)&&n.operatorToken.kind===ts.SyntaxKind.PlusToken){const fields=[],labels=[];const collect=x=>{tick('work');if(ts.isPropertyAccessExpression(x)&&/price|currency|renew|recurr|duration|period|promo|billing|offer/i.test(x.name.text))fields.push(x.getText(m.ast));if(ts.isStringLiteral(x)&&x.text.length<=100)labels.push(x.text);ts.forEachChild(x,collect);};collect(n);if(fields.length&&labels.length){if(renderers.length>=limits.rendererLinks){exhausted=true;stop('RENDERER_LIMIT',m.url);}else renderers.push({fields:[...new Set(fields)],labels,kind:ts.isConditionalExpression(n)?'CONDITIONAL_PRESENTATION':'FIELD_LABEL_PRESENTATION',condition:ts.isConditionalExpression(n)?n.condition.getText(m.ast):null,status:'PARTIALLY_PROVEN',locator:loc(m,n),reason:'Static presentation relationship only; no actual API/product/runtime branch established.',verificationEligible:false});}}
   if(ts.isCallExpression(n)&&ts.isPropertyAccessExpression(n.expression)&&n.expression.name.text==='format'&&ts.isNewExpression(n.expression.expression)){const ctor=n.expression.expression;if(ctor.expression.getText(m.ast)==='Intl.NumberFormat'&&!m.bindings.has('Intl')&&!m.mutated.has('Intl')){const opt=ev(ctor.arguments?.[1],m),field=n.arguments[0];if(opt?.v?.style?.v==='currency'&&typeof opt?.v?.currency?.v==='string'&&field&&ts.isPropertyAccessExpression(field)){if(renderers.length>=limits.rendererLinks){exhausted=true;stop('RENDERER_LIMIT',m.url);}else renderers.push({field:field.getText(m.ast),currency:opt.v.currency.v,status:'PARTIALLY_PROVEN',reason:'Formatter code is explicit; API object/product/selected runtime binding still required.',locator:loc(m,n),verificationEligible:false});}}}ts.forEachChild(n,visit);};visit(m.ast);
 }}catch(e){exhausted=true;stop(String(e.message).startsWith('BOUND_')?e.message:'ANALYSIS_UNRESOLVED','No candidate admitted from partial bounded result.');}
 if(exhausted)for(const c of candidates)c.acquisitionEligible=false,c.status='PARTIALLY_PROVEN';
 return {activation:active,bounds:limits,counts,modules,candidates,rendererSemantics:renderers,rejections,stops,complete:!exhausted,productionPromotion:false};
}
